var tz=document.getElementById("timezone");init_timezones();for(var i=0;i<all_timezones.length;i++)tz.options[tz.options.length]=new Option(all_timezones[i].name,all_timezones[i].value);
function onLoad(a){a?(getBG().g_create_account_data?(document.getElementById("email").value=getBG().g_create_account_data.email,document.getElementById("masterpassword").value=getBG().g_create_account_data.masterpassword,document.getElementById("passwordreminder").value=getBG().g_create_account_data.passwordreminder,document.getElementById("timezone").value=getBG().g_create_account_data.timezone,document.getElementById("terms").checked=!0,document.getElementById("data").checked=!0,document.getElementById("history").checked=
getBG().g_create_account_data.history,document.getElementById("improve").checked=getBG().g_create_account_data.improve):tz.value=calculate_time_zone(!1),document.getElementById("email").focus(),update_password_meter(document.getElementById("email").value,document.getElementById("masterpassword").value),document.getElementById("createanaccount")&&(document.getElementById("createanaccount").innerText=gs("Create Account")),document.getElementById("nothanks")&&(document.getElementById("nothanks").innerText=
gs("No Thanks"))):get_data("create_account",function(){onLoad(!0)})}var dobeforeunload=!0;
function do_submit(){var a=document.getElementById("masterpassword").value,b=document.getElementById("email").value,c=document.getElementById("passwordreminder").value;if(""!=welcome_email_check&&"ok"!=welcome_email_check)return alert(welcome_email_check),!1;if(""==welcome_email_check&&5>b.length)return alert(gs("Invalid email address, try again")),!1;if(!document.getElementById("terms").checked)return alert(gs("You must agree to the terms to continue")),!1;if(!document.getElementById("data").checked)return alert(gs("You must agree to send your encrypted data to LastPass.com.\n\nLastPass.com encrypts your data and sends it to its secure servers.\nNo one at LastPass can read your confidential data since it is encrypted using your\nsecret password and you are the only one who knows your password.")),
!1;if(8>a.length)return alert(gs("Your password is too short. It must be at least 8 characters long")),!1;if(a==b)return alert(gs("Your password can not be the same as your email.")),!1;if(a==c)return alert(gs("Password reminder cannot match password")),!1;if(0==c.length)return alert(gs("Please enter a Password Reminder")),!1;if("password"==a||"123"==a||"1234"==a||"12345"==a||"123456"==a||"123123"==a||"letmein"==a||"pass"==a||"lastpass"==a||"lastpass.com"==a||"abc123"==a)return alert(gs("Your password is easily guessable.")),
!1;dobeforeunload=!1;getBG().g_create_account_data=[];getBG().g_create_account_data.email=b;getBG().g_create_account_data.masterpassword=a;getBG().g_create_account_data.passwordreminder=c;getBG().g_create_account_data.timezone=document.getElementById("timezone").value;getBG().g_create_account_data.history=document.getElementById("history").checked;getBG().g_create_account_data.improve=document.getElementById("improve").checked;getBG().update_create_account_data();redirect_to_url("reenter_password.html")}
var welcome_email_check="";function checkEmail(){var a=document.getElementById("email");0<a.value.length&&(welcome_email_check="",getBG().lpMakeRequest(getBG().base_url+"create_account.php?check=avail&username="+getBG().en(a.value),"",lpCheckEmailResponse))}
function lpCheckEmailResponse(a){4==a.readyState&&(200==a.status&&a.responseText)&&(a=a.responseText,welcome_email_check=0<=a.indexOf("ok")?"ok":0<=a.indexOf("emailinvalid")?gs("Invalid email address, try again"):gs("Email already in use, have you forgotten your password?"))};
