document.title=gs("Form Fill Profile");var g_hide_formfill_title=!1;document.getElementById("_docwrite_formfill3")&&(document.getElementById("_docwrite_formfill3").innerHTML=gs("Nameproper",getlocale()));document.getElementById("_docwrite_formfill4")&&(document.getElementById("_docwrite_formfill4").innerHTML=gs("Language",getlocale()));document.getElementById("_docwrite_formfill5")&&(document.getElementById("_docwrite_formfill5").innerHTML=gs("Enable Free Credit Monitoring",getlocale()));
document.getElementById("_docwrite_formfill6")&&(document.getElementById("_docwrite_formfill6").innerHTML=gs("Require Password Reprompt",getlocale()));document.getElementById("_docwrite_formfill7")&&(document.getElementById("_docwrite_formfill7").innerHTML=gs("Personal",getlocale()));document.getElementById("_docwrite_formfill8")&&(document.getElementById("_docwrite_formfill8").innerHTML=gs("Address",getlocale()));
document.getElementById("_docwrite_formfill9")&&(document.getElementById("_docwrite_formfill9").innerHTML=gs("Contact",getlocale()));document.getElementById("_docwrite_formfill10")&&(document.getElementById("_docwrite_formfill10").innerHTML=gs("Credit cardformfill",getlocale()));document.getElementById("_docwrite_formfill11")&&(document.getElementById("_docwrite_formfill11").innerHTML=gs("Bank accountformfill",getlocale()));
document.getElementById("_docwrite_formfill12")&&(document.getElementById("_docwrite_formfill12").innerHTML=gs("Custom fields",getlocale()));document.getElementById("_docwrite_formfill13")&&(document.getElementById("_docwrite_formfill13").innerHTML=gs("Notes",getlocale()));
!1==g_hide_formfill_title?document.getElementById("_docwrite_formfill14")&&(document.getElementById("_docwrite_formfill14").innerHTML=gs("Title",getlocale())):(document.getElementById("_docwrite_formfill14")&&(document.getElementById("_docwrite_formfill14").style.display="none"),document.getElementById("titlerow")&&(document.getElementById("titlerow").style.display="none"));
document.getElementById("_docwrite_formfill15")&&(document.getElementById("_docwrite_formfill15").innerHTML=gs("First name",getlocale()));document.getElementById("_docwrite_formfill16")&&(document.getElementById("_docwrite_formfill16").innerHTML=gs("Middle name",getlocale()));document.getElementById("_docwrite_formfill17")&&(document.getElementById("_docwrite_formfill17").innerHTML=gs("Last name",getlocale()));
document.getElementById("_docwrite_formfill18")&&(document.getElementById("_docwrite_formfill18").innerHTML=gs("Japanese Only -- Name Std",getlocale()));document.getElementById("_docwrite_formfill19")&&(document.getElementById("_docwrite_formfill19").innerHTML=gs("Japanese Only -- Last Std",getlocale()));document.getElementById("_docwrite_formfill20")&&(document.getElementById("_docwrite_formfill20").innerHTML=gs("Japanese Only -- First Std",getlocale()));
document.getElementById("_docwrite_formfill21")&&(document.getElementById("_docwrite_formfill21").innerHTML=gs("Japanese Only -- Name Fur",getlocale()));document.getElementById("_docwrite_formfill22")&&(document.getElementById("_docwrite_formfill22").innerHTML=gs("Japanese Only -- Last Fur",getlocale()));document.getElementById("_docwrite_formfill23")&&(document.getElementById("_docwrite_formfill23").innerHTML=gs("Japanese Only -- First Fur",getlocale()));
document.getElementById("_docwrite_formfill24")&&(document.getElementById("_docwrite_formfill24").innerHTML=gs("Japanese Only -- Name Rom",getlocale()));document.getElementById("_docwrite_formfill25")&&(document.getElementById("_docwrite_formfill25").innerHTML=gs("Japanese Only -- Last Rom",getlocale()));document.getElementById("_docwrite_formfill26")&&(document.getElementById("_docwrite_formfill26").innerHTML=gs("Japanese Only -- First Rom",getlocale()));
document.getElementById("_docwrite_formfill27")&&(document.getElementById("_docwrite_formfill27").innerHTML=gs("Last Name2",getlocale()));document.getElementById("_docwrite_formfill28")&&(document.getElementById("_docwrite_formfill28").innerHTML=gs("User name",getlocale()));document.getElementById("_docwrite_formfill29")&&(document.getElementById("_docwrite_formfill29").innerHTML=gs("Gender",getlocale()));
document.getElementById("_docwrite_formfill30")&&(document.getElementById("_docwrite_formfill30").innerHTML=gs("Birthday",getlocale()));document.getElementById("_docwrite_formfill31")&&(document.getElementById("_docwrite_formfill31").innerHTML=gs("Social security number",getlocale()));document.getElementById("_docwrite_formfill32")&&(document.getElementById("_docwrite_formfill32").innerHTML=gs("Company",getlocale()));
document.getElementById("_docwrite_formfill33")&&(document.getElementById("_docwrite_formfill33").innerHTML=gs("Address 1",getlocale()));document.getElementById("_docwrite_formfill34")&&(document.getElementById("_docwrite_formfill34").innerHTML=gs("Address 2",getlocale()));document.getElementById("_docwrite_formfill35")&&(document.getElementById("_docwrite_formfill35").innerHTML=gs("Address 3",getlocale()));
document.getElementById("_docwrite_formfill36")&&(document.getElementById("_docwrite_formfill36").innerHTML=gs("City / Town",getlocale()));document.getElementById("_docwrite_formfill37")&&(document.getElementById("_docwrite_formfill37").innerHTML=gs("County",getlocale()));document.getElementById("_docwrite_formfill38")&&(document.getElementById("_docwrite_formfill38").innerHTML=gs("State / Province",getlocale()));
document.getElementById("_docwrite_formfill39")&&(document.getElementById("_docwrite_formfill39").innerHTML=gs("ZIP / Postal code",getlocale()));document.getElementById("_docwrite_formfill40")&&(document.getElementById("_docwrite_formfill40").innerHTML=gs("Country",getlocale()));document.getElementById("_docwrite_formfill41")&&(document.getElementById("_docwrite_formfill41").innerHTML=gs("Time Zone",getlocale()));
document.getElementById("_docwrite_formfill42")&&(document.getElementById("_docwrite_formfill42").innerHTML=gs("Email address",getlocale()));document.getElementById("_docwrite_formfill43")&&(document.getElementById("_docwrite_formfill43").innerHTML=gs("Mobile Email Address",getlocale()));document.getElementById("_docwrite_formfill44")&&(document.getElementById("_docwrite_formfill44").innerHTML=gs("Phone number",getlocale()));
document.getElementById("_docwrite_formfill45")&&(document.getElementById("_docwrite_formfill45").innerHTML=gs("ext.",getlocale()));document.getElementById("_docwrite_formfill46")&&(document.getElementById("_docwrite_formfill46").innerHTML=gs("Evening number",getlocale()));document.getElementById("_docwrite_formfill47")&&(document.getElementById("_docwrite_formfill47").innerHTML=gs("ext.",getlocale()));
document.getElementById("_docwrite_formfill48")&&(document.getElementById("_docwrite_formfill48").innerHTML=gs("Fax number",getlocale()));document.getElementById("_docwrite_formfill49")&&(document.getElementById("_docwrite_formfill49").innerHTML=gs("ext.",getlocale()));document.getElementById("_docwrite_formfill50")&&(document.getElementById("_docwrite_formfill50").innerHTML=gs("Mobile number",getlocale()));
document.getElementById("_docwrite_formfill51")&&(document.getElementById("_docwrite_formfill51").innerHTML=gs("ext.",getlocale()));document.getElementById("_docwrite_formfill52")&&(document.getElementById("_docwrite_formfill52").innerHTML=gs("Name on card",getlocale()));document.getElementById("_docwrite_formfill53")&&(document.getElementById("_docwrite_formfill53").innerHTML=gs("Credit card number",getlocale()));
document.getElementById("_docwrite_formfill54")&&(document.getElementById("_docwrite_formfill54").innerHTML=gs("Start date",getlocale()));document.getElementById("_docwrite_formfill55")&&(document.getElementById("_docwrite_formfill55").innerHTML=gs("Expiration date",getlocale()));document.getElementById("_docwrite_formfill56")&&(document.getElementById("_docwrite_formfill56").innerHTML=gs("Security code",getlocale()));
document.getElementById("_docwrite_formfill57")&&(document.getElementById("_docwrite_formfill57").innerHTML=gs("Issue number",getlocale()));document.getElementById("_docwrite_formfill58")&&(document.getElementById("_docwrite_formfill58").innerHTML=gs("Bank name",getlocale()));document.getElementById("_docwrite_formfill59")&&(document.getElementById("_docwrite_formfill59").innerHTML=gs("Account number",getlocale()));
document.getElementById("_docwrite_formfill60")&&(document.getElementById("_docwrite_formfill60").innerHTML=gs("Routing number",getlocale()));document.getElementById("_docwrite_formfill61")&&(document.getElementById("_docwrite_formfill61").innerHTML=gs("Text to find",getlocale()));document.getElementById("_docwrite_formfill62")&&(document.getElementById("_docwrite_formfill62").innerHTML=gs("Value to fill",getlocale()));
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){on_load()});document.getElementById("lpform").onsubmit=function(){return!1};document.getElementById("close1").addEventListener("mouseover",function(){ttabove(this,gt("Close this window"))});document.getElementById("close2").addEventListener("mouseover",function(){ttabove(this,gt("Close this window"))});document.getElementById("ff_name").addEventListener("mouseover",function(){ttabove(this,gt("The name of the Form Fill profile"))});
document.getElementById("ff_language").addEventListener("mouseover",function(){ttabove(this,gt("The language of the Web sites where this Form Fill profile will be used"))});document.getElementById("ff_creditmon").addEventListener("mouseover",function(){ttabover(this,gt("If checked, your credit report will be regularly monitored and you will be alerted if any suspicious activity occurs."))});document.getElementById("ff_protected").addEventListener("mouseover",function(){ttabover(this,gt("If checked, you will be asked to re-enter your master password<br/>before being able to access this Form Fill profile"))});
document.getElementById("ff_title").addEventListener("mouseover",function(){ttabove(this,gt("Your prefix or title"))});document.getElementById("ff_firstname").addEventListener("mouseover",function(){ttabove(this,gt("Your first name"))});document.getElementById("ff_middlename").addEventListener("mouseover",function(){ttabove(this,gt("Your middle name"))});document.getElementById("ff_lastname").addEventListener("mouseover",function(){ttabove(this,gt("Your last name"))});document.getElementById("ff_username").addEventListener("mouseover",
function(){ttabove(this,gt("Your username when signing into Web sites"))});document.getElementById("ff_gender").addEventListener("mouseover",function(){ttabove(this,gt("Your sex"))});document.getElementById("ff_birthday_month").addEventListener("mouseover",function(){ttabove(this,gt("Your birth month"))});document.getElementById("ff_birthday_day").addEventListener("mouseover",function(){ttabove(this,gt("Your birth day"))});document.getElementById("ff_birthday_year").addEventListener("mouseover",function(){ttabove(this,
gt("Your 4 digit birth year"))});document.getElementById("ff_ssn").addEventListener("mouseover",function(){ttabove(this,gt("Your government ID number"))});document.getElementById("ff_company").addEventListener("mouseover",function(){ttabove(this,gt("Your company's name"))});document.getElementById("ff_address1").addEventListener("mouseover",function(){ttabove(this,gt("Your street address"))});document.getElementById("ff_address2").addEventListener("mouseover",function(){ttabove(this,gt("Your street address"))});
document.getElementById("ff_address3").addEventListener("mouseover",function(){ttabove(this,gt("Your street address"))});document.getElementById("ff_city").addEventListener("mouseover",function(){ttabove(this,gt("Your city name"))});document.getElementById("ff_county").addEventListener("mouseover",function(){ttabove(this,gt("Your county name"))});document.getElementById("ff_state").addEventListener("mouseover",function(){ttabove(this,gt("Your state or province name"))});document.getElementById("ff_zip").addEventListener("mouseover",
function(){ttabove(this,gt("Your ZIP or postal code"))});document.getElementById("ff_country").addEventListener("mouseover",function(){ttabove(this,gt("Your country name"))});document.getElementById("ff_timezone").addEventListener("mouseover",function(){ttabove(this,gt("Your time zone"))});document.getElementById("ff_email").addEventListener("mouseover",function(){ttabove(this,gt("Your email address"))});document.getElementById("ff_countryphone").addEventListener("mouseover",function(){ttabove(this,
gt("Your country name"))});document.getElementById("ff_npaphone").addEventListener("mouseover",function(){ttabove(this,gt("First 3 digits of your phone number"))});document.getElementById("ff_nxxphone").addEventListener("mouseover",function(){ttabove(this,gt("Middle 3 digits of your phone number"))});document.getElementById("ff_xxxxphone").addEventListener("mouseover",function(){ttabove(this,gt("Last 4 digits of your phone number"))});document.getElementById("ff_intnumphone").addEventListener("mouseover",
function(){ttabove(this,gt("Your phone number"))});document.getElementById("ff_extphone").addEventListener("mouseover",function(){ttabove(this,gt("Your phone number extension"))});document.getElementById("ff_countryeve").addEventListener("mouseover",function(){ttabove(this,gt("Your country name"))});document.getElementById("ff_npaeve").addEventListener("mouseover",function(){ttabove(this,gt("First 3 digits of your phone number"))});document.getElementById("ff_nxxeve").addEventListener("mouseover",
function(){ttabove(this,gt("Middle 3 digits of your phone number"))});document.getElementById("ff_xxxxeve").addEventListener("mouseover",function(){ttabove(this,gt("Last 4 digits of your phone number"))});document.getElementById("ff_intnumeve").addEventListener("mouseover",function(){ttabove(this,gt("Your phone number"))});document.getElementById("ff_exteve").addEventListener("mouseover",function(){ttabove(this,gt("Your phone number extension"))});document.getElementById("ff_countryfax").addEventListener("mouseover",
function(){ttabove(this,gt("Your country name"))});document.getElementById("ff_npafax").addEventListener("mouseover",function(){ttabove(this,gt("First 3 digits of your phone number"))});document.getElementById("ff_nxxfax").addEventListener("mouseover",function(){ttabove(this,gt("Middle 3 digits of your phone number"))});document.getElementById("ff_xxxxfax").addEventListener("mouseover",function(){ttabove(this,gt("Last 4 digits of your phone number"))});document.getElementById("ff_intnumfax").addEventListener("mouseover",
function(){ttabove(this,gt("Your phone number"))});document.getElementById("ff_extfax").addEventListener("mouseover",function(){ttabove(this,gt("Your phone number extension"))});document.getElementById("ff_countrymobile").addEventListener("mouseover",function(){ttabove(this,gt("Your country name"))});document.getElementById("ff_npamobile").addEventListener("mouseover",function(){ttabove(this,gt("First 3 digits of your phone number"))});document.getElementById("ff_nxxmobile").addEventListener("mouseover",
function(){ttabove(this,gt("Middle 3 digits of your phone number"))});document.getElementById("ff_xxxxmobile").addEventListener("mouseover",function(){ttabove(this,gt("Last 4 digits of your phone number"))});document.getElementById("ff_intnummobile").addEventListener("mouseover",function(){ttabove(this,gt("Your phone number"))});document.getElementById("ff_extmobile").addEventListener("mouseover",function(){ttabove(this,gt("Your phone number extension"))});document.getElementById("ff_ccname").addEventListener("mouseover",
function(){ttabove(this,gt("The full name printed on the credit card"))});document.getElementById("ff_ccnum").addEventListener("mouseover",function(){ttabove(this,gt("The credit card number"))});document.getElementById("ff_ccstart_month").addEventListener("mouseover",function(){ttabove(this,gt("The month the credit card was issued"))});document.getElementById("ff_ccstart_year").addEventListener("mouseover",function(){ttabove(this,gt("The 4 digit year the credit card was issued"))});document.getElementById("ff_ccexp_month").addEventListener("mouseover",
function(){ttabove(this,gt("The credit card's expiration month"))});document.getElementById("ff_ccexp_year").addEventListener("mouseover",function(){ttabove(this,gt("The credit card's 4 digit expiration year"))});document.getElementById("ff_cccsc").addEventListener("mouseover",function(){ttabove(this,gt("The credit card's security code.<br/>For most credit cards, this is the last 3 digits of a number printed on the back of the card.<br/>For American Express credit cards, it is the last 4 digits of a number printed in small print on the front of the card."))});
document.getElementById("ff_ccissuenum").addEventListener("mouseover",function(){ttabove(this,gt("The credit card's issue number.<br/>Only applicable to certain European brands of debit cards, such as Maestro."))});document.getElementById("ff_bankname").addEventListener("mouseover",function(){ttabove(this,gt("The name of your bank"))});document.getElementById("ff_bankacctnum").addEventListener("mouseover",function(){ttabove(this,gt("Your bank account number.<br/>This number can typically be found to the right of the routing number on your personal checks."))});
document.getElementById("ff_bankroutingnum").addEventListener("mouseover",function(){ttabove(this,gt("Your bank's routing number.<br/>This 9 digit number can typically be found on your personal checks in the bottom left corner."))});document.getElementById("ff_addcustomfield").addEventListener("mouseover",function(){ttabove(this,gt("Shows another custom field entry"))});document.getElementById("ff_notes").addEventListener("mouseover",function(){ttabove(this,gt("Arbitrary notes to store along with this Form Fill profile"))});
document.getElementById("pff_delete").addEventListener("mouseover",function(){ttabove(this,gt("Delete this form fill profile"))});document.getElementById("pff_done").addEventListener("mouseover",function(){ttabove(this,gt("Save your changes and close this window"))});document.getElementById("pff_cancel").addEventListener("mouseover",function(){ttabove(this,gt("Discard changes and close this window"))});document.getElementById("close1").addEventListener("mouseout",function(){ttoff()});document.getElementById("close2").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_name").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_language").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_creditmon").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_protected").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_title").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_firstname").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_middlename").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_lastname").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_username").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_gender").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_birthday_month").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_birthday_day").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_birthday_year").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_ssn").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_company").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_address1").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_address2").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_address3").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_city").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_county").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_state").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_zip").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_country").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_timezone").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_email").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_countryphone").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_npaphone").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_nxxphone").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_xxxxphone").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_intnumphone").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_extphone").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_countryeve").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_npaeve").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_nxxeve").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_xxxxeve").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_intnumeve").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_exteve").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_countryfax").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_npafax").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_nxxfax").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_xxxxfax").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_intnumfax").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_extfax").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_countrymobile").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_npamobile").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_nxxmobile").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_xxxxmobile").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_intnummobile").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_extmobile").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_ccname").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_ccnum").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_ccstart_month").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_ccstart_year").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_ccexp_month").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_ccexp_year").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_cccsc").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_ccissuenum").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_bankname").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_bankacctnum").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_bankroutingnum").addEventListener("mouseout",
function(){ttoff()});document.getElementById("ff_addcustomfield").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_notes").addEventListener("mouseout",function(){ttoff()});document.getElementById("pff_delete").addEventListener("mouseout",function(){ttoff()});document.getElementById("pff_done").addEventListener("mouseout",function(){ttoff()});document.getElementById("pff_cancel").addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_language").addEventListener("change",
function(){retranslate();fix_states()});document.getElementById("ff_birthday_month").addEventListener("change",function(){ff_fix_birthday()});document.getElementById("ff_birthday_year").addEventListener("change",function(){ff_fix_birthday()});document.getElementById("ff_state").addEventListener("change",function(){ff_state_changed()});document.getElementById("ff_countryphone").addEventListener("change",function(){fix_phone(this)});document.getElementById("ff_countryeve").addEventListener("change",
function(){fix_phone(this)});document.getElementById("ff_countryfax").addEventListener("change",function(){fix_phone(this)});document.getElementById("ff_countrymobile").addEventListener("change",function(){fix_phone(this)});document.getElementById("ff_tabpersonal").onclick=function(){return ffshow("ff_panepersonal")};document.getElementById("ff_tabaddress").onclick=function(){return ffshow("ff_paneaddress")};document.getElementById("ff_tabcontact").onclick=function(){return ffshow("ff_panecontact")};
document.getElementById("ff_tabcreditcard").onclick=function(){return ffshow("ff_panecreditcard")};document.getElementById("ff_tabbankaccount").onclick=function(){return ffshow("ff_panebankaccount")};document.getElementById("ff_tabcustomfields").onclick=function(){return ffshow("ff_panecustomfields")};document.getElementById("ff_tabnotes").onclick=function(){return ffshow("ff_panenotes")};document.getElementById("ff_addcustomfield").onclick=function(){return ff_addcustomfield()};document.getElementById("pff_delete").onclick=
function(){return pff_delete()};document.getElementById("pff_done").onclick=function(){return pff_save()};document.getElementById("pff_cancel").onclick=function(){return pff_cancel()};document.getElementById("ff_npaphone").addEventListener("keyup",function(a){onkeyupnpa(this,a)});document.getElementById("ff_nxxphone").addEventListener("keyup",function(a){onkeyupnxx(this,a)});document.getElementById("ff_xxxxphone").addEventListener("keyup",function(a){onkeyupxxxx(this,a)});document.getElementById("ff_npaeve").addEventListener("keyup",
function(a){onkeyupnpa(this,a)});document.getElementById("ff_nxxeve").addEventListener("keyup",function(a){onkeyupnxx(this,a)});document.getElementById("ff_xxxxeve").addEventListener("keyup",function(a){onkeyupxxxx(this,a)});document.getElementById("ff_npafax").addEventListener("keyup",function(a){onkeyupnpa(this,a)});document.getElementById("ff_nxxfax").addEventListener("keyup",function(a){onkeyupnxx(this,a)});document.getElementById("ff_xxxxfax").addEventListener("keyup",function(a){onkeyupxxxx(this,
a)});document.getElementById("ff_npamobile").addEventListener("keyup",function(a){onkeyupnpa(this,a)});document.getElementById("ff_nxxmobile").addEventListener("keyup",function(a){onkeyupnxx(this,a)});document.getElementById("ff_xxxxmobile").addEventListener("keyup",function(a){onkeyupxxxx(this,a)});document.getElementById("ff_nxxphone").addEventListener("keydown",function(){onkeydownnxx(this,event)});document.getElementById("ff_xxxxphone").addEventListener("keydown",function(){onkeydownxxxx(this,
event)});document.getElementById("ff_extphone").addEventListener("keydown",function(){onkeydownext(this,event)});document.getElementById("ff_nxxeve").addEventListener("keydown",function(){onkeydownnxx(this,event)});document.getElementById("ff_xxxxeve").addEventListener("keydown",function(){onkeydownxxxx(this,event)});document.getElementById("ff_exteve").addEventListener("keydown",function(){onkeydownext(this,event)});document.getElementById("ff_nxxfax").addEventListener("keydown",function(){onkeydownnxx(this,
event)});document.getElementById("ff_xxxxfax").addEventListener("keydown",function(){onkeydownxxxx(this,event)});document.getElementById("ff_extfax").addEventListener("keydown",function(){onkeydownext(this,event)});document.getElementById("ff_nxxmobile").addEventListener("keydown",function(){onkeydownnxx(this,event)});document.getElementById("ff_xxxxmobile").addEventListener("keydown",function(){onkeydownxxxx(this,event)});document.getElementById("ff_extmobile").addEventListener("keydown",function(){onkeydownext(this,
event)})});
