function iScroll(a,b){this.element="object"==typeof a?a:document.getElementById(a);this.wrapper=this.element.parentNode;this.wrapper.style.overflow="hidden";this.wrapper.style.position="relative";this.element.style.webkitTransitionProperty="-webkit-transform";this.element.style.webkitTransitionTimingFunction="cubic-bezier(0,0,0.25,1)";this.element.style.webkitTransitionDuration="0";this.element.style.webkitTransform="translate3d(0,0,0)";this.options={bounce:!0,hScrollBar:!0,vScrollBar:!0};if("object"==
typeof b)for(var c in b)this.options[c]=b[c];this.refresh();this.element.addEventListener("touchstart",this);this.element.addEventListener("touchmove",this);this.element.addEventListener("touchend",this);this.element.addEventListener("DOMSubtreeModified",this);window.addEventListener("orientationchange",this)}
iScroll.prototype={_x:0,_y:0,handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a);break;case "webkitTransitionEnd":this.onTransitionEnd(a);break;case "orientationchange":this.refresh();break;case "DOMSubtreeModified":this.refresh()}},refresh:function(){this.element.style.webkitTransitionDuration="0";this.scrollWidth=this.wrapper.clientWidth;this.scrollHeight=this.wrapper.clientHeight;try{if("undefined"!=
typeof LPFromWebsite&&"undefined"!=typeof LPFromWebsite.ipad&&"undefined"!=typeof $.tree){var a=0;1==$.tree.focused().container.children().length&&0<$.tree.focused().container.children().children().length&&(a=$.tree.focused().container.children().children()[$.tree.focused().container.children().children().length-1].clientHeight);this.scrollHeight-=20+a}}catch(b){}this.maxScrollX=this.scrollWidth-this.element.offsetWidth;this.maxScrollY=this.scrollHeight-this.element.offsetHeight;var a=this._x,c=this._y;
this.scrollX&&this._x<this.maxScrollX&&(a=this.maxScrollX);this.scrollY&&this._y<this.maxScrollY&&(c=this.maxScrollY);this.scrollTo(a,c,"0");this.scrollX=this.element.offsetWidth>this.scrollWidth?!0:!1;this.scrollY=this.element.offsetHeight>this.scrollHeight?!0:!1;this.options.hScrollBar&&this.scrollX?(this.scrollBarX=new scrollbar("horizontal",this.wrapper),this.scrollBarX.init(this.scrollWidth,this.element.offsetWidth)):this.scrollBarX&&(this.scrollBarX=this.scrollBarX.remove());this.options.vScrollBar&&
this.scrollY?(this.scrollBarY=new scrollbar("vertical",this.wrapper),this.scrollBarY.init(this.scrollHeight,this.element.offsetHeight)):this.scrollBarY&&(this.scrollBarY=this.scrollBarY.remove())},setPosition:function(a,b){this._x=null!==a?a:this._x;this._y=null!==b?b:this._y;this.element.style.webkitTransform="translate3d("+this._x+"px,"+this._y+"px,0)";this.scrollBarX&&this.scrollBarX.setPosition(this.scrollBarX.maxScroll/this.maxScrollX*this._x);this.scrollBarY&&this.scrollBarY.setPosition(this.scrollBarY.maxScroll/
this.maxScrollY*this._y)},onTouchStart:function(a){if(1!=a.targetTouches.length)return!1;a.preventDefault();a.stopPropagation();this.element.style.webkitTransitionDuration="0";this.scrollBarX&&(this.scrollBarX.bar.style.webkitTransitionDuration="0, 250ms");this.scrollBarY&&(this.scrollBarY.bar.style.webkitTransitionDuration="0, 250ms");var b=new WebKitCSSMatrix(window.getComputedStyle(this.element).webkitTransform);(b.m41!=this._x||b.m42!=this._y)&&this.setPosition(b.m41,b.m42);this.touchStartX=a.touches[0].pageX;
this.scrollStartX=this._x;this.touchStartY=a.touches[0].pageY;this.scrollStartY=this._y;this.scrollStartTime=a.timeStamp;this.moved=!1},onTouchMove:function(a){if(1!=a.targetTouches.length)return!1;var b=!0===this.scrollX?a.touches[0].pageX-this.touchStartX:0,c=!0===this.scrollY?a.touches[0].pageY-this.touchStartY:0;if(0<this._x||this._x<this.maxScrollX)b=Math.round(b/4);if(0<this._y||this._y<this.maxScrollY)c=Math.round(c/4);this.scrollBarX&&!this.scrollBarX.visible&&this.scrollBarX.show();this.scrollBarY&&
!this.scrollBarY.visible&&this.scrollBarY.show();this.setPosition(this._x+b,this._y+c);this.touchStartX=a.touches[0].pageX;this.touchStartY=a.touches[0].pageY;this.moved=!0;250<a.timeStamp-this.scrollStartTime&&(this.scrollStartX=this._x,this.scrollStartY=this._y,this.scrollStartTime=a.timeStamp)},onTouchEnd:function(a){if(0<a.targetTouches.length)return!1;if(!this.moved){var b=document.createEvent("MouseEvents");b.initMouseEvent("click",!0,!0,document.defaultView,0,0,0,0,0,0,0,0,0,0,0,null);a.changedTouches[0].target.dispatchEvent(b);
return!1}a=a.timeStamp-this.scrollStartTime;var b=!0===this.scrollX?this.momentum(this._x-this.scrollStartX,a,-this._x+50,this._x+this.element.offsetWidth-this.scrollWidth+50):{dist:0,time:0},c=!0===this.scrollY?this.momentum(this._y-this.scrollStartY,a,-this._y+50,this._y+this.element.offsetHeight-this.scrollHeight+50):{dist:0,time:0};if(!b.dist&&!c.dist)return this.onTransitionEnd(),!1;a=Math.max(b.time,c.time);b=this._x+b.dist;c=this._y+c.dist;this.element.addEventListener("webkitTransitionEnd",
this);this.scrollTo(b,c,a+"ms");this.scrollBarX&&this.scrollBarX.scrollTo(this.scrollBarX.maxScroll/this.maxScrollX*b,a+"ms");this.scrollBarY&&this.scrollBarY.scrollTo(this.scrollBarY.maxScroll/this.maxScrollY*c,a+"ms")},onTransitionEnd:function(){this.element.removeEventListener("webkitTransitionEnd",this);this.resetPosition();this.scrollBarX&&this.scrollBarX.hide();this.scrollBarY&&this.scrollBarY.hide()},resetPosition:function(){var a=resetY=null;if(0<this._x||this._x<this.maxScrollX)a=0<=this._x?
0:this.maxScrollX;if(0<this._y||this._y<this.maxScrollY)resetY=0<=this._y?0:this.maxScrollY;if(null!==a||null!==resetY)this.scrollTo(a,resetY,"500ms"),this.scrollBarX&&this.scrollBarX.scrollTo(this.scrollBarX.maxScroll/this.maxScrollX*(a||this._x),"500ms"),this.scrollBarY&&this.scrollBarY.scrollTo(this.scrollBarY.maxScroll/this.maxScrollY*(resetY||this._y),"500ms")},scrollTo:function(a,b,c){this.element.style.webkitTransitionDuration=c||"400ms";this.setPosition(a,b)},momentum:function(a,b,c,e){friction=
0.1;deceleration=1.5;var d=1E3*(Math.abs(a)/b);b=d*d/(20*friction)/1E3;0<a&&void 0!==c&&b>c&&(d=d*c/b,b=c);0>a&&void 0!==e&&b>e&&(d=d*e/b,b=e);c=-d/-deceleration;1>c&&(c=1);return{dist:Math.round(b*(0>a?-1:1)),time:Math.round(c)}}};
var scrollbar=function(a,b){this.dir=a;this.bar=document.createElement("div");this.bar.className="scrollbar "+a;this.bar.style.webkitTransitionTimingFunction="cubic-bezier(0,0,0.25,1)";this.bar.style.webkitTransform="translate3d(0,0,0)";this.bar.style.webkitTransitionProperty="-webkit-transform,opacity";this.bar.style.webkitTransitionDuration="0,250ms";this.bar.style.pointerEvents="none";this.bar.style.opacity="0";b.appendChild(this.bar)};
scrollbar.prototype={size:0,maxSize:0,maxScroll:0,visible:!1,init:function(a,b){var c="horizontal"==this.dir?this.bar.offsetWidth-this.bar.clientWidth:this.bar.offsetHeight-this.bar.clientHeight;this.maxSize=a-8;this.size=Math.round(this.maxSize*this.maxSize/b)+c;this.maxScroll=this.maxSize-this.size;this.bar.style["horizontal"==this.dir?"width":"height"]=this.size-c+"px"},setPosition:function(a){0>a?a=0:a>this.maxScroll&&(a=this.maxScroll);a="horizontal"==this.dir?"translate3d("+Math.round(a)+"px,0,0)":
"translate3d(0,"+Math.round(a)+"px,0)";this.bar.style.webkitTransform=a},scrollTo:function(a,b){this.bar.style.webkitTransitionDuration=(b||"400ms")+",250ms";this.setPosition(a)},show:function(){this.visible=!0;this.bar.style.opacity="1"},hide:function(){this.visible=!1;this.bar.style.opacity="0"},remove:function(){this.bar.parentNode.removeChild(this.bar);return null}};
