document.title=gs("Login");document.getElementById("_docwrite_login2")&&(document.getElementById("_docwrite_login2").innerHTML=gs("Your current settings require you to enter your LastPass password to complete this action."));
document.getElementById("_docwrite_login3")&&(document.getElementById("_docwrite_login3").innerHTML=gs("The version of Chrome you are currently running does not have HTML5 database support enabled.  As such, this login page will not remember your email and password, and other features such as automatic login on browser restart will not work.  You may be able to fix this by adding --enable-databases as a parameter to your Google Chrome browser shortcut.")+" "+gs("You may also be blocking all cookies, which causes Chrome to disallow HTML5 database access."));
document.getElementById("_docwrite_login4")&&(document.getElementById("_docwrite_login4").innerHTML=gs("Email"));document.getElementById("_docwrite_login5")&&(document.getElementById("_docwrite_login5").innerHTML=gs("Password"));document.getElementById("_docwrite_login6")&&(document.getElementById("_docwrite_login6").innerHTML=gs("Remember Email"));document.getElementById("_docwrite_login7")&&(document.getElementById("_docwrite_login7").innerHTML=gs("Remember Password"));
document.getElementById("_docwrite_login8")&&(document.getElementById("_docwrite_login8").innerHTML=gs("Show My LastPass Vault After Login"));document.getElementById("_docwrite_login9")&&(document.getElementById("_docwrite_login9").innerHTML=gs("Do not re-prompt for "));document.getElementById("_docwrite_login10")&&(document.getElementById("_docwrite_login10").innerHTML="30 "+gs("seconds"));
document.getElementById("_docwrite_login11")&&(document.getElementById("_docwrite_login11").innerHTML="60 "+gs("seconds"));document.getElementById("_docwrite_login12")&&(document.getElementById("_docwrite_login12").innerHTML="5 "+gs("minutes"));document.getElementById("_docwrite_login13")&&(document.getElementById("_docwrite_login13").innerHTML="15 "+gs("minutes"));document.getElementById("_docwrite_login14")&&(document.getElementById("_docwrite_login14").innerHTML="30 "+gs("minutes"));
document.getElementById("_docwrite_login15")&&(document.getElementById("_docwrite_login15").innerHTML="1 "+gs("hour"));document.getElementById("_docwrite_login16")&&(document.getElementById("_docwrite_login16").innerHTML="3 "+gs("hours"));document.getElementById("_docwrite_login17")&&(document.getElementById("_docwrite_login17").innerHTML="6 "+gs("hours"));document.getElementById("_docwrite_login24")&&(document.getElementById("_docwrite_login24").innerHTML="8 "+gs("hours"));
document.getElementById("_docwrite_login18")&&(document.getElementById("_docwrite_login18").innerHTML="12 "+gs("hours"));document.getElementById("_docwrite_login19")&&(document.getElementById("_docwrite_login19").innerHTML="24 "+gs("hours"));document.getElementById("_docwrite_login20")&&(document.getElementById("_docwrite_login20").innerHTML=gs("I forgot my password, Help!"));document.getElementById("_docwrite_login21")&&(document.getElementById("_docwrite_login21").innerHTML=gs("Screen Keyboard"));
document.getElementById("_docwrite_login22")&&(document.getElementById("_docwrite_login22").innerHTML=gs("Create Account"));
if(g_issafari||g_isopera)document.getElementById("logoimg")&&(document.getElementById("logoimg").src="images/lp_signin_logo.png"),document.getElementById("deleteicon")&&(document.getElementById("deleteicon").src="images/vault/cancel.png"),document.getElementById("keyboardicon")&&(document.getElementById("keyboardicon").src="images/keyboard.png",document.getElementById("screenkeyboardcontainer").style.top="4px");
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){load()});window.addEventListener("unload",function(){"function"==typeof reprompt_error_callback&&reprompt_error_callback()});document.getElementById("f").onsubmit=function(){return!1};document.getElementById("u").onchange=function(){username_changed()};document.getElementById("deleteicon").addEventListener("click",function(){delete_user()});document.getElementById("p").onkeypress=function(a){return retsubmit(a)};
document.getElementById("rememberemail").addEventListener("click",function(){this.checked||(document.getElementById("rememberpassword").checked=!1)});document.getElementById("rememberpassword").addEventListener("click",function(){this.checked&&!confirm(gs("Are you sure you want to have LastPass remember your password?  This will significantly decrease the security of your LastPass account!"))&&(this.checked=!1);this.checked&&(document.getElementById("rememberemail").checked=!0)});document.getElementById("showvault").addEventListener("click",
function(){this.checked||(document.getElementById("showvault").checked=!1)});document.getElementById("donotrepromptforsecs").addEventListener("change",function(){document.getElementById("donotrepromptfor").checked=0<this.selectedIndex});document.getElementById("login").addEventListener("click",function(){do_submit()});document.getElementById("cancel").addEventListener("click",function(){setTimeout(function(){getBG().closecurrenttab("login.html")},0)});document.getElementById("forgot").onclick=function(){getBG().openURL(getBG().g_forgotpwurl);
return!1};document.getElementById("screenkeyboard").onclick=function(){getBG().openURL(base_url+"?sk=1");return!1};document.getElementById("createaccount").onclick=function(){getBG().openURL(getchromeurl("welcome.html"));return!1}});
