var reprompt_callback=null,reprompt_error_callback=null;g_fixpbkdf2=!0;
function do_submit(){var b=fix_username(document.getElementById("u").value),a=document.getElementById("p").value;document.getElementById("p").value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";var c=get_key_iterations(b);getBG().make_lp_key_hash_iterations(b,a,c,function(e,g){document.getElementById("p").blur();if(null!=reprompt_callback){var d=getBG();if(e!=d.g_local_key&&""!=checkNeedsPBKDF2v2(b,a)){var f="undefined"!=typeof g_oldpbkdf2?g_oldpbkdf2:null;
g_oldpbkdf2=1;e=make_lp_key_iterations(b,a,c);g_oldpbkdf2=f}e==d.g_local_key?(f=0,document.getElementById("donotrepromptfor").checked&&(f=document.getElementById("donotrepromptforsecs").value),d.lpPutUserPref("reprompttime",f),d.lpWriteAllPrefs(),d.set_last_reprompt_time(),reprompt_error_callback=null,d.select_selectedtabid(),reprompt_callback(),setTimeout(function(){window_close("login.html")},0)):(alert(gs("Invalid Password.")),setTimeout(function(){getBG().closecurrenttab("login.html")},0))}else(d=
getBG())?(d.g_manual_login=!0,d.LP_do_login(b,a,document.getElementById("rememberemail").checked,document.getElementById("rememberpassword").checked,null,document.getElementById("showvault").checked,e,g),reprompt_error_callback=null,a="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",setTimeout(function(){getBG().closecurrenttab("login.html")},0)):alert(gs("Can't find hidden LastPass window"))});return!1}var passwords=[];
function load(b){try{if(!b&&("undefined"==typeof safari||"undefined"==typeof safari.extension.globalPage))get_data("login",function(){load(!0)});else{getBG().LPISLOC&&(document.getElementById("forgotcontainer").style.display=document.getElementById("screenkeyboardcontainer").style.display=document.getElementById("createaccountcontainer").style.display="none");var a=getBG();can_chrome_do_math()||a.openURL(getchromeurl("mathfail.html"));if(null!=a.g_reprompt_callback){reprompt_callback=a.g_reprompt_callback;
a.g_reprompt_callback=null;reprompt_error_callback=a.g_reprompt_error_callback;a.g_reprompt_error_callback=null;document.getElementById("reprompttext").style.display="";document.getElementById("deleteicon").style.display="none";document.getElementById("rememberemailrow").style.display="none";document.getElementById("rememberpasswordrow").style.display="none";document.getElementById("showvaultrow").style.display="none";document.getElementById("donotrepromptforrow").style.display="";document.getElementById("screenkeyboardcontainer").style.display=
"none";document.getElementById("forgotcontainer").style.display="none";document.getElementById("u").value=a.g_username;document.getElementById("u").disabled=!0;var c=a.lpGetPref("reprompttime",0);document.getElementById("donotrepromptfor").checked=0<c;document.getElementById("donotrepromptforsecs").value=c;document.getElementById("p").focus();document.getElementById("links").style.display="none";getBG().can_allow_reprompt_skip()||(document.getElementById("donotrepromptfor").checked=!1,document.getElementById("donotrepromptfor").disabled=
!0,document.getElementById("donotrepromptforsecs").disabled=!0);document.getElementById("logintitletxt").innerHTML="";setTimeout(function(){document.getElementById("p").focus()},50)}else{var e=a.lpGetPref("rememberemail",1),g=a.lpGetPref("rememberpassword",-1),d=a.lpGetPref("showvault",-1);document.getElementById("rememberemail").checked=1==e?!0:!1;document.getElementById("rememberpassword").checked=1==g?!0:!1;document.getElementById("showvault").checked=1==d?!0:!1;getBG().g_hidecreate&&(document.getElementById("createaccountcontainer").style.display=
"none");if(getBG().g_hidevault||getBG().g_hideshowvault)document.getElementById("showvaultrow").style.display="none";getBG().g_hidescreenkeyboard&&(document.getElementById("screenkeyboardcontainer").style.display="none");document.getElementById("logintitletxt").innerHTML=gs("Sign In")}}}catch(f){console_log(f.message)}}
function populate_usernames(){getBG().get_saved_logins(function(b){for(var a=[],c=0;c<b.length;c++)a[c]=b[c].username,passwords[a[c]]=b[c].password,1==b[c]["protected"]?function(a,b){getBG().unprotect_data(b,!1,function(c){passwords[a]=c;document.getElementById("p").value==b&&(document.getElementById("p").value=c)})}(a[c],passwords[a[c]]):2==b[c]["protected"]&&(passwords[a[c]]=lpdec(passwords[a[c]],AES.hex2bin(SHA256(a[c]))));a.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});create_combo("u",
a,!0,document);a="";c=document.location.href.indexOf("sesameusername=");-1!=c&&(a=document.location.href.substr(c+15),c=a.indexOf("&"),-1!=c&&(a=a.substring(0,c)),a=decodeURIComponent(a));0<b.length||""!=a?(b=""!=a?a:b[0].username,a="undefined"!=typeof passwords[b]?passwords[b]:"",document.getElementById("u").value=b,document.getElementById("p").focus(),""!=a&&(document.getElementById("p").value=a,-1==rememberpassword&&(document.getElementById("rememberpassword").checked=!0),document.getElementById("login").focus())):
document.getElementById("u").focus();g_ischrome&&(-1!=navigator.userAgent.indexOf("Chrome/4")||-1!=navigator.userAgent.indexOf("Chrome/5"))&&setTimeout(function(){test_db_failed(1)},5E3)})}function test_db_failed(b){L("test_db_failed timeout: "+b);getBG().g_db_transaction_tested=!0;getBG().g_db_transaction_worked||(document.getElementById("u").focus(),create_combo("u",[],!0,document))}
function username_changed(){var b=document.getElementById("u").value;"undefined"!=typeof passwords[b]&&""!=passwords[b]?(document.getElementById("p").value=passwords[b],document.getElementById("rememberpassword").checked=!0):(document.getElementById("p").value="",document.getElementById("rememberpassword").checked=!1)}
function delete_user(){var b=document.getElementById("u").value;getBG().delete_saved_login(b);delete passwords[b];delete_combo_item("u",b);document.getElementById("u").value="";for(var a in passwords){document.getElementById("u").value=a;break}username_changed()}function retsubmit(b){return 13==b.keyCode?(do_submit(),!1):!0};
