function redraw_menu(){var f=getBG().lploggedin,c=false,d;for(d in getBG().g_sites)if(getBG().g_sites[d].fav=="1"&&getBG().check_ident_aid(d)){c=true;break}c=[{hidden:f,cmd:"getBG().lplogin()",icon:"images/power_off.png",title:getBG().gs("Login")},{hidden:f,title:'<select style="visibility: hidden;"></select>'},{hidden:!f,cmd:"getBG().lplogoff(false,'menu1')",icon:"images/power_off.png",title:getBG().gs("Logoff")},{hidden:!f||getBG().g_hidevault,cmd:"getBG().openvault()",icon:"images/icon_vault.png",
title:getBG().gs("My LastPass Vault")},{hidden:!f,menu:"sites",icon:"images/icon_sites.png",title:getBG().gs("Sites")},{hidden:!f||getBG().g_hideopenfavs||!c,cmd:"getBG().openfavorites()",icon:"images/icon_favorites.png",title:getBG().gs("Open Favorites")},{hidden:!f,menu:"fillforms",icon:"images/icon_formfill.png",title:getBG().gs("Fill Forms")},{hidden:!f,menu:"tools",icon:"images/icon_tools.png",title:getBG().gs("Tools")}];getBG().LPISLOC?c.push({hidden:!f,cmd:"getBG().upgradetoserver()",icon:"images/icon_premium.png",
title:getBG().gs("Upgrade to LastPass Online!")}):c.push({hidden:!f||getBG().g_hidegopremium||getBG().g_premium_exp>lp_get_local_timestamp()||getBG().g_enterpriseuser,cmd:"getBG().openpremium()",icon:"images/icon_premium.png",title:getBG().gs("Go Premium!")});c.push({hidden:!f,cmd:"getBG().saveall()",icon:"images/icon_saveall.png",title:getBG().gs("Save All Entered Data")});var g='<table cellspacing="0" cellpadding="0">';g+="<tr>";var k=true;for(d=0;d<c.length;d++)if(!c[d].hidden){if(!k&&f)g+='<td style="font-size: 16px;">&nbsp;&nbsp;|&nbsp;&nbsp;</td>';
k=false;var i="",j="";if(typeof c[d].cmd!="undefined"){i='<a href="javascript:'+c[d].cmd+';getBG().close_menu();">';j="</a>"}var e="";if(typeof c[d].menu!="undefined"){var a;switch(c[d].menu){case "sites":a=[];e=getBG().getmatchingsites();for(var b=0;b<e.length;b++){var h=e[b].name;if(e[b].username!="")h+=" ("+e[b].username+")";a.push({cmd:"getBG().fillaid("+e[b].aid+")",title:h})}break;case "fillforms":a=[{cmd:"getBG().addprofile()",title:getBG().gs("Add Profile")},{cmd:"getBG().addcreditcard()",
title:getBG().gs("Add Credit Card")},{cmd:"getBG().clearforms()",title:getBG().gs("Clear Forms")},{cmd:"getBG().openchooseprofilecc()",title:getBG().gs("Choose Profile and Credit Card")}];e=true;for(b=getBG().g_formfills.length-1;b>=0;b--)if(getBG().check_ident_ffid(getBG().g_formfills[b].ffid)){if(e){a.unshift({title:"----------"});e=false}a.unshift({cmd:"getBG().fillform("+getBG().g_formfills[b].ffid+")",title:of(getBG().g_formfills[b].decprofilename)})}break;case "tools":a=[{cmd:"getBG().opengenpw()",
title:getBG().gs("Generate Secure Password")},{cmd:"getBG().openprefs()",title:getBG().gs("Preferences")}];getBG().g_hidesearch||a.push({cmd:"getBG().opensearch()",title:getBG().gs("Site Search")});getBG().g_hiderecheckpage||a.push({cmd:"getBG().recheckpage()",title:getBG().gs("Recheck Page")});if(!getBG().LPISLOC){a.push({cmd:"getBG().refreshsites()",title:getBG().gs("Refresh Sites")});getBG().g_hideimport||a.push({cmd:"getBG().openimport()",title:getBG().gs("Import")})}getBG().g_hideexport||a.push({cmd:"getBG().doexportchoose()",
title:getBG().gs("Export")});if(!getBG().LPISLOC&&!getBG().g_hideprint){a.push({cmd:"getBG().openprint(false)",title:getBG().gs("Print Sites")});getBG().g_hidenotes||a.push({cmd:"getBG().openprint(true)",title:getBG().gs("Print Secure Notes")})}getBG().g_hidecheckupdates||a.push({cmd:"getBG().checkforupdates()",title:getBG().gs("Check For Updates")});if(!getBG().LPISLOC){a.push({cmd:"getBG().clearCache(false)",title:getBG().gs("Clear Local Cache")});getBG().g_hideseccheck||a.push({cmd:"getBG().openseccheck()",
title:getBG().gs("Security Check")});getBG().g_hidesessions||a.push({cmd:"getBG().opensessions()",title:getBG().gs("Other Sessions")})}a.push({cmd:"getBG().openhelp()",title:getBG().gs("Help...")});getBG().g_hideabout||a.push({cmd:"getBG().openabout()",title:getBG().gs("About...")});a.push({title:"----------"});a.push({cmd:"getBG().openaddsite()",title:getBG().gs("Add Site")});getBG().g_hidenotes||a.push({cmd:"getBG().openaddsecurenote()",title:getBG().gs("Add Secure Note")})}e=': <select style="width: 75px;" onchange="eval(this.options[this.selectedIndex].value);"><option>'+
getBG().gs("Select")+"</option>";for(b=0;b<a.length;b++){h="";if(typeof a[b].cmd!="undefined")h+=a[b].cmd+"; getBG().close_menu();";h+="this.selectedIndex = 0;";e+='<option value="'+h+'">'+a[b].title+"</option>"}e+="</select>"}b="";if(typeof c[d].icon!="undefined"){g+="<td>"+i+'<img border="0" src="'+getchromeurl(c[d].icon)+'">'+j+"</td>";b="&nbsp;"}g+="<td>"+i+b+c[d].title+j+e+"</td>"}g+="</tr>";g+="</table>";document.body.innerHTML=g}
typeof safari!="undefined"&&typeof safari.extension.globalPage!="undefined"&&safari.extension.globalPage&&getBG().drawIconAtRotation(0);
