var gLastLoginState=0,gAccts_version=-1,gCurr_username="",gTimerId=null,gIconsLength=0,gLastSearch="",gIdentity="",gSearchWhileType=!0,gTreeHeightOffset=147,gPollInterval=500,gHidePreferences=!1,gLocalBaseUrl="",g_hideprofilecopy=1,g_hideidentcopy=1,g_localvault=1,g_showrows=1,g_autoselectcredmontab=0,g_CNTsearch_it=0,g_CNTsearch_string_tokenize=0,g_CNTinit_vault=0,g_CNTpopulate=0,g_CNTsearch_tree=0,g_CNTclear_tree=0,event_handlers={},event_handlers_onmouseover={},event_handlers_onmouseout={},event_handlers_onclick=
{};function fix_group(a){a==gs("(none)")&&(a="");return a}
function onLoad(a,b){try{if("undefined"!=typeof g_is_safari&&"undefined"==typeof LPFromWebsite)50>a?(a++,setTimeout(function(){onLoad(a)},25)):document.location.href=document.location.href;else if("undefined"==typeof g_is_safari&&!b)get_data("vault",function(){onLoad(a,!0)});else if("function"!=typeof getBG||"undefined"==typeof getBG()||null==getBG())setTimeout(function(){onLoad()},50);else{g_urlprefix=getBG().base_url;var c=document.createElement("base");c.href=g_urlprefix;document.head.appendChild(c);
0<document.location.href.lastIndexOf("/")&&(gLocalBaseUrl=document.location.href.substr(0,document.location.href.lastIndexOf("/")+1));getBG().LPISLOC&&(document.getElementById("accountsettingscontainer").style.display="none");getBG().g_hideidentities&&(document.getElementById("identitycontainer").style.display="none");getBG().g_hideseccheck&&(document.getElementById("seccheckcontainer").style.display="none");sr(document,"submit","value",isSafariNative()?"Search":"Searchproper");document.getElementById("q").setAttribute("placeholder",
gs("Search Vault"));document.getElementById("lpusername").innerHTML="<b><a href='' id='lpusernamelink'>"+gs("Login")+"</a></b>";document.getElementById("lpusernamelink").onclick=function(){return login()};onResize();inittabs();setusernametext(getBG().g_username);0<document.location.href.indexOf("cmd=video")&&ontabchange(document.getElementById("video"));gTimerId=setInterval(function(){checkLoggedInHome()},gPollInterval);var f=getcolvisibility("usernamecol"),g=getcolvisibility("ltnamecol");document.getElementById("usercol").className=
f?"usercolvisible":"usercolhidden";document.getElementById("ltcol").className=g?"ltcolvisible":"ltcolhidden";document.getElementById("ltcol").style.paddingRight=f?"calc(5% + 20px)":"5%";create_combo("grpsel",[]);document.getElementById("grpsel_combo").style.height="150px";document.getElementById("grpsel_combo").style.overflow="auto";document.getElementById("q").focus();document.getElementById("ident").style.display=getBG().g_hideidentities?"none":"table-cell";document.getElementById("shares").style.display=
getBG().g_hidesharing?"none":"table-cell";document.getElementById("addsecurenote").style.display=getBG().g_hidenotes?"none":"block";document.getElementById("import").style.display=getBG().g_hideimport?"none":"block";document.getElementById("export").style.display=getBG().g_hideexport?"none":"block"}}catch(h){alert("homelocal2 onLoad:"+h)}}function onUnLoad(){gTimerId&&(clearInterval(gTimerId),gTimerId=null);saveGroupState()}
function onResize(){for(var a=0;a<tabnames.length;a++)document.getElementById(tabnames[a])&&(document.getElementById(tabnames[a]).style.height=document.body.clientHeight-gTreeHeightOffset+20+"px");document.getElementById("thetree")&&(document.getElementById("thetree").style.height=document.body.clientHeight-gTreeHeightOffset-14+"px")}
function checkLoggedInHome(a){try{var b=getBG(),c=b.lploggedin;if(isSafariNative())LPFromWebsite.lpupdateState(b.g_username,c,b.g_local_accts_version,b.g_identity,b.g_isadmin);else if(("undefined"!=typeof g_issafari&&g_issafari||"undefined"!=typeof g_isopera&&g_isopera||"undefined"!=typeof g_ismaxthon&&g_ismaxthon)&&!a){b.update_state("vault");return}a="";c&&(a=b.g_username);if(c!=gLastLoginState||a!=gCurr_username)if(c)window_load_loggedin(a);else{try{var f={"static":"{}"};$(function(){$("#thetree").tree({data:{type:"json",
opts:f}})})}catch(g){}finish_vault_search();g_lastnodeid=g_rootnodeid=null;window_load_loggedoff();update_identity_popup()}gLastLoginState=c;g_username=lpusername=gCurr_username=a;if(gLastLoginState){var h=b.g_local_accts_version;if(h>gAccts_version||b.IsIconsUpdated(gIconsLength)||b.g_identity!=gIdentity)finish_vault_search(),gAccts_version=h,populateNewData(gLastSearch),populateff(gLastSearch),populateident(gLastSearch),update_identity_popup(),setusernametext(a),showads()}}catch(l){alert("checkLoggedInHome:"+
l)}}function setusernametext(a){var b=getBG();if(b.lploggedin){var c="",f;for(f in b.g_identities)if(b.g_identities.hasOwnProperty(f)&&b.g_identity==b.g_identities[f].iid){c=b.g_identities[f].deciname;break}""==c?document.getElementById("lpusername").innerText=of(a):document.getElementById("lpusername").innerText=of(a+" ("+c+")")}else document.getElementById("lpusername").innerText=gs("Login")}
function window_load_loggedin(a){document.getElementById("identity").disabled=0;document.getElementById("enterpriseaction").style.display=getBG().g_iscompanyadmin?"":"none";document.getElementById("enterprise").style.display="1"==getBG().g_enterpriseuser?"none":"";document.getElementById("addsharedfolder").style.display="";document.getElementById("credmon").style.display="1"==getBG().g_showcredmon?"":"none";"1"==getBG().g_enterpriseuser&&(document.getElementById("linkpersonal").style.display=""==
get_personal_linked()?"":"none",document.getElementById("removepersonal").style.display=""!=get_personal_linked()?"":"none");setusernametext(a);getBG().get_securityChallengeScore(function(a){a&&(document.getElementById("securitycheckscore").style.color=getscorecolor(a),document.getElementById("securitycheckscore").innerHTML=" ("+getscoretxt(a)+")")});g_local_key=getBG().g_local_key;g_key_iterations=getBG().get_key_iterations(a)}
function showads(){getBG().lploggedin&&getBG().g_premium_exp<lp_get_local_timestamp()&&"1"!=getBG().g_enterpriseuser?("none"==document.getElementById("adframe").style.display&&(document.getElementById("adframe").style.display="block",document.getElementById("rightside").style.display="block",document.getElementById("adframe").setAttribute("src",g_urlprefix+"ads.php?nobr=1&noga=1&rand="+Math.floor(1E3*Math.random()))),document.getElementById("friend").style.display="block"):(document.getElementById("adframe").style.display=
"none",document.getElementById("rightside").style.display="none",document.getElementById("friend").style.display="none")}
function window_load_loggedoff(){gAccts_version=-1;gIconsLength=0;g_local_key=null;document.getElementById("lpusername").innerHTML="<b><a href='' id='lpusernamelink'>"+gs("Login")+"</a></b>";document.getElementById("lpusernamelink").onclick=function(){return login()};document.getElementById("credmon").style.display="none";document.getElementById("adframe").style.display="none";document.getElementById("rightside").style.display="none";document.getElementById("friend").style.display="none";document.getElementById("enterpriseaction").style.display=
"none";document.getElementById("enterprise").style.display="";document.getElementById("addsharedfolder").style.display="none";document.getElementById("linkpersonal").style.display="none";document.getElementById("removepersonal").style.display="none";for(var a=0;a<tabnames.length;a++)"treepane"!=tabnames[a]&&cleartab(tabnames[a]);setusernametext(getBG().g_username);document.getElementById("securitycheckscore").innerHTML=""}
function populateNewData(a){if(isSafariNative())LPFromWebsite.lpgetaccts();else{var b=!1,c;for(c in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(c)){b=!0;break}if(!b)for(c in getBG().g_securenotes)if(getBG().g_securenotes.hasOwnProperty(c)){b=!0;break}var f=!1;for(c in getBG().g_pendings)if(getBG().g_pendings.hasOwnProperty(c)){f=!0;break}!b&&!f?document.getElementById("sitesiframe")||(b=document.getElementById("treepane"),a=document.createElement("iframe"),a.id="sitesiframe",a.className="overviewiframe",
a.src="sites_overview.php",b.appendChild(a),document.getElementById("thetree").style.display="none"):(document.getElementById("sitesiframe")&&(b=document.getElementById("treepane"),b.removeChild(document.getElementById("sitesiframe")),document.getElementById("thetree").style.display=""),populate(a,!0),SearchTree(0,!0))}}function isSafariNative(){return"undefined"!=typeof LPFromWebsite&&("undefined"==typeof g_issafari||!g_issafari)}
function showhide(a,b){document.getElementById(a).style.display=b?"":"none"}
function update_identity_popup(){for(var a=getBG(),b=document.getElementById("identity");b.length;)b.remove(0);var c=document.createElement("option");c.text=gs("All");c.value="";""==a.g_identity&&(c.selected=1);b.appendChild(c);var f=0,g;for(g in a.g_identities)a.g_identities.hasOwnProperty(g)&&(c=document.createElement("option"),c.text=a.g_identities[g].deciname,c.value=a.g_identities[g].iid,a.g_identity==a.g_identities[g].iid&&(c.selected=1),b.appendChild(c),f++);0<f&&!getBG().g_hideidentities?
document.getElementById("identitycontainer").style.display="":document.getElementById("identitycontainer").style.display="none";document.getElementById("identitylabel").innerHTML=gs("Identity")}
function search_matches(a,b){var c=getBG().get_searchNotesPref();g_CNTsearch_matches++;var f=getBG().g_sites[a];if("undefined"==typeof f&&(f=getBG().g_securenotes[a],"undefined"==typeof f&&(0==a.indexOf("app")&&(a=a.substring(3)),f=getBG().g_applications[a],"undefined"==typeof f&&(f=getBG().g_pendings[a],"undefined"==typeof f)))){var g=getgroupnamefromid(a);if(g)for(var h in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(h)&&"undefined"!=typeof getBG().g_sites[h]&&"http://group"==getBG().g_sites[h].url&&
getBG().g_sites[h].group==g){f=getBG().g_sites[h];break}if("undefined"==typeof f)return!1}return matches(f,b,c)}var g_all_li=[],g_search_array={};function init_vault_search(){g_all_li=$("#thetree").find("li");g_CNTinit_vault++;var a=getBG().get_searchNotesPref();g_search_array=sites_tokenize(g_all_li,a)}function finish_vault_search(){lastqstr=g_search_array=g_all_li=null}
function sites_tokenize(a,b){for(var c={},f=0;f<a.length;f++){var g=a[f].id,h="id"+g,l="",k=getBG().g_sites[g];if("undefined"==typeof k&&(k=getBG().g_securenotes[g],"undefined"==typeof k&&(0==g.indexOf("app")&&(g=g.substring(3)),k=getBG().g_applications[g],"undefined"==typeof k&&(k=getBG().g_pendings[g],"undefined"==typeof k))))if(g=getgroupnamefromid(g))l=g;else if("undefined"==typeof k)continue;if(l)k=l.toLowerCase(),c[h]=k;else if("undefined"!=typeof k){l=[];l.push(k.name);l.push(k.group);"http://group"!=
k.url&&"http://sn"!=k.url&&l.push(k.url);k.unencryptedUsername&&l.push(k.unencryptedUsername);is_application(k)&&(l.push(k.appname),l.push(getusernamefromacct(k)));if(b&&"undefined"!=typeof k.extra&&0<k.extra.length&&("undefined"==typeof k.url||"http://group"!=k.url))k=getBG().lpmdec_acct(k.extra,!0,k,getBG().g_shares),l.push(k);k=l.join(" ");k=k.toLowerCase();c[h]=k}}return c}
function search_string_tokenize(a){var b=[];g_CNTsearch_string_tokenize++;if(!a)return b;if(-1==a.indexOf('"'))b=a.split(/\s+/);else{var c=[],c=a.split('"');for(a=0;a<c.length;a++)if(a%2)b.push(c[a]);else for(var f=[],f=c[a].split(/\s+/),g=0;g<f.length;g++)f[g]=f[g].replace(/^\s+/,""),f[g]=f[g].replace(/\s+$/,""),0<f[g].length&&b.push(f[g])}return b}
function search_it(a,b){g_CNTsearch_it++;for(var c="id"+a,f=1,g=0;g<b.length;g++)if(!(g_search_array[c]&&-1!=g_search_array[c].indexOf(b[g]))){f=0;break}return f}var populate_done=!1;
function populate(a,b){try{var c=getBG();g_CNTpopulate++;c.get_searchNotesPref();var f=$("#q").val(),g=0;a!=f&&($("#q").val(a),f=a,g=0);gLastSearch=a;gIconsLength=c.g_icons_length;gIdentity=c.g_identity;var f=[],h=[],l=[],k=[],m=[],j=0,v=[c.g_sites,c.g_securenotes],w;for(w in v)if(v.hasOwnProperty(w)){var x=v[w],t;for(t in x)if(x.hasOwnProperty(t)&&(j++,c.check_ident_aid(t))){for(var n=x[t],q=""!=n.group?n.group:"http://sn"==n.url?gs("Secure Notes"):gs("(none)"),q="_"+q;"\\"==q[0];)q=q.substr(1);
"undefined"==typeof f[q]&&(f[q]=[],h[h.length]=q,l[q]="undefined"==typeof n.aid?null:n.aid);f[q][f[q].length]=n;m[m.length]=n;"1"==n.fav&&(k[k.length]=n)}}for(t in c.g_applications)c.g_applications.hasOwnProperty(t)&&c.check_ident_appaid(t)&&(n=c.g_applications[t],q=""!=n.group?n.group:gs("(none)"),q="_"+q,"undefined"==typeof f[q]&&(f[q]=[],h[h.length]=q,l[q]="undefined"==typeof n.aid?null:n.aid),f[q][f[q].length]=n,m[m.length]=n,"1"==n.fav&&(k[k.length]=n));var v=0,p;for(p in c.g_pendings)c.g_pendings.hasOwnProperty(p)&&
(++v,n=c.g_pendings[p],""==a&&(q=gs("(New Pending Share Offers)"),"undefined"==typeof f[q]&&(f[q]=[],h[h.length]=q,l[q]=null),f[q][f[q].length]=n));var C=h.length;h.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});m.sort(function(a,b){return a.last_touch>b.last_touch?1:-1});var n=[],z=c.getClearRecentTime(),y=c.getRecentCount();if(""==a)for(p=0;n.length<y&&p<m.length;p++)"http://group"!=m[m.length-p-1].url&&(m[m.length-p-1].last_touch<z||(n[n.length]=m[m.length-p-1]));if(n.length){var m=
isSafariNative()?"recently used":"recently usedlower",r=gs(m);h.unshift(r);f[r]=n}k.length&&(h.unshift(gs("favorites")),f[gs("favorites")]=k);z=[];""==a&&(z=getOpenedGroups());var u=[],y=[];resetgroupnames();event_handlers={};event_handlers_onmouseover={};event_handlers_onmouseout={};event_handlers_onclick={};for(p=0;p<h.length;p++){r=!1;if(""!=a||"undefined"!=typeof z[h[p]]||1==C&&p==h.length-1)r=!0;var D="undefined"==typeof l[h[p]]?null:l[h[p]];"undefined"!=typeof h[p]&&addGroup(c,f,u,y,h[p],r,
!1,z,D)}$(function(){var a={};a["static"]=u;var b={beforedelete:lpbeforedelete,beforemove:lpbeforemove,onmove:lponmove,check_move:lpcheck_move,onselect:lponselect};populate_done||(b.onrgtclk=lponrgtclk);$("#thetree").tree({callback:b,data:{type:"json",opts:a},rules:{multiple:"ctrl",drag_copy:!1,use_max_children:!1,use_max_depth:!1},plugins:{hotkeys:{functions:{"return":function(){var a=$.tree.focused().selected;a&&(1==a.length&&(isNumber(a[0].id)||is_application(a[0].id)))&&ls(a[0].id)}}}}})})}catch(A){if("undefined"==
typeof LPFromWebsite||"function"!=typeof LPFromWebsite.ipad){if(0<=A.message.indexOf("atob")&&-1==document.location.href.indexOf("retry")){document.location.href+="?retry=1";return}alert("populate_error:"+A)}}update_identity_popup();init_vault_search();populate_done=!0;a&&""!=a&&SearchTree(g,b);for(p in event_handlers)document.getElementById(p)&&(document.getElementById(p).onclick=event_handlers[p]);for(p in event_handlers_onmouseover){c=document.getElementsByName(p);for(g=0;g<c.length;g++)c[g].onmouseover=
event_handlers_onmouseover[p]}for(p in event_handlers_onmouseout){c=document.getElementsByName(p);for(g=0;g<c.length;g++)c[g].onmouseout=event_handlers_onmouseout[p]}for(p in event_handlers_onclick){c=document.getElementsByName(p);for(g=0;g<c.length;g++)c[g].onclick=event_handlers_onclick[p]}}
function lpbeforedelete(a){var b=getBG();if(1<($.tree.focused().selected_arr&&$.tree.focused().selected_arr.length)){for(var c="",f=[],g=0;g<$.tree.focused().selected_arr.length;g++){var h=getmoveid($.tree.focused().selected_arr[g]);h&&""!=h&&(c+=(""!=c?",":"")+h,f[f.length]=$.tree.focused().selected_arr[g])}b.deleteAid(c,window,!1,!1,function(){for(var a=0;a<f.length;a++)$.tree.focused().cut(f[a])});return!1}c=!1;is_application(a.id)||isNumber(a.id)?c=b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)}):
(c=getgroupnamefromid(a.id),c=b.deleteGroup(fix_group(c),window,function(){$.tree.focused().cut(a)}));return c}
function lpbeforemove(a,b){getBG().lpevent("v_dnd");for(var c="",f=b,c=0;f&&""==f.attr("id")&&100>c;)f=f.parent(),c++;if(99<c||!f)return!1;var g=f.attr("id");g.match(/launch_(nor|fav|rec)_\d+/)&&(g=g.substr(11));g.match(/accept2_(nor|fav|rec)_\d+/)&&(g=g.substr(12));var c="",h=getBG();if(is_application(g)||isNumber(g)){is_application(g)?(h=[h.g_applications],g=get_appaid(g)):h=[h.g_sites,h.g_securenotes];for(var l in h)if(h.hasOwnProperty(l)){var k=h[l],m;for(m in k)if(k.hasOwnProperty(m)){var j=
k[m];if(j.aid==g){if("1"==j.fav){k=f.parent();for(c=0;k&&""==k.attr("id")&&100>c;)k=k.parent(),c++;if(99>c&&k&&k.attr("id")==gs("favorites")){c=gs("favorites");break}}c=j.group;break}}}}else c=getgroupnamefromid(g);f=isSafariNative()?"recently used":"recently usedlower";f=gs(f);if(!(""==c||c==f||c==gs("(New Pending Share Offers)"))){f=$.tree.focused().selected_arr;l="";for(m=0;m<f.length;m++)if(is_application(getmoveid(f[m]))||isNumber(getmoveid(f[m])))l+=(""==l?"":",")+getmoveid(f[m]);0==l.length&&
(l=a.attr("id"));0!=l.length&&getBG().moveSelectedToGroup(c,l);return!1}}function lponmove(){}function lpcheck_move(a){return 1<$.tree.focused().selected_arr.length?!0:a&&""!=a.attr("id")&&!is_application(a.attr("id"))&&!isNumber(a.attr("id"))?!1:!0}function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}var g_groups={},g_groupindex=2E5,g_groupid={},g_groupnames={};
function getgroupnamefromid(a,b){if("undefined"==typeof g_groups[a])return a;var c=g_groups[a];!b&&0==c.indexOf("_")&&(c=c.substring(1));return c}function getrawgroupid(a){return"undefined"==typeof g_groupid[a]||null==g_groupid[a]?null:g_groupid[a]}function resetgroupnames(){g_groups={};g_groupindex=2E5;g_groupid={};g_groupnames={}}function getgroupid(a,b){var c="LpGrOuP"+g_groupindex;g_groups[c]=a;g_groupnames[a]=c;g_groupid[c]=b;++g_groupindex;return"LpGrOuP"+(g_groupindex-1)}
function getgroupidfromname(a){return"undefined"==typeof g_groupnames[a]||null==g_groupnames[a]?null:g_groupnames[a]}var g_rootnodeid=null,g_lastnodeid=null;
function addGroup(a,b,c,f,g,h,l,k,m){for(;"\\"==g[0];)g=g.substr(1);for(var j=g.match(/^([^\\]*)\\(.*)$/),v=null!=j,w="",x=0;j&&!l;){var t=j[1],n=j[2],w=w+((""!=w?"\\":"")+t);"undefined"==typeof f[w]&&addGroup(a,b,c,f,w,h||"undefined"!=typeof k[w],!0,k,m);x++;j=n.match(/^([^\\]*)\\(.*)$/)}w=(""==w?"":"\\")+g;l=[];h=h?"open":"closed";t=b[g];"undefined"==typeof t&&(t=[]);j=isSafariNative()?"recently used":"recently usedlower";j=gs(j);b="nor_";g!=j&&g!=gs("(New Pending Share Offers)")?(t.sort(a.lp_sort_case_insensitive_name),
g==gs("favorites")&&(b="fav_")):(t.sort(function(a,b){return a.last_touch>b.last_touch?-1:1}),g==j&&(b="rec_"));k=getcolvisibility("usernamecol");for(var q=getcolvisibility("ltnamecol"),p=navigator.userAgent.match("Gecko/"),C=1==g_showrows?"":"none",z=0;z<t.length;z++){var y=45+15*x;if(p||"undefined"!=typeof g_isopera&&g_isopera)y+=20;var r=t[z];if("http://group"!=r.url){var u=j="";if("undefined"!=typeof r.sharerusername)"undefined"!=typeof g_isopera&&g_isopera&&(j+="</a>"),j+="<div class='actionmenu' style='padding-right: "+
y+"px;display:"+C+";'><a href='#' id='accept_"+b+r.id+"' style='text-decoration: underline; color: #00C'><img src='"+gLocalBaseUrl+"images/vaultaccept.png'/></a> | <a href='#' id='reject_"+b+r.id+"' style='text-decoration: underline; color: #00C'><img src='"+gLocalBaseUrl+"images/vaultreject.png'/></a></div>",event_handlers["accept_"+b+r.id]=function(){return accept(this.id.substring(11))},event_handlers["reject_"+b+r.id]=function(){return reject(this.id.substring(11))},j+="<span style='clear:both'></span>",
j+="<span><a href='#' id='accept2_"+b+r.id+"'>"+gs("Share offer from")+" "+of(a.hex2bin(r.sharerusername))+"</a></span>",event_handlers["accept2_"+b+r.id]=function(){return accept(this.id.substring(12))};else{var D=safclassdel=safclassshare="";if(g_issafari||g_isopera)D=" editsaf",safclassdel=" delsaf",safclassshare=" sharesaf";var u=get_record_id(r),A,B="<a href='#' id='share_"+b+u+"' style='text-decoration: underline; color: #00C' title='"+gs("Share")+"'><span class='shareimg"+safclassshare+"'></span></a> ";
event_handlers["share_"+b+u]=function(){return s(this.id.substring(10))};!a.LPISLOC&&!r.genpw&&("undefined"==typeof r.sharedfromaid||null==r.sharedfromaid||""==r.sharedfromaid||"0"==r.sharedfromaid||"null"==r.sharedfromaid)&&"undefined"==typeof r.sharefolderid&&!is_application(r)&&!1==a.g_hidesharing?A="":(A='<font style="visibility: hidden;display:inline;">'+B+"</font>",B="");"undefined"!=typeof g_isopera&&g_isopera&&(j+="</a>");j+="<div class='actionmenu' style='padding-right: "+y+"px; display:"+
C+";'>"+A;j+="<a href='#' id='edit_"+b+u+"' style='text-decoration: underline; color: #00C' title='"+gs("Edit")+"'><span class='editimg"+D+"'></span></a> ";event_handlers["edit_"+b+u]=function(){return e(this.id.substring(9))};j+=B;j+="<a href='#' id='delete_"+b+u+"' style='text-decoration: underline; color: #00C' title='"+gs("Delete")+"'><span class='delimg"+safclassdel+"'></span></a></div>";event_handlers["delete_"+b+u]=function(){return d(this.id.substring(11))};j+="<span style='clear:both'></span>";
j+="<span><a href='#' id='launch_"+b+u+"'>"+of(r.name)+"</a></span>";event_handlers["launch_"+b+u]=function(){return ls(this.id.substring(11))}}y="calc(5% + 10px)";D=k?"usercolvisible":"usercolhidden";A=q?"ltcolvisible":"ltcolhidden";B=of(a.getusernamefromacct(r));""==B&&(B="&nbsp;");j+="<div style='float: right; padding-right: "+y+";display:"+C+";' class='"+D+"' name='usercol'>"+B+"</div>";j+="<div style='float: right; padding-right: "+y+";display:"+C+";' class='"+A+"' name='ltcol'>"+("undefined"!=
typeof r.last_touch?of(elapsedTime(r.last_touch)):"")+"</div>";l[l.length]={data:{title:j,icon:a.geticonurlfromrecord(r)},attributes:{id:u,name:u}};event_handlers_onmouseover[u]=function(){sv(event,this);return!1};event_handlers_onmouseout[u]=function(){hv(event,this);return!1};event_handlers_onclick[u]=function(){lc(event,this);return!1}}}a="";isSafariNative()&&"function"==typeof LPFromWebsite.ipad&&(a="onclick='$.tree.focused().toggle_branch(this)'");x=g;0==x.indexOf("_")&&(x=x.substring(1));j=
"<span style='font-weight:bold' isgroup='1' "+a+">"+of(x)+"</span>";f[g]=c.length;if(v){j=g.match(/^([^\\]*)\\(.*)$/);f=null;for(v=w=0;j;){t=j[1];n=j[2];if(0==w){for(a=c.length-1;0<=a;a--)if(c[a].group==t){f=c[a].children;break}v=0;w=1;if(!n.match(/^([^\\]*)\\(.*)$/))for(a=0;a<f.length;a++)if("undefined"==typeof f[a].group||f[a].group==t){v=a;break}}else{for(a=x=0;a<f.length;a++)if("undefined"==typeof f[a].group){x=a-1;break}else if(f[a].group==t){x=a;break}f=f[x].children}j=n.match(/^([^\\]*)\\(.*)$/);
if(!j)for(a=0;a<f.length;a++)if("undefined"==typeof f[a].group||f[a].group==t){v=a;break}else if(a==f.length-1){v=a+1;break}}j="<span style='font-weight:bold' isgroup='1'>"+of(n)+"</span>";f.splice(v,0,{data:j,children:l,state:h,group:n,attributes:{"class":"folder",id:getgroupid(g,m)}})}else 0==c.length&&(g_rootnodeid=g),g_lastnodeid=g,c[c.length]={data:j,children:l,state:h,group:g,attributes:{"class":"folder",id:getgroupid(w,m)}}}
function getcolvisibility(a){return 0==localStorage.getItem(a)?!1:!0}function setcolvisibility(a,b){localStorage.setItem(a,b)}
function matches(a,b,c){var f=b.toLowerCase();g_CNTmatches++;if(-1!=a.name.toLowerCase().indexOf(f)||(a.url&&-1!=a.url.toLowerCase().indexOf(f)||-1!=a.group.toLowerCase().indexOf(f)||a.unencryptedUsername&&-1!=a.unencryptedUsername.toLowerCase().indexOf(f))||is_application(a)&&(a.appname&&-1!=a.appname.toLowerCase().indexOf(f)||-1!=getusernamefromacct(a).toLowerCase().indexOf(f)))return!0;if(c&&"undefined"!=typeof a.extra&&0<a.extra.length&&("undefined"==typeof a.url||"http://group"!=a.url))if(c=
getBG().lpmdec_acct(a.extra,!0,a,getBG().g_shares),g_CNTmatches_decrypt++,-1!=c.toLowerCase().indexOf(f))return!0;return"has:attachment"==b&&"undefined"!=typeof a.attachid&&null!=a.attachid&&0!=a.attachid?!0:!1}
function getOpenedGroups(){var a=getBG(),b=[],c="";if("undefined"==typeof LPFromWebsite){if("undefined"==typeof localStorage)return b;c=localStorage.getItem(a.db_prepend(a.g_username_hash+".savedtree"));c=a.dec(c)}else c=LPFromWebsite.readopengroups();if(!c||""==c)return b;a=c.split(",");for(c=0;c<a.length;c++)b[a[c].replace("%2C",",")]=1;return b}
function saveGroupState(){var a=getBG();if(!massoperation&&a.lploggedin){var b="",c=$("#thetree").find(".open");$.each(c,function(a,c){var h=getgroupnamefromid(c.id,!0);h.replace(",","%2C");b+=h+","});"undefined"==typeof LPFromWebsite?"undefined"!=typeof localStorage&&(c=a.enc(b),localStorage.setItem(a.db_prepend(a.g_username_hash+".savedtree"),c)):LPFromWebsite.saveopengroups(b)}}function lc(a,b){$.tree.focused().select_branch(b,a.ctrlKey|a.metaKey,a.shiftKey)}
function sv(a,b){if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="inline-block")}function hv(a,b){if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="none")}function lponopen(){saveGroupState()}function lponclose(){saveGroupState()}function lponselect(){document.getElementById("q").blur()}var g_lastpop=0;
function lponrgtclk(a,b,c){var f=$.tree.focused().selected_arr&&$.tree.focused().selected_arr.length;getBG().lpevent("v_rgt");var g=(new Date).getTime();if(!(g_lastpop>g-500)){g_lastpop=g;if(1<f){for(var h="",l=[],k=!1,m=!1,f=0;f<$.tree.focused().selected_arr.length;f++)if((g=getmoveid($.tree.focused().selected_arr[f]))&&""!=g)is_application(g)&&(k=!0),get_record(g)&&"undefined"!=typeof get_record(g).sharefolderid&&(m=!0),h+=(""!=h?",":"")+g,l[l.length]=$.tree.focused().selected_arr[f];setTimeout(function(){$.contextMenu.create(function(){var b=
getBG(),c={};c[gs("Move Selected to Group")]=function(){b.lpevent("v_multmov");openMoveGroup(a)};!k&&!m&&(c[gs("Share Selected")]=function(){b.lpevent("v_mults");s(h)});c[gs("Delete Selected")]=function(){b.lpevent("v_multd");b.deleteAid(h,window,!1,!1,function(){for(var a=0;a<l.length;a++)$.tree.focused().cut(l[a])})};return[c]},{theme:"vista"}).show(b,c)},100)}else if("undefined"!=typeof a)if(""!=a.id&&!is_application(a.id)&&!isNumber(a.id)){var j=getgroupnamefromid(a.id);0==j.indexOf("_")&&(j=
j.substring(1));f=!1;for(g=a;g.parentNode&&g.parentNode!=g;)if(g=g.parentNode,"thetree"==g.id){f=!0;break}if(!f)return;var v=getrawgroupid(a.id);setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={},f=isSafariNative()?"recently used":"recently usedlower",f=gs(f);j!=gs("favorites")&&(j!=f&&j!=gs("(New Pending Share Offers)"))&&(c[gs("Rename Group")]=function(){b.lpevent("v_ren");openMoveGroup(a)},c[gs("Delete Group")]=function(){b.lpevent("v_dg");b.deleteGroup(fix_group(j),window,
function(){$.tree.focused().cut(a)},"homelocal2.html B",0,v)},c[gs("Create Sub-Group")]=function(){b.lpevent("v_csub");openCreateGroup(a)});c[gs("Open All")]=function(){b.openall(j)};return[c]},{theme:"vista"}).show(b,c)},0);c.preventDefault()}else""!=a.id&&(is_application(a.id)||isNumber(a.id))&&setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={};if("undefined"!=typeof getBG().g_sites[a.id]||is_application(a.id)){if("undefined"==typeof g_issafari&&"undefined"==typeof g_isopera&&
"undefined"==typeof g_ismaxthon||"function"==typeof b.can_copy_to_clipboard&&b.can_copy_to_clipboard()||"undefined"!=typeof g_is_safari)c[gs("Copy Username")]=function(){b.copyusername(a.id)},c[gs("Copy Password")]=function(){b.copypassword(a.id)},c[gs("Copy URL")]=function(){b.copyurl(a.id)}}else if("undefined"!=typeof getBG().g_securenotes[a.id]){var f=getBG().g_securenotes[a.id],f="undefined"!=typeof f.notetype?f.notetype:"";if("Server"==f||"Email Account"==f||"Database"==f)c[gs("Copy Username")]=
function(){b.copyusername(a.id)},c[gs("Copy Password")]=function(){b.copypassword(a.id)}}c[gs("Move to Group")]=function(){b.lpevent("v_mov");openMoveGroup(a)};c[gs("Move to Sub-Group")]=function(){b.lpevent("v_msub");openMoveGroup(a,!0)};f=get_record(a.id);if(!is_application(a.id)&&get_record(a.id)&&"undefined"==typeof get_record(a.id).sharefolderid&&("undefined"==typeof f.sharedfromaid||null==f.sharedfromaid||""==f.sharedfromaid||"0"==f.sharedfromaid||"null"==f.sharedfromaid))c[gs("Share")]=function(){s(a.id)};
c[gs("Delete")]=function(){b.lpevent("v_rgtd");b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)})};c[gs("Edit")]=function(){b.lpevent("v_rgte");b.editAid(a.id,window)};"undefined"!=typeof getBG().g_sites[a.id]&&(c[gs("Go to URL")]=function(){b.lpevent("v_g2");b.gotourl(a.id,null)});return[c]},{theme:"vista"}).show(b,c)},100);c.preventDefault()}}var lastqstr="";
function SearchTree(a,b){g_CNTsearch_tree++;var c=!1;0<document.location.href.indexOf("cmd=viewcreditmon")&&1!=g_autoselectcredmontab?(ontabchange(document.getElementById("credmon")),g_autoselectcredmontab=1):"sites"!=g_activetab.id&&(c=!0);var f=$("#q").val(),g=!1;if(a||f!=lastqstr)c&&!b&&(ontabchange(document.getElementById("sites")),g=!0),gLastSearch=lastqstr=f,""==f?clearTree():$.tree.focused().search(f);c&&!g&&setTimeout(function(){ontabchange(g_activetab)},0);document.getElementById("searchxlink").style.visibility=
""==f?"hidden":"visible"}function ls(a){var b=getBG();b.lpevent("v_ls");b.launch(a);return!1}function cu(a){var b=getBG();b.lpevent("v_cu");b.copyusername(a);return!1}function cp(a){var b=getBG();b.lpevent("v_cp");b.copypassword(a);return!1}function curl(a){var b=getBG();b.lpevent("v_curl");b.copyurl(a);return!1}function e(a){var b=getBG();b.lpevent("v_e");b.editAid(a,window);return!1}function d(a){var b=getBG();b.lpevent("v_d");b.deleteAid(a,window);return!1}
function is_protected(a){"string"==typeof a&&(a=a.split(","));for(var b=0;b<a.length;b++){var c=get_record(a[b]);if(c&&1==c.pwprotect)return!0}return!1}function s(a){getBG().lpevent("v_s");callServerFunction("share",a);return!1}function MoveFocus(a){if(40==a.keyCode||34==a.keyCode||38==a.keyCode||33==a.keyCode)a=38==a.keyCode||33==a.keyCode?getgroupidfromname(g_lastnodeid):getgroupidfromname(g_rootnodeid),$.tree.focused().select_branch("#"+a),document.getElementById("q").blur()}
function clearTree(){g_CNTclear_tree++;populate("");document.getElementById("searchxlink").style.visibility="hidden";document.getElementById("q").value=""}var massoperation=!1;function expandall(){if(!getBG().lploggedin)return!1;massoperation=!0;$.tree.focused().open_all();massoperation=!1;saveGroupState()}function collapseall(){if(!getBG().lploggedin)return!1;massoperation=!0;$.tree.focused().close_all();massoperation=!1;saveGroupState()}
function creategroup(){var a=getBG();a.lploggedin&&(a.lpevent("v_cg"),openCreateGroup(null))}
function showformfill(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a=getBG(),b={},c;for(c in a.g_formfills)a.g_formfills.hasOwnProperty(c)&&a.check_ident_ffid(a.g_formfills[c].ffid)&&(b[of(a.g_formfills[c].decprofilename)]=function(a){editff(a.innerText)});a={};a[gs("Add Profile")]=function(){getBG().addprofile()};a[gs("Add Credit Card")]=function(){getBG().addcreditcard()};return[b,"context-menu-separator",a]},{theme:"vista"}).show(a,
b)},0);return!1}function editff(a){var b=getBG();a=$.trim(a);for(var c in b.g_formfills)if(b.g_formfills.hasOwnProperty(c)&&a==$.trim(b.g_formfills[c].decprofilename)){b.editprofile(b.g_formfills[c].ffid);break}}
function showmoremenu(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a={};gHidePreferences||(a[gs("Preferences")]=function(){getBG().openprefs()});getBG().LPISLOC||(a[gs("History")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&openhistory=1")},a[gs("Show Deleted Sites")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&showdeleted=1")});if(!getBG().LPISLOC||!getBG().LPISUPEK)a[gs("Change Password")]=
function(){getBG().unlock_plug2web();getBG().changemasterpassword()};a[gs("Forums")]=function(){getBG().openURL("http://forums.lastpass.com")};a[gs("Blog")]=function(){getBG().openURL("http://blog.lastpass.com")};getBG().g_isadmin&&(a[gs("Admin Tools")]=function(){getBG().openURL("https://rodan.lastpass.com/admintools/")});return[a]},{theme:"vista"}).show(a,b)},0);return!1}function addsecurenote(){getBG().lpevent("v_addn");getBG().openaddsecurenote();return!1}
function logoff(){if(!getBG().lploggedin)return!1;finish_vault_search();getBG().lpevent("v_off");saveGroupState();getBG().loggedOut(!1,"homelocal2");return!1}function accept(a){getBG().lpevent("v_apt");callServerFunction("acceptshare",a)}function reject(a){getBG().lpevent("v_rjt");callServerFunction("rejectshare",a)}function login(){getBG().lpevent("v_lgn");getBG().open_login(!0);return!1}
function changeidentity(a,b){("undefined"==typeof b||!0==b)&&closepopup();getBG();getBG().lpevent("v_cid");getBG().switch_identity(a);document.getElementById("identity").value=getBG().g_identity;setusernametext(getBG().g_username);closepopup()}var gMoveSelected=null;
function openMoveGroup(a,b){gMoveSelected=$.tree.focused().selected_arr;if("undefined"==typeof gMoveSelected||0==gMoveSelected.length)gMoveSelected=Array(a);var c=getBG(),f=[],g=[],c=[c.g_sites,c.g_securenotes,c.g_applications],h="",l;for(l in c)if(c.hasOwnProperty(l)){var k=c[l],m;for(m in k)if(k.hasOwnProperty(m)){var j=k[m];if(gMoveSelected&&(1==gMoveSelected.length&&getmoveid(gMoveSelected[0])==get_record_id(j))&&(h=j.group,b)){""!=j.group&&(f[f.length]=j.group);break}j=""!=j.group?j.group:gs("(none)");
"undefined"!=typeof j&&"undefined"==typeof g[j]&&(g[j]="1",f[f.length]=j)}}f.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});""==h&&(1==gMoveSelected.length&&!isNumber(getmoveid(gMoveSelected[0])))&&(h=getmoveid(gMoveSelected[0]));document.getElementById("grpsel").value="";repopulate_combo("grpsel",f);document.getElementById("dialog").title=gs("Change Group Name");document.getElementById("dialogtext").innerHTML=gs("Select or enter a new group name");document.getElementById("dialoggrpinp").style.display=
"none";document.getElementById("dialoggrpsel").style.display="";document.getElementById("dosubgroup").value="undefined"!=typeof b&&b?"1":"0";1==gMoveSelected.length&&(b?document.getElementById("dialogtext").innerHTML+="<br/><br/>"+gs("Group will be created or currently exists under")+": <br/>"+of(h):document.getElementById("grpsel").value=h);$("#dialog").dialog("destroy");$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,dragStop:function(){var a=document.getElementById("grpsel_combo");
a&&"block"==a.style.display&&realShowCombo()},close:function(){var a=document.getElementById("grpsel_combo");a&&"block"==a.style.display&&close_combo("grpsel")},buttons:{Change:function(){var a=1==gMoveSelected.length?getmoveid(gMoveSelected[0]):"";if(1==gMoveSelected.length&&""!=a&&!is_application(a)&&!isNumber(a))getBG().renameGroup(fix_group(a),fix_group(document.getElementById("grpsel").value));else{for(var b="",c=0;c<gMoveSelected.length;c++)if(a=getmoveid(gMoveSelected[c]),is_application(a)||
isNumber(a))b+=(""==b?"":",")+a;if(0==b.length)return;a=document.getElementById("grpsel").value;1==gMoveSelected.length&&"1"==document.getElementById("dosubgroup").value&&a!=h&&0!=a.indexOf(h+"\\")&&(a=h+"\\"+a);getBG().moveSelectedToGroup(a,b)}populate(gLastSearch);$(this).dialog("close")},Close:function(){$(this).dialog("close")}}});$("#dialog").dialog("open");$("#grpsel").click()}var selected_global;
function openCreateGroup(a){selected_global=a;getBG().lpevent("v_cg");document.getElementById("dialog").title=gs("Group Name");document.getElementById("dialogtext").innerHTML=gs("Group Name");document.getElementById("dialoggrpinp").style.display="";document.getElementById("grpinp").value="";document.getElementById("dialoggrpsel").style.display="none";$("#dialog").dialog("destroy");$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,buttons:{OK:function(){var a=
document.getElementById("grpinp").value;for(null!=selected_global&&(a=fix_group(getmoveid(selected_global))+"\\"+a);"\\"==a[0];)a=a.substr(1);if(a==gs("favorites")||a==gs(isSafariNative()?"recently used":"recently usedlower")||a==gs("(New Pending Share Offers)"))alert(gs("That group already exists."));else{var c=getBG(),f=[c.g_sites,c.g_securenotes,c.g_applications],g;for(g in f)if(f.hasOwnProperty(g)){var h=f[g],l;for(l in h)if(h.hasOwnProperty(l)&&h[l].group==a){alert(gs("That group already exists."));
return}}c.addEmptyGroup(a);populate(gLastSearch);$(this).dialog("close")}},Close:function(){$(this).dialog("close")}}});$("#dialog").dialog("open");$("#grpinp").click()}function getmoveid(a){var b="",b="undefined"!=typeof a.id?getgroupnamefromid(a.id):getgroupnamefromid(a.attr("id"));0==b.indexOf("_")&&(b=b.substring(1));return b}function getacct(a){return get_record(a)}
function getDragHTMLForNode(a){var b=a;for(a=0;b&&""==b.attr("id")&&100>a;)b=b.parent(),a++;a=getBG();b=b.attr("id");return(b=getacct(b))?"<div style='background-image:url("+a.geticonurlfromrecord(b)+");background-repeat:no-repeat;'><span style='padding-left: 23px;'>"+of(b.name)+"</span></div>":""}
function getDragHTML(a){var b="<div id='jstree-dragged' class='tree default'>";if(null==a){a=$.tree.focused().selected_arr;for(var c=0;c<a.length;c++)b+=getDragHTMLForNode(a[c])}else b+=getDragHTMLForNode(a);return b+"</div>"}var togglestate=0;
function toggleUserCol(){var a=getcolvisibility("usernamecol"),b=getcolvisibility("ltnamecol"),c="usercol",f="usernamecol",g="usercolhidden",h="usercolvisible",l=a;1==togglestate%2?(c="ltcol",f="ltnamecol",g="ltcolhidden",h="ltcolvisible",l=b):document.getElementById("ltcol").style.paddingRight=!a?"5%":"calc(5% + 20px)";togglestate++;a=document.getElementsByName(c);for(b=0;b<a.length;b++)a[b].className=l?g:h,0==b&&setcolvisibility(f,l?"0":"1")}
function openinparent(a,b){0!=a.indexOf("http")&&(a=g_urlprefix+a);a+="?";for(var c in b)b.hasOwnProperty(c)&&(a+="&"+en(c)+"="+en(b[c]));window.open(a)}function showpopup(){if(getBG().lploggedin){var a=document.getElementById("lppopup"),b=document.getElementById("person");a.style.display="block";a.style.top=parseInt(b.height)+22+"px";a.style.left=b.offsetLeft-180+"px"}else login()}document.addEventListener("click",closepopup,!0);
function closepopup(a){if("block"==document.getElementById("lppopup").style.display&&(!a||!a.target||"person"!=a.target.id&&"identity"!=a.target.id&&"lpusername"!=a.target.id))document.getElementById("lppopup").style.display="none"}var translations=[];translations.DeleteSiteConfirm=gs("Are you sure you want to delete this site?");translations.DeleteSite=gs("Delete Site?");translations.DeleteIdentityConfirm=gs("Are you sure you want to delete this identity?");translations.DeleteIdentity=gs("Delete Identity?");
translations["Invalid Password."]=gs("Invalid Password.");translations["Add Site"]=gs("Add Site");translations["Add Profile"]=gs("Add Profile");translations["Add Identity"]=gs("Add Identity");this.updated_enc=function(){return!0};var g_waitbox=null;
this.show_waitbox=function(a,b){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy());var c=gs("Submitting...");"undefined"!=typeof a&&null!=a&&!0==a?c=gs("LastPass must reencrypt all of your data because of a key change.")+"<br/><br/>"+gs("This may take a while...")+"<br/><br/>"+gs("Please keep this page open until the operation completes.")+'<br/><br/><div id="changepw_progress" style="width: 300px;"></div>':"undefined"!=typeof b&&(b&&""!=b)&&(c=b);b=gs("Please Wait...");var f=Math.min(750,200+4*c.length);
g_waitbox=new Ext.Window({closable:!1,width:f,autoHeight:!0,layout:"fit",modal:!0,title:b,bodyStyle:"padding: 20px",id:"waitbox",html:"<br/><br/><b>"+c+"</b><br/><br/>"});g_waitbox.show()};this.hide_waitbox=function(){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy(),g_waitbox=null)};this.populateff=function(a,b){populateffcommon(convert_object_to_array(getBG().g_formfills),a,b)};this.openff=function(a){getBG().lpevent("v_off");getBG().editprofile(a)};
this.delff=function(a){confirm(gs("Are you sure you would like to delete this form fill profile?"))&&(getBG().lpevent("v_dff"),getBG().deleteformfill(a))};
this.populateident=function(a){var b=convert_object_to_array(getBG().g_identities);if(b.length){if(document.getElementById("identiframe")){var c=document.getElementById("identpane");c.removeChild(document.getElementById("identiframe"))}populateidentcommon(b,a)}else if(!document.getElementById("identiframe")){for(c=document.getElementById("identpane");c.children.length;)c.removeChild(c.children[0]);a=document.createElement("iframe");a.id="identiframe";a.className="overviewiframe";a.src="ident_overview.php";
c.appendChild(a)}};this.openident=function(a){getBG().lpevent("v_oid");callServerFunction("identity",a);return!1};this.delident=function(a){getBG().lpevent("v_did");confirm(gs("Are you sure you want to delete this identity?"))&&callServerFunction("deleteidentity",a,getBG().g_token);return!1};
this.populateshares_remote=function(){cleartab("sharepane");var a=document.getElementById("sharepane");if(!document.getElementById("shareiframe")){getBG().unlock_plug2web();var b=document.createElement("iframe");b.id="shareiframe";b.className="overviewiframe";b.src="share_overview.php?extension=1";a.appendChild(b)}};
this.populatealerts=function(){cleartab("credmonpane");var a=document.getElementById("credmonpane");if(!document.getElementById("credmoniframe")){var b=document.createElement("iframe");b.id="credmoniframe";b.className="overviewiframe";b.src="credmon_overview.php";a.appendChild(b)}};this.cleartab=function(a){for(a=document.getElementById(a);a&&a.children.length;)a.removeChild(a.children[0])};this.refreshsites=function(){getBG().refreshsites()};
this.website_event=function(){var a=document.getElementById("eventtype").value;lpdbg("vault","new vault got website event: "+a);var b={cmd:a,url:g_urlprefix,callback:website_event_callback};switch(a){case "refresh":b.from=document.getElementById("eventdata1").value;b.type=document.getElementById("eventdata2").value;break;case "logoff":break;case "clearcache":break;case "keyweb2plug":b.cmd="web2plug";b.key=document.getElementById("eventdata1").value;b.username=document.getElementById("eventdata2").value;
b.rsa=document.getElementById("eventdata3").value;break;case "checkmultifactorsupport":b.type=document.getElementById("eventdata1").value;break;case "setupsinglefactor":b.type=document.getElementById("eventdata1").value;b.username=document.getElementById("eventdata2").value;b.password=document.getElementById("eventdata3").value;b.silent=document.getElementById("eventdata5").value;"1"!=document.getElementById("eventdata5").value&&g_websiteeventtarget&&g_websiteeventtarget.source.postMessage({cmd:a,
result:"working"},g_websiteeventtarget.origin);break;case "rsadecrypt":b.sharerpublickeyhex=document.getElementById("eventdata1").value;b.sharekeyenchexsig=document.getElementById("eventdata2").value;b.sharekeyenchex=document.getElementById("eventdata3").value;b.sharekeyhex=document.getElementById("eventdata4").value;break;case "request_native_messaging":break;default:console.error("got unsupported website event on new vault: "+a);return}getBG().processCS(null,b,null)};
this.website_event_callback=function(a){lpdbg("vault","new vault got website event callback: "+a.cmd);"checkmultifactorsupport"==a.cmd?(document.getElementById("eventdata4").value=a.type,document.getElementById("eventdata3").value=a.result,g_websiteeventtarget&&g_websiteeventtarget.source.postMessage(a,g_websiteeventtarget.origin)):"setupsinglefactor"==a.cmd?(document.getElementById("eventdata4").value=a.result,g_websiteeventtarget&&g_websiteeventtarget.source.postMessage(a,g_websiteeventtarget.origin)):
"ipcgotdata"==a.cmd&&g_ipctarget.source.postMessage(a,g_ipctarget.origin)};var g_loaded=g_haspluginrsa=!1,g_func=null;this.callFunction=function(a){getBG().lploggedin&&(g_loaded?a():(g_func=a,a=document.createElement("link"),a.rel="stylesheet",a.type="text/css",a.href=g_urlprefix+"m.php/default_ext",document.body.appendChild(a),a=document.createElement("script"),a.src=g_urlprefix+"m.php/localvault_async?rand="+Math.floor(1E3*Math.random()),document.body.appendChild(a)))};
this.doneloadingexternaljs=function(){g_loaded=!0;g_func&&g_func();g_func=null};this.openaddbytab=function(){if(getBG().lploggedin)return"ident"==g_activetab.id?callServerFunction("identity",""):"ff"==g_activetab.id||"credmon"==g_activetab.id?getBG().addprofile():getBG().openaddsite(),!1};this.opencreditmondash=function(a,b){if(getBG().lploggedin)return a?callServerFunction("opencreditmondash",b):callServerFunction("opencreditmondashnoalert",b),!1};function togglerows(){}
var g_ipctarget=null,g_websiteeventtarget=null;
window.addEventListener("message",function(a){if(0==getBG().base_url.indexOf(a.origin)){var b=a.data+"";"addprofile"==b||"addidentity"==b?openaddbytab():0<=b.indexOf("showcredmondash_")?(a=b.substr(16),opencreditmondash(!0,a)):0<=b.indexOf("showcredmondashnoalert_")?(a=b.substr(23),opencreditmondash(!1,a)):"object"==typeof a.data&&("getdata"==a.data.msg?0==a.data.url.indexOf(getBG().base_url)&&(g_ipctarget=a,getBG().processCS(null,{cmd:"ipcgetdata",url:a.data.url,callback:website_event_callback},
null)):"refreshsites"==a.data.msg?getBG().refreshsites():"closeiframe"==a.data.msg?(a=document.body,b=document.getElementById("__serveriframe"),a&&b&&a.removeChild(b)):"websiteevent"==a.data.msg&&(g_websiteeventtarget=a,document.getElementById("eventtype").value=a.data.eventtype,document.getElementById("eventdata1").value=a.data.eventdata1,document.getElementById("eventdata2").value=a.data.eventdata2,document.getElementById("eventdata3").value=a.data.eventdata3,document.getElementById("eventdata4").value=
a.data.eventdata4,document.getElementById("eventdata5").value=a.data.eventdata5,website_event()))}},!1);
function callServerFunction(a,b,c,f){if(getBG().lploggedin){getBG().unlock_plug2web();var g=document,h=!1;if("share"==a||"acceptshare"==a||"rejectshare"==a){if(h=getBG().g_prompts.edit_site_prompt||getBG().g_prompts.edit_sn_prompt,!h&&"share"==a)for(var l=b.split(","),k=0;k<l.length;k++){var m=get_record(l[k]);if(m&&m.pwprotect){h=!0;break}}}else if("identity"==a||"deleteidentity"==a){if(h=getBG().g_prompts.switch_identity_prompt,!h&&""!=b){l=convert_object_to_array(getBG().g_identities);for(k=0;k<
l.length;++k)if(l[k].iid==b&&l[k].pw_prompt){h=!0;break}}}else if("opencreditmondash"==a||"opencreditmondashnoalert"==a)h=!1;if(h&&!f)getBG().security_prompt(function(){callServerFunction(a,b,c,!0)});else{f=g.body;g=g.createElement("iframe");g.type="content";h=1E3*Math.random();h=g_urlprefix+"acctsiframe.php?rand="+h+"&command="+encodeURIComponent(a);b&&(h+="&commandid="+encodeURIComponent(b));c&&(h+="&commandtoken="+encodeURIComponent(c));h+="&version="+encodeURIComponent(lpversion);g.setAttribute("src",
h);g.id="__serveriframe";g.style.position="absolute";g.style.top=g.style.left="0px";try{var j=f.ownerDocument.defaultView.getComputedStyle(f,"");g.style.width=j.width;g.style.height=j.height}catch(v){}f.appendChild(g)}}};
