var g_notifytype=null,g_notifydata=null,g_matchingsites=null;function oninitnotify(){}
function onshownotify(){lpdbg("notify","showing notification");var a=getBG();if(a){lpdbg("notify","got background page");g_notifytype=a.g_notification_type;g_notifydata=a.g_notification_data;$("#body").css("background","#e6e6e6");if("error"==g_notifytype)("undefined"==typeof g_notifydata.yellow||!g_notifydata.yellow)&&$("#body").css("background","#f00"),document.getElementById("notifymsg").innerHTML=g_notifydata.msg,document.getElementById("notifyfeedbackbtn").style.display=g_notifydata.showFeedback?
"":"none",document.getElementById("notifytryagainbtn").style.display=g_notifydata.showLogin?"":"none",g_notifydata.custombutton&&g_notifydata.customaction?(document.getElementById("notifytryagainbtn").style.display="none",document.getElementById("notifycustombtn").value=g_notifydata.custombutton,document.getElementById("notifycustombtn").style.display="",document.getElementById("notifycustombtn").addEventListener("click",function(){getBG().openURL(g_notifydata.customaction);closemole()})):document.getElementById("notifycustombtn").style.display=
"none",document.getElementById("notifycreateaccountbtn").style.display=g_notifydata.showCreateAccount&&!a.LPISLOC?"":"none",document.getElementById("notifydisablebtn").style.display=g_notifydata.multifactor_disable_url?"":"none",document.getElementById("notifydisablesinglebtn").style.display="none";else if("save"==g_notifytype)$("#body").css("background","#87d087"),document.getElementById("notifymsg").innerHTML=gs("Should LastPass remember this password?")+" ("+g_notifydata.tld+")";else if("alert"==
g_notifytype)lpdbg("notify","notify type is alert"),$("#body").css("background","#ddd"),document.getElementById("lefticon").src=a.g_ischrome?"images/warning.svg":"images/warning.png","weak"==g_notifydata.alerttype?(lpdbg("notify","alert type is weak"),document.getElementById("notifymsg").innerHTML=gs("Weak Password"),document.getElementById("alertdescription").innerHTML=gs("LastPass has detected that you are using a weak password for the site below. We recommend going to your account settings for this site, and creating a new password. Use LastPass to generate a unique, strong password for this account. You can then save the changes on the site, and to LastPass.")):
"duplicate"==g_notifydata.alerttype&&(lpdbg("notify","alert type is duplicate"),document.getElementById("notifymsg").innerHTML=gs("Duplicate password"),document.getElementById("alertdescription").innerHTML=gs("LastPass has detected that you have used the password for this login on other sites, too. We recommend going to your account settings for this site, and creating a new password. Use LastPass to generate a unique, strong password for this account. You can then save the changes on the site, and to LastPass.")),
document.getElementById("notifymsg").innerHTML="<span class='alertheader'>"+document.getElementById("notifymsg").innerHTML+"</span>",document.getElementById("alertsite").innerHTML=of(g_notifydata.name),document.getElementById("alertusername").innerHTML=of(g_notifydata.username),lpdbg("notify","done creating alert"),document.body.className+=" alertbody";else if("change"==g_notifytype){g_matchingsites=a.getsites(g_notifydata.tld,!0);var c;if(1==array_length(g_matchingsites))for(var b in g_matchingsites){c=
gs("LastPass detected a password change for user:")+" "+a.getusernamefromacct(a.g_sites[b]);break}else c=gs("LastPass detected a password change for domain:")+" "+g_notifydata.tld;document.getElementById("notifymsg").innerHTML=c}else"upgrade"==g_notifytype&&(g_notifydata.upgrade?(document.getElementById("notifymsg").innerHTML=gs("An Update is Available. Would you like to install?"),document.getElementById("notifyyesbtn").style.display="",document.getElementById("notifynobtn").style.display=""):(g_notifydata.checking?
document.getElementById("notifymsg").innerHTML=gs("Checking For Updates..."):document.getElementById("notifymsg").innerHTML=gs("No Updates Are Available"),document.getElementById("notifyyesbtn").style.display="none",document.getElementById("notifynobtn").style.display="none"));a=document.getElementsByTagName("div");for(b=0;b<a.length;b++)lpdbg("notify","looking at div "+b),0==a[b].id.indexOf("notify")&&"popup"!=a[b].id.substring(a[b].id.length-5)&&(lpdbg("notify","hiding div "+b),a[b].style.display=
"none");document.getElementById("notify"+g_notifytype).style.display="";lpdbg("notify","done showing notification");document.body.style.minHeight="inherit"}}function savethesite(){var a=getBG();g_notifydata.addsite=1;a.g_site_data=g_notifydata;chrome.tabs.create({url:getchromeurl("site.html")});closemole()}
function clicknever(a){var c={neversite:{title:gs("Never For This Site"),cmd:"neversite"},neverdomain:{title:gs("Never For This Domain"),cmd:"neverdomain"}},b="",d,f,e={};for(d in c)null==c[d]?b+='<div id="'+d+'" class="notifyspacer"><div></div></div>':(f="undefined"==typeof c[d].cmd?"":' data-lpcmd="'+c[d].cmd+'"',b+='<div id="'+d+'" class="notifybutton"'+f+'"><div>'+c[d].title+"</div></div>",e[d]=function(){notifyaction(this.getAttribute("data-lpcmd"))});c=document.getElementById("notifyneverpopup");
c.style.left=a.x;c.style.top=0;c.innerHTML=b;for(d in e)document.getElementById(d).addEventListener("click",e[d])}function notifyaction(a){var c=g_notifydata.url,b=getBG();"neversite"==a?c=b.lpcanonizeUrl(c):"neverdomain"==a&&(c=b.lp_gettld_url(c));b.addNever(c);closemole()}
function changeconfirm(){if(1==array_length(g_matchingsites))for(var a in g_matchingsites){getBG().changePassword(g_notifydata.newpw,Array(a));break}else{if(g_browseraction){receiveBG({cmd:"changepw",newpw:g_notifydata.newpw,tld:g_notifydata.tld});return}getBG().openchangepw(g_notifydata.newpw,g_notifydata.tld)}closemole()};
