var do_bgiconinput=!0;
function doc_create_clickable_icons(a,d,b,c){if(do_experimental_popupfill&&document.body){var f=check_nevers(document,g_nevers,document.location.href),e=d=a=!0,g=!0;null!=f&&(a=f.show_for_formfill,d=f.show_for_save,e=f.show_for_autofill,g=f.show_for_clickable_icon);verbose_log("g_popupfill_rows="+g_popupfill_rows+" show_clickable_for_autofill="+e+" show_clickable_for_save="+d+" show_clickable_for_formfill="+a);if((0<g_popupfill_rows&&e||0==g_popupfill_rows&&d||a)&&g){var f=document,h=document.getElementsByTagName("input"),
j,m={},n=checkDocumentForLoginOrphans(document),p=null;if("undefined"!=typeof Math){var u=Math.floor(1E4*Math.random());for(j=0;j<h.length;j++)if(c||popupfill_shoulddofield(document,h[j],b))try{var k=h[j],l=pickFormName(k.form),q=chk_form_has_password(document,k.form)||n,v=chk_form_is_nonlogin_form(document,k.form);if(c)if(looksLikeUsername(h[j]))q=!0,v=!1;else continue;var s=chk_form_ask_generate(document,k.form),w=!1;null!=p&&(null!=l&&l!=p)&&(w=!0,s=chk_form_ask_generate(document,k.form,w));var t=
k.style.width.replace(/px/,"");if(""===t)try{t=("undefined"!=typeof window.getComputedStyle?k.ownerDocument.defaultView.getComputedStyle(k,""):k.currentStyle).width.replace(/px/,"")}catch(y){}if(!(null!=m[l]&&1<=m[l]&&!isInputFieldPassword(document,k)&&(!q||s)&&!g_show_icon_only_on_focus&&(!isASPpage()||!isFirstFieldNonLoginSubForm(document,k))))if((q&&(0<g_popupfill_rows&&e||0==g_popupfill_rows&&d)||(v&&!q||s)&&a)&&g)if((q||s)&&0<t&&30>t)verbose_log("skipping loginform icon create on "+LP_getname_or_idx(f,
k,LP_GETNAME_FAVOR_ID_OVER_NAME)+"because field is too thin");else if(v&&0<t&&100>t)verbose_log("skipping nonloginform icon create on "+LP_getname_or_idx(f,k,LP_GETNAME_FAVOR_ID_OVER_NAME)+"because field is too thin");else if(v&&is_search_field(document,k,!0))verbose_log("skipping nonloginform icon create on "+LP_getname_or_idx(f,k,LP_GETNAME_FAVOR_ID_OVER_NAME)+"because it looks like a search field");else if(v&&k.readOnly)verbose_log("skipping nonloginform icon create on "+LP_getname_or_idx(f,k,
LP_GETNAME_FAVOR_ID_OVER_NAME)+"because it is read-only");else{var r;q&&!s?(p=l,g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,rowtype:"sites"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(r="sites")):q&&s?g_aspx_hack&&isASPpage()?(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,rowtype:"sites"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(r="sites")):(verbose_log("CONFLICT: form "+l+" is a signup form and login form; treat as a signup form and present formfill options"),
g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,rowtype:"formfills"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"formfills"}),g_do_icon_number_hint&&(r=isInputFieldPassword(document,k)?"generate":"formfills")):!q&&s&&chk_form_changepw(document,k.form)?(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,rowtype:"sites"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(r="sites")):(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,
rowtype:"formfills"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"formfills"}),g_do_icon_number_hint&&(r="formfills"));if(checkIsDisplayed(document,k,0,null,u)){g_do_icon_number_hint?do_bgiconinput?isASPpage()&&isFirstFieldNonLoginSubForm(document,k)?setup_input_icon(document,k,"formfills",g_icon_numbers):setup_input_icon(document,k,r,g_icon_numbers):create_or_move_overlay_icon(document,LP_getname_or_idx(f,k,LP_GETNAME_FAVOR_ID_OVER_NAME),OK_CREATE,r,g_icon_numbers):do_bgiconinput?setup_input_icon(document,
k):create_or_move_overlay_icon(document,LP_getname_or_idx(f,k,LP_GETNAME_FAVOR_ID_OVER_NAME),OK_CREATE);g_save_suggest_msg&&(r&&null!=typeof g_icon_numbers&&null!=typeof g_icon_numbers.sites&&1>g_icon_numbers.sites)&&addEventHandler(k,"click",function(a){var b=getEventTarget(a);setTimeout(function(){do_save_suggest_msg(b,document)},0);stopEventPropagation(a);return!1},!1);if(g_clickable_input&&(!("password"==k.type&&formHasUsernameField(k))||g_clickable_input_on_password)&&"true"!==k.getAttribute("clickev")&&
"sites"==r)k.setAttribute("clickev","true"),addEventHandler(k,"click",function(a){var b=document;a=getEventTarget(a);var c=MAGIC+LP_getname_or_idx(b,a,LP_GETNAME_FAVOR_ID_OVER_NAME);null!=b.getElementById(c)&&(g_clickable_input_on_password?is_your_popup_showing(b)||conditional_create_popup(b,a,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(b,k.form),do_bgiconinput?popuptoggle(b,null,LP_getname_or_idx(b,a,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS):popupfilltoggle(b,
c,a,NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)));return!1},!1);null==m[l]?m[l]=1:m[l]++}}}catch(x){verbose&&alert("error: "+x.message+" stack: "+x.stack)}!1==g_weaseled&&setTimeout(function(){weasel(100)},500);g_weaseled=!0}}}}
function popupfilltoggle(a,d,b,c,f,e){if(do_experimental_popupfill)if(null==g_port&&g_ischrome)console_log("disconnected from BG, abort");else{var g=e?!0:!1;g_save_suggest_msg&&setTimeout(function(){destroy_save_suggest_msg(a,MSGDIVID,null);return!1},0);g_keyboardNav=!1;var h;e=b.type;var j=LP_getname_or_idx(a,b,LP_GETNAME_FAVOR_ID_OVER_NAME);if(g_clickable_input)if(g_clickable_input_on_password){h=g_popup_active_username;var m=g_popup_active_password;null==h&&(h="undefined"==typeof b.form||null==
b.form?doc_get_orphan_username(a):form_get_username(a,b.form));null==m&&(m="undefined"==typeof b.form||null==b.form?doc_get_orphan_password(a):form_get_password(a,b.form));h&&m?(h=h.value,verbose_log("PASS3 username="+h),null!=h&&0<h.length&&!g_isie&&sendBG({cmd:"popupfillinputsave",inputstr:h,inputid:j,inputtype:e})):(verbose_log("PASS2 pass empty string"),g_isie||sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:j,inputtype:e}))}else h=b.value,null!=h&&0<h.length&&(verbose_log("PASS1 pass parent field string "+
h),g_isie||sendBG({cmd:"popupfillinputsave",inputstr:h,inputid:j,inputtype:e}));else h="",g_isie||(sendBG({cmd:"popupfillinputsave",inputstr:h,inputid:j,inputtype:e}),verbose_log("PASS0 pass empty string"));e=a.getElementById(d);j=a.getElementById(MAGICIFRAME+d);if(null==j){g_popupfill_ctr>=g_popupfill_max&&(closepopupfills(a),g_popupfill_ctr=0);g_popupfill_ctr=1;g_popupfill_parent_last=g_popupfill_parent=b;verbose_log("["+g_docnum+"]: popupfilltoggle() set: g_popupfill_parent_last="+g_popupfill_parent_last);
g_isie?(init_LPfn(),j=pickFormName(b.form),h=LPfn?LPfn.ie_getpopupfillhint(j):null,null==h&&(h="sites"),g={rowtype:h,offergenerate:c?"1":"0",formid:j,fieldid:LP_getname_or_idx(a,b,LP_GETNAME_FAVOR_ID_OVER_NAME),fieldtype:b.type,opentosave:g},g=LPJSON.stringify(g),document.documentElement.setAttribute("lpifmsg",g)):(j=pickFormName(b.form),c=c?1:0,sendBG({cmd:"setpopupfilllastactive",active:j,activefieldid:LP_getname_or_idx(a,b,LP_GETNAME_FAVOR_ID_OVER_NAME),ask_generate:c,opentosave:g,activefieldtype:b.type}));
g=chk_form_is_nonlogin_form(document,b.form);j=checkDocumentForLoginOrphans(document);j=chk_form_has_password(document,b.form)||j;b=g_popupfill_rows;g&&!j&&(b=g_popupfill_rows_FF);g=g_popupfill_widest+40;120>g&&(g=120);g<g_popupfill_parent.offsetWidth&&(g=g_popupfill_parent.offsetWidth,g+=2*Math.abs(POPUP_FIELD_OFFSET));if(1==b&&!create_onerow_iframe){j=null;g_fillaid&&(j=g_fillaid);isEmptyObject(g_autofillsites)||(j=g_autofillsites[0].aid);if(null!=j){sendBG({cmd:"autofillaid",aid:j});verbose_log("filling only, not creating 1 row iframe");
return}verbose_log("tried to fill form with invalid acct")}0==b&&!do_popup_actions||0==b&&f==NO_FORCE_NOHITS?verbose_log("not creating empty iframe"):(j="undefined"!=typeof g_isloggedin?g_isloggedin:lploggedin,g_dologin_clickable&&!j&&(!g_isie||g_isie&&f==FORCE_SHOW_NOHITS_NOLOGIN)?(verbose_log("login state: checking whether to issue Chrome login prompt"),f!=FORCE_SHOW_NOHITS_NOLOGIN&&(g_isie||sendBG({cmd:"dologinaction"}))):(g_isie||sendBG({cmd:"popupregister",docnum:g_docnum}),j=calculate_iframe_pos(a,
e,g),null!=j?(f=j.posx,j=j.posy,10<b&&(b=10),c&&(b=10),do_popup_actions&&(b+=2),popupfill_create_iframe(a,f,j,d,b,g,g_minheight_override),g_popupfill_iframe_width_save=g):g_popupfill_ctr=0,g_use_grey_icons&&change_clickable_icon_to_cancel(a,e.id)))}else j.parentNode.removeChild(j),g_popupfill_parent_last=g_popupfill_parent,g_popupfill_parent=null,g_popupfill_ctr=0,verbose_log("["+g_docnum+"]: popupfilltoggle() set: g_popupfill_parent_last="+g_popupfill_parent_last)}}
function popupfill_create_iframe(a,d,b,c,f,e,g){if(do_experimental_popupfill){d=parseInt(d)+"px";b=parseInt(b)+"px";var h=a.body;a=a.createElement("iframe");a.id=MAGICIFRAME+c;a.name=MAGICIFRAME+c;a.src=g_isie?"https://0.lastpass.com/#framesrc=LPMAGIC":urlprefix+"popupfilltab.html";0>parseInt(d)&&(d="0px");0>parseInt(b)&&(b="0px");g_frame_css_str="display:block; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5);";
a.style.cssText=g_frame_css_str;h.appendChild(a);a.width=parseInt(e)+"px";a.height="26px";"undefined"!=typeof f&&0<f&&(a.height=24*f+23+"px");a.height=0<parseInt(g)?parseInt(g)+"px":parseInt(a.height)+"px";c=parseInt(a.width)+"px";f=parseInt(a.height)+"px";a.style.cssText=g_frame_css_str+("width: "+c+" !important; height: "+f+" !important; top:"+b+" !important; left:"+d+" !important; ")}}
function weasel(a){g_ctr_weasel++;if(do_experimental_popupfill){if("undefined"==typeof a||!1==a||!0==a||5>a)a=200;g_weaseled=!0;popupfill_resize();g_weasel_id=setTimeout(function(){weasel(a)},a)}}function end_weasel(){do_experimental_popupfill&&null!=g_weasel_id&&(clearTimeout(g_weasel_id),g_weasel_id=null,verbose_log("clearTimeout weasel"),g_weaseled=!1)}
function handle_form_text_change(a,d,b,c){if(do_experimental_popupfill&&!(null==b||null==d||null==c||null==c.keyCode)&&"lpwebsiteeventform"!=b.name&&"lpmanualform"!=b.name&&popupfill_shoulddofield(a,d,SHOULD_DO_ALWAYS)){c=d.value;var f=LP_getname_or_idx(a,d,LP_GETNAME_FAVOR_ID_OVER_NAME);if(g_clickable_input_on_password){var e=g_popup_active_username,g=g_popup_active_password;null==e&&(e="undefined"==typeof d.form||null==d.form?doc_get_orphan_username(a):form_get_username(a,d.form));null==g&&(g="undefined"==
typeof d.form||null==d.form?doc_get_orphan_password(a):form_get_password(a,d.form));a=checkDocumentForLoginOrphans(document);a=chk_form_has_password(document,b)||a;var h=chk_form_is_nonlogin_form(document,b),j=chk_form_ask_generate(document,b);if(e&&g&&(a||j)&&!h){if(d!=e){d==g?(g_isie||(c=e.value,sendBG({cmd:"popupfillinputsave",inputstr:c,inputid:f,inputtype:"password"})),verbose_log("KEYPASS4 username="+c)):(g_isie||sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:f}),verbose_log('KEYPASS5 username=""'));
return}}else{g_isie||(sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:f}),verbose_log('KEYPASS6 formfill? username=""'));return}}if(null==c||0==c.length)g_isie||sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:f}),verbose_log("KEYPASS7 empty username");else{var e=0,m;for(m in g_autofillsites)e++;if(!(0>=e)||g_change_icon_on_input){m=0;var e=null,n;for(n in g_autofillsites)0==g_autofillsites[n].useusername.indexOf(c)&&(m++,e=g_autofillsites[n]);if(1==m)do_autofill_if_matched?g_isie||sendBG({cmd:"autofillaid",
aid:e.aid}):(g_isie||sendBG({cmd:"popupfillinputsave",inputstr:c,inputid:f,inputtype:d.type,issaveall:issaveall(b)}),verbose_log("KEYPASS8 match>0 username="+c));else if(g_isie||sendBG({cmd:"popupfillinputsave",inputstr:c,inputid:f,inputtype:d.type,issaveall:issaveall(b)}),verbose_log("KEYPASS9 match>1 username="+c),chk_form_has_password(document,b),g_change_icon_on_input&&(d=b.elements,"undefined"!=typeof Math&&(b=Math.floor(1E4*Math.random()),null!=d)))for(n=0;n<d.length&&!(c=d[n],checkIsDisplayed(document,
c,0,null,b)&&isInputFieldPassword(document,c)&&null!=c.value&&0<c.value.length);n++);}}}}function issaveall(a){a=a.elements;for(var d=0,b=0,c=0,f=0;f<a.length;f++){var e=a[f].type;"password"==e?b++:"text"==e||"tel"==e||"email"==e?d++:"textarea"==e&&c++}return 1==d&&1==b&&0==c?!1:!0}
function relocate_popupfill_iframes(a,d){if(do_experimental_popupfill){var b,c=null,f=a.getElementsByTagName("iframe");for(b=0;b<f.length;b++){var e=f[b],c=null;if("undefined"!=typeof e.id&&null!=e.id){var g=MAGICIFRAME;if(0==e.id.indexOf(g)){var g=e.id.substr(g.length),g=do_bgiconinput?LP_getElementByIdOrName(a,g):a.getElementById(g),h=!d;if(null!=g&&(do_bgiconinput&&lpIsVisible(g,h)||!do_bgiconinput)){if(h=calculate_iframe_pos(a,g,0<g_minwidth_override?g_minwidth_override:0),null!=h){var g=h.posx,
j=h.posy,h=parseInt(g)+"px",m=parseInt(j)+"px",n=0;if(0<parseInt(g_minwidth_override)){var n=Math.max(parseInt(g_popupfill_iframe_width_save),parseInt(g_minwidth_override))+"px",p=LP_getWindowWidth(window);if(!p)continue;parseInt(n)+parseInt(h)>p&&(h=p-parseInt(n)-20+"px")}else 0<parseInt(g_popupfill_iframe_width_save)?n=parseInt(g_popupfill_iframe_width_save)+"px":(null==c&&(c="undefined"!=typeof window.getComputedStyle?window.getComputedStyle(e):e.currentStyle),n=c.width);0>parseInt(h)&&(h="0px");
p=0;0<parseInt(g_minheight_override)?p=Math.max(parseInt(g_popupfill_iframe_height_save),parseInt(g_minheight_override))+"px":0<parseInt(g_popupfill_iframe_height_save)?p=parseInt(g_popupfill_iframe_height_save)+"px":(null==c&&(c="undefined"!=typeof window.getComputedStyle?window.getComputedStyle(e):e.currentStyle),p=c.height);if(g_iframe_scroll_hack&&!g_frame_scrollable_set){var c=parseInt(p),u=parseInt(n),k;k="undefined"!=typeof window.getComputedStyle?window.getComputedStyle(a.body):"undefined"!=
typeof a.documentElement?a.documentElement.currentStyle:a.body.currentStyle;parseInt(k.height);parseInt(k.width);k=window.innerHeight;var l=window.innerWidth;if(null!=c&&0<c&&null!=k&&0<k||null!=u&&0<u&&null!=l&&0<l)if(parseInt(j)+c>k||parseInt(g)+u>l){g=!1;try{window.self!=window.top&&(g=!0)}catch(q){g=!0}g&&(g_isie||(verbose_log("ensuring this frame/iframe has scrolling enabled"),sendBG({cmd:"iframescrollenable",href:a.location.href})),g_frame_scrollable_set=!0)}}e.style.cssText=g_frame_css_str+
("width: "+n+" !important; height: "+p+" !important; top:"+m+" !important; left:"+h+" !important; position: absolute;")}}else closepopupfills(a)}}}}}var KEY_ESCAPE=27;function keypress_handler(a){a.keyCode==KEY_ESCAPE&&closepopupfills(document);return!1}var KEY_TAB=9,KEY_UP=38,KEY_DOWN=40,KEY_ENTER=13,KEY_SHIFT=16,KEY_RIGHT=39,KEY_PAGEDOWN=34,KEY_PAGEUP=33,KEY_END=35,KEY_HOME=36;
function field_keypress_handler(a,d){if("undefined"!=typeof g_isloggedin?g_isloggedin:lploggedin){var b=a.keyCode;if(b==KEY_ESCAPE)closepopupfills(document);else if(b==KEY_TAB)closepopupfills(document);else if(b==KEY_DOWN){if(!is_your_popup_showing(document)){var c=document;set_active_username_password(c,d.form);if(do_bgiconinput){var f=MAGIC+LP_getname_or_idx(c,d,LP_GETNAME_FAVOR_ID_OVER_NAME);popuptoggle(c,null,LP_getname_or_idx(c,d,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)}else f=
MAGIC+LP_getname_or_idx(c,d,LP_GETNAME_FAVOR_ID_OVER_NAME),popupfilltoggle(c,f,d,NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)}}else if(b!=KEY_UP&&!(b==KEY_SHIFT||0==b)&&!(b==KEY_RIGHT&&a.altKey)&&!is_modifier_key(b)&&b!=KEY_ENTER){if(g_ischrome&&g_setup_hotkey_handler){if(is_hotkey_event(a))return}else if(g_isie&&(c=""+(a.ctrlKey?"control ":""),c+=a.metaKey?"meta ":"",c+=a.altKey?"alt ":"",c+=a.shiftKey?"shift ":"",verbose_log("keycode == "+b+" "+c),"undefined"!=typeof a.metaKey&&a.metaKey||"undefined"!=
typeof a.altKey&&a.altKey||"undefined"!=typeof a.ctrlKey&&a.ctrlKey))return;if("password"==d.type&&formHasUsernameField(d))if(g_clickable_input_on_password)!is_your_popup_showing(document)&&!chk_form_ask_generate(document,d.form)&&conditional_create_popup(document,d,FORCE_SHOW_NOHITS_NOLOGIN);else return;if(!chk_form_has_password(document,d.form))return;is_your_popup_showing(document)||(g_clickable_input_on_password?(c=document,do_bgiconinput?(c=getIconState(c,LP_getname_or_idx(c,d,LP_GETNAME_FAVOR_ID_OVER_NAME)))&&
(c.fillhint&&"sites"==c.fillhint)&&conditional_create_popup(document,d,FORCE_SHOW_NOHITS_NOLOGIN):(f=MAGIC+LP_getname_or_idx(c,d,LP_GETNAME_FAVOR_ID_OVER_NAME),f=LP_getElementByIdOrName(c,f).getAttribute("intrinsic"),null!=f&&"sites"==f&&conditional_create_popup(c,d,FORCE_SHOW_NOHITS_NOLOGIN))):(c=document,do_bgiconinput?(LP_getname_or_idx(c,d,LP_GETNAME_FAVOR_ID_OVER_NAME),popuptoggle(c,null,LP_getname_or_idx(c,d,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)):(f=MAGIC+LP_getname_or_idx(c,
d,LP_GETNAME_FAVOR_ID_OVER_NAME),popupfilltoggle(c,f,d,NO_FORCE_GENERATE,FORCE_SHOW_NOHITS))),g_keyboardNav=!0)}is_your_popup_showing(document)&&(b==KEY_UP&&(g_isie||(sendBG({cmd:"popupfillinputfocusdecrement",count:1}),g_keyboardNav=!0),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),stopEventPropagation(a)),b==KEY_DOWN&&(g_extended_kbd_nav&&a.altKey&&g_hide_navbar?is_your_popup_showing(document)&&(g_isie||sendBG({cmd:"popupfillinputshownavbar"})):g_isie||(sendBG({cmd:"popupfillinputfocusincrement",
count:1}),g_keyboardNav=!0),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),stopEventPropagation(a)),b==KEY_ENTER&&(g_popupfill_parent==d&&g_keyboardNav)&&(g_isie||sendBG({cmd:"popupfillinputfocuschoose"}),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),stopEventPropagation(a)),b==KEY_PAGEUP&&(g_isie||(sendBG({cmd:"popupfillinputfocusdecrement",count:12}),g_keyboardNav=!0),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),stopEventPropagation(a)),b==KEY_PAGEDOWN&&(g_isie||(sendBG({cmd:"popupfillinputfocusincrement",
count:12}),g_keyboardNav=!0),stopEventPropagation(a)),b==KEY_END&&!g_isie&&(sendBG({cmd:"popupfillinputfocusincrement",count:1073741824}),g_keyboardNav=!0),b==KEY_HOME&&!g_isie&&(sendBG({cmd:"popupfillinputfocusdecrement",count:1073741824}),g_keyboardNav=!0));return!1}}
function relocate_popupfill_clickables(a){if(!do_bgiconinput)try{var d,b=0;for(d in g_popup_divs)if(g_popup_divs.hasOwnProperty(d)){var c=g_popup_divs[d].substr(MAGIC.length);if(null!=c&&0<c.length){var f=c;if(null==LP_getElementByIdOrName(a,f)&&!g_double_password_hack&&!g_double_secret_password_hack){var e=a.getElementById(g_popup_divs[d]);if(g_do_icon_number_hint)var g=a.getElementById(g_popup_divs[d]+"_numspan");null!=e&&(e.parentNode.removeChild(e),verbose_log("relocate: deleting orphaned icon container for "+
c),b++);g_do_icon_number_hint&&null!=g&&(g.parentNode.removeChild(g),verbose_log("relocate: deleting orphaned icon number for "+c),b++);delete g_popup_divs[d]}else if(g_do_icon_number_hint){if(e=a.getElementById(g_popup_divs[d]),null!=e){var h=e.getAttribute("intrinsic");null!=h&&("sites"!=h&&"formfills"!=h)&&(h=null);var j={};j.sites=0<g_icon_number_overrides.sites?g_icon_number_overrides.sites:g_icon_numbers.sites;j.formfills=0<g_icon_number_overrides.formfills?g_icon_number_overrides.formfills:
g_icon_numbers.formfills;create_or_move_overlay_icon(a,f,NO_CREATE,h,j)}}else create_or_move_overlay_icon(a,f,NO_CREATE)}}0<b&&setTimeout(function(){checkShouldRecheck()},500)}catch(m){verbose_log("relocate_popupfill_clickables caught error:"+m.message)}}var POPUP_FIELD_OFFSET=-4;
function calculate_iframe_pos(a,d,b){if(!do_experimental_popupfill||null==d)return null;var c=d.style.left,f=d.style.top;if(g_double_password_hack||g_double_secret_password_hack||0>parseInt(c)||0>parseInt(f)){var e=a.getElementById(MAGICIFRAME+d.id);if(null!=e)return b=getAbsolutePos(a,e),f=parseInt(b.top)+"px",c=parseInt(b.left)+"px",{posx:c,posy:f}}e=do_bgiconinput?LP_getname_or_idx(a,d,LP_GETNAME_FAVOR_ID_OVER_NAME):d.id.substr(MAGIC.length);e=d&&do_bgiconinput?d:LP_getElementByIdOrName(a,e);null==
e&&(e=d);if(null!=e){e=getAbsolutePos(a,e);null!=e&&(c=parseInt(e.left)+POPUP_FIELD_OFFSET+"px",f=parseInt(e.top)+parseInt(e.height)+"px",g_do_icon_number_hint&&(f=parseInt(e.top)+parseInt(e.height)+4+"px"));if(null==b||0==b)e=do_bgiconinput?LP_getElementByIdOrName(a,MAGICIFRAME+LP_getname_or_idx(a,d)):a.getElementById(MAGICIFRAME+d.id),null!=e&&(b=getAbsolutePos(a,e).width);a=LP_getWindowWidth(window);if(!a)return{posx:0,posy:0};parseInt(b)+parseInt(c)>a&&(c=a-parseInt(b)-20+"px")}c=parseInt(c)+
"px";f=parseInt(f)+"px";return{posx:c,posy:f}}function verbose_log(a){verbose&&console_log(a)}function is_watermark(){return!1}function checkAskGenerate(){}function sendKey(a,d){try{return keyName="DOM_VK_"+a.toUpperCase(),send_simulated_key(d,0,KeyEvent[keyName],!1)}catch(b){lpdbg("error",b)}return null}
function send_simulated_key(a,d,b,c){if(void 0===a||void 0===a.ownerDocument)return lpdbg("error","No key target!"),!1;d=a.ownerDocument.createEvent("KeyboardEvent");d.initKeyboardEvent("keydown",!0,!0,document.defaultView,!1,!1,c,!1,b,b);var f=a.dispatchEvent(d);d=a.ownerDocument.createEvent("KeyboardEvent");d.initKeyboardEvent("keyup",!0,!0,null,!1,!1,c,!1,b,b);a.dispatchEvent(d);return f}
if("undefined"==typeof KeyEvent)var KeyEvent={DOM_VK_CANCEL:3,DOM_VK_HELP:6,DOM_VK_BACK_SPACE:8,DOM_VK_TAB:9,DOM_VK_CLEAR:12,DOM_VK_RETURN:13,DOM_VK_ENTER:14,DOM_VK_SHIFT:16,DOM_VK_CONTROL:17,DOM_VK_ALT:18,DOM_VK_PAUSE:19,DOM_VK_CAPS_LOCK:20,DOM_VK_ESCAPE:27,DOM_VK_SPACE:32,DOM_VK_PAGE_UP:33,DOM_VK_PAGE_DOWN:34,DOM_VK_END:35,DOM_VK_HOME:36,DOM_VK_LEFT:37,DOM_VK_UP:38,DOM_VK_RIGHT:39,DOM_VK_DOWN:40,DOM_VK_PRINTSCREEN:44,DOM_VK_INSERT:45,DOM_VK_DELETE:46,DOM_VK_0:48,DOM_VK_1:49,DOM_VK_2:50,DOM_VK_3:51,
DOM_VK_4:52,DOM_VK_5:53,DOM_VK_6:54,DOM_VK_7:55,DOM_VK_8:56,DOM_VK_9:57,DOM_VK_SEMICOLON:59,DOM_VK_EQUALS:61,DOM_VK_A:65,DOM_VK_B:66,DOM_VK_C:67,DOM_VK_D:68,DOM_VK_E:69,DOM_VK_F:70,DOM_VK_G:71,DOM_VK_H:72,DOM_VK_I:73,DOM_VK_J:74,DOM_VK_K:75,DOM_VK_L:76,DOM_VK_M:77,DOM_VK_N:78,DOM_VK_O:79,DOM_VK_P:80,DOM_VK_Q:81,DOM_VK_R:82,DOM_VK_S:83,DOM_VK_T:84,DOM_VK_U:85,DOM_VK_V:86,DOM_VK_W:87,DOM_VK_X:88,DOM_VK_Y:89,DOM_VK_Z:90,DOM_VK_WIN:91,DOM_VK_CONTEXT_MENU:93,DOM_VK_NUMPAD0:96,DOM_VK_NUMPAD1:97,DOM_VK_NUMPAD2:98,
DOM_VK_NUMPAD3:99,DOM_VK_NUMPAD4:100,DOM_VK_NUMPAD5:101,DOM_VK_NUMPAD6:102,DOM_VK_NUMPAD7:103,DOM_VK_NUMPAD8:104,DOM_VK_NUMPAD9:105,DOM_VK_MULTIPLY:106,DOM_VK_ADD:107,DOM_VK_SEPARATOR:108,DOM_VK_SUBTRACT:109,DOM_VK_DECIMAL:110,DOM_VK_DIVIDE:111,DOM_VK_F1:112,DOM_VK_F2:113,DOM_VK_F3:114,DOM_VK_F4:115,DOM_VK_F5:116,DOM_VK_F6:117,DOM_VK_F7:118,DOM_VK_F8:119,DOM_VK_F9:120,DOM_VK_F10:121,DOM_VK_F11:122,DOM_VK_F12:123,DOM_VK_F13:124,DOM_VK_F14:125,DOM_VK_F15:126,DOM_VK_F16:127,DOM_VK_F17:128,DOM_VK_F18:129,
DOM_VK_F19:130,DOM_VK_F20:131,DOM_VK_F21:132,DOM_VK_F22:133,DOM_VK_F23:134,DOM_VK_F24:135,DOM_VK_NUM_LOCK:144,DOM_VK_SCROLL_LOCK:145,DOM_VK_COMMA:188,DOM_VK_PERIOD:190,DOM_VK_SLASH:191,DOM_VK_BACK_QUOTE:192,DOM_VK_OPEN_BRACKET:219,DOM_VK_BACK_SLASH:220,DOM_VK_CLOSE_BRACKET:221,DOM_VK_QUOTE:222,DOM_VK_META:224};
function checkShouldRecheck(){if(do_experimental_popupfill&&(verbose_log("entered checkShouldRecheck()"),0<=g_input_cnt)){var a=countInputs(document);g_input_cnt!=a&&(formcachereset(document),g_isie?(setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},200),setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},1E3)):setTimeout(function(){sendBG({cmd:"recheckpage"})},200),g_input_cnt=a)}}function is_watermark_password(){return!1}
function addEventHandler(a,d,b){try{return null==a||null==d||null==b||0>=d.length?null:"undefined"!=typeof a.addEventListener?a.addEventListener(d,b,!1):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+d,b):null}catch(c){return verbose_log("addEventHandler failed, "+c.message),null}}
function stopEventPropagation(a){try{"undefined"!=typeof a.preventDefault?a.preventDefault():typeof window.event&&(window.event.returnValue=!1),"undefined"!=typeof a.stopPropagation?a.stopPropagation():typeof window.event&&(window.event.cancelBubble=!0)}catch(d){verbose_log("stopEventPropagation failed, "+d.message)}}function getEventTarget(a){a=a?a:window.event;if((a="undefined"!=typeof a.target?a.target:a.srcElement)&&"undefined"!=typeof a.nodeType&&3==a.nodeType)a=a.parentNode;return a};
