if(document.getElementById("_docwrite_popover2"))document.getElementById("_docwrite_popover2").innerHTML=gs("FormFill Profiles");if(document.getElementById("_docwrite_popover3"))document.getElementById("_docwrite_popover3").innerHTML=gs("Vault");if(document.getElementById("_docwrite_popover4"))document.getElementById("_docwrite_popover4").innerHTML=gs("Save Site");if(document.getElementById("_docwrite_popover5"))document.getElementById("_docwrite_popover5").innerHTML=gs("Add Note");
if(document.getElementById("_docwrite_popover6"))document.getElementById("_docwrite_popover6").innerHTML=gs("Generate Password");if(document.getElementById("_docwrite_popover8"))document.getElementById("_docwrite_popover8").innerHTML=gs("Password Length");if(document.getElementById("_docwrite_popover9"))document.getElementById("_docwrite_popover9").innerHTML="<label for='pronounceable'>"+gs("Pronounceable")+"</label>";
if(document.getElementById("_docwrite_popover10"))document.getElementById("_docwrite_popover10").innerHTML="<label for='upper'>"+gs("A-Zupper")+"</label>";if(document.getElementById("_docwrite_popover11"))document.getElementById("_docwrite_popover11").innerHTML="<label for='lower'>"+gs("a-zlower")+"</label>";if(document.getElementById("_docwrite_popover12"))document.getElementById("_docwrite_popover12").innerHTML="<label for='digits'>"+gs("0-9")+"</label>";
if(document.getElementById("_docwrite_popover13"))document.getElementById("_docwrite_popover13").innerHTML="<label for='special'>"+gs("Special")+"</label>";if(document.getElementById("_docwrite_popover14"))document.getElementById("_docwrite_popover14").innerHTML="<label for='mindigits'>"+gs("Minimum Digit Count")+"</label>";if(document.getElementById("_docwrite_popover15"))document.getElementById("_docwrite_popover15").innerHTML="<label for='ambig'>"+gs("Avoid Ambiguous Characters")+"</label>";
if(document.getElementById("_docwrite_popover16"))document.getElementById("_docwrite_popover16").innerHTML="<label for='reqevery'>"+gs("Require Every Character Type")+"</label>";if(document.getElementById("_docwrite_popover17"))document.getElementById("_docwrite_popover17").innerHTML=gs("Generate");if(document.getElementById("_docwrite_popover18"))document.getElementById("_docwrite_popover18").innerHTML=gs("Save");
if(document.getElementById("_docwrite_popover19"))document.getElementById("_docwrite_popover19").innerHTML=gs("Advanced Options");if(document.getElementById("_docwrite_popover20"))document.getElementById("_docwrite_popover20").innerHTML=gs("Identities");if(document.getElementById("_docwrite_popover21"))document.getElementById("_docwrite_popover21").innerHTML=gs("Security Check");if(document.getElementById("_docwrite_popover22"))document.getElementById("_docwrite_popover22").innerHTML=gs("Print");
if(document.getElementById("_docwrite_popover23"))document.getElementById("_docwrite_popover23").innerHTML=gs("Refresh Sites");if(document.getElementById("_docwrite_popover24"))document.getElementById("_docwrite_popover24").innerHTML=gs("Import");if(document.getElementById("_docwrite_popover25"))document.getElementById("_docwrite_popover25").innerHTML=gs("Export");if(document.getElementById("_docwrite_popover26"))document.getElementById("_docwrite_popover26").innerHTML=gs("Delete Cache");
if(document.getElementById("_docwrite_popover27"))document.getElementById("_docwrite_popover27").innerHTML=gs("Sessions");if(document.getElementById("_docwrite_popover28"))document.getElementById("_docwrite_popover28").innerHTML=gs("Preferences");if(document.getElementById("_docwrite_popover30"))document.getElementById("_docwrite_popover30").innerHTML=gs("Sites");if(document.getElementById("_docwrite_popover31"))document.getElementById("_docwrite_popover31").innerHTML=gs("Groups");
if(document.getElementById("_docwrite_popover32"))document.getElementById("_docwrite_popover32").innerHTML=gs("FormFill");if(document.getElementById("_docwrite_popover33"))document.getElementById("_docwrite_popover33").innerHTML=gs("Generate");if(document.getElementById("_docwrite_popover34"))document.getElementById("_docwrite_popover34").innerHTML=gs("Advanced");if(getBG().g_hideabout)if(document.getElementById("help"))document.getElementById("help").style.display="none";
