var language="";(g_issafari||g_isopera||g_ismaxthon)&&initlangs(0);function initlangs(a){try{if(!(5<=a)){a++;var c=getBG();if(null==c)setTimeout(function(){initlangs(a)},100);else{null!=c&&(language=c.lpGetPref("language",""));if(null==language||0==language.length)language=navigator.language;include_language(language)}}}catch(b){setTimeout(function(){initlangs(a)},100)}}
var g_page=0,g_scrollPos=0,g_ids=[],g_nummatching=0,g_selectedrow=-1,g_searchhasfocus=!1,g_tree=null,g_treestack=null,g_focusstack=[];
function menuload(a){var c=getBG();get("logouttxt").innerText=gs("Logoff").toUpperCase()+": ";null!=c.g_username&&(get("logouttxt").innerText+=of(c.g_username),get("win").style.display="none",get("container2").style.display="block",get("addbtn").innerHTML=gs("Save Site"),get("add2").style.display="",get("addbtn2").innerHTML=gs("Add Note"),get("addbtn2").style.display=c.g_hidenotes?"none":"",a&&(g_tree=g_treestack=g_focusstack=[],get("searchinput").value="",get("searchxlink").style.display="none",
$("#searchinput").watermark({remove:!0}),$("#searchinput").watermark({html:gs("Search All Data"),cls:"waterclass"}),changepage(0,!0)),drawsites(),"undefined"==typeof a&&0!=getBG().g_popoverstartpage&&changepage(getBG().g_popoverstartpage,!1))}function drawsites(a){var c='<table class="stdrow" id="tbldata">';0==g_page?c+=getsiteshtml():1==g_page&&(c+=gettreehtml(a));get("sites").innerHTML=c+"</table>";get("searchinput").focus()}
function showwin(a,c,b){get("win").style.display="block";get("container2").style.display="none";get("win").width=a;get("win").height=c;get("win").src=b}
function sitematches(a,c,b){return a&&(a.url&&-1!=a.url.toLowerCase().indexOf(c)||-1!=a.name.toLowerCase().indexOf(c)||-1!=a.group.toLowerCase().indexOf(c)||"undefined"!=typeof a.unencryptedUsername&&a.unencryptedUsername&&-1!=a.unencryptedUsername.toLowerCase().indexOf(c)||is_application(a)&&(-1!=a.appname.toLowerCase().indexOf(c)||-1!=getusernamefromacct(a).toLowerCase().indexOf(c)))||b&&(a&&a.extra&&0<a.extra.length&&"http://group"!=a.url)&&-1!=getBG().lpmdec_acct(a.extra,!0,a,getBG().g_shares).toLowerCase().indexOf(c)?
!0:!1}
function getsiteshtml(){var a=getBG(),c="",b=[],d;for(d in a.g_sites)b[d]=a.g_sites[d];for(d in a.g_securenotes)b[d]=a.g_securenotes[d];for(d in a.g_applications)b["app"+d]=a.g_applications[d];var e=get("searchinput").value.toLowerCase(),f=a.get_searchNotesPref(),g=""==e?!0:!1,j=[],l=[],h=[];g_ids=[];for(var n in b)if(is_application(n)&&a.check_ident_appaid(n)||!is_application(n)&&a.check_ident_aid(n)){var m=b[n];"http://group"!=m.url&&(g?j[j.length]=m:sitematches(m,e,f)&&(j[j.length]=m))}recentcount=0;
if(g&&0==g_page){b=getBG().getmatchingsites();for(d in b)l[l.length]=b[d],l[l.length-1].unencryptedUsername=b[d].username;g_nummatching=l.length;a=a.lpGetPref("recentUsedCount",10);if(0<a){j.sort(function(a,b){return a.last_touch>b.last_touch?-1:1});for(d=0;d<a&&d<j.length;d++)h[h.length]=j[d]}if(l.length)for(d in c+=addtitlerow(gs("Matching Sites"),"togglematching()","matchingsitesid","<img src='images/down.png'/>"),l)c+=addsiterow(l[d],!0,!1,!1,!0);if(h.length)for(d in c+=addtitlerow(gs("Recent Sites"),
"togglerecent()","recentusedid",0==l.length?"<img src='images/down.png'/>":"<img src='images/right.png'/>"),h)c+=addsiterow(h[d],!1,!0,!1,0==l.length)}else for(d in j.sort(a.lp_sort_case_insensitive_name),j)c+=addsiterow(j[d],!1,!1);return c}
function gettreehtml(a){if(g_tree){if("__lp_back"==a)return g_treestack.pop(),g_selectedrow=g_focusstack.pop(),showtree(g_treestack.length?g_treestack[g_treestack.length-1].children:g_tree,0==g_treestack.length);var c=g_treestack.length?g_treestack[g_treestack.length-1].children:g_tree,b;for(b in c){var d=b.lastIndexOf("\\"+a);if(b==a||0<d&&d==b.length-a.length-1)return g_treestack.push(c[b]),get("sites").scrollTop=0,g_focusstack.push(g_selectedrow),g_selectedrow=-1,showtree(c[b].children)}}a={};
var e=getBG(),f=[];for(b in e.g_sites)f[b]=e.g_sites[b];for(b in e.g_securenotes)f[b]=e.g_securenotes[b];for(b in e.g_applications)f["app"+b]=e.g_applications[b];var g=get("searchinput").value.toLowerCase(),j=e.get_searchNotesPref(),l=""==g?!0:!1,c=[],d=[],h,n=!1,m;for(m in f)if(is_application(m)&&e.check_ident_appaid(m)||!is_application(m)&&e.check_ident_aid(m)){var p=f[m];if(l||sitematches(p,g,j)){h=p.group;if(null==h||""==h)h=is_application(p)?gs("Applications"):"http://sn"==p.url?gs("Secure Notes"):
gs("(none)");var q=h.split("\\"),k="";for(b=0;b<q.length;b++)0==b&&"\\"==h[0]?(k+="\\",b++):""!=k&&(k+="\\"),k+=q[b],lp_in_array(k,c)||(c[c.length]=k);"http://group"!=p.url&&(d[d.length]=p);"1"==p.fav&&(n=!0)}}c.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});n&&(a[gs("favorites")]={title:gs("favorites"),children:{}});if(!l&&7>d.length){a={};for(b=0;b<d.length;b++)a[get_record_id(d[b])]={title:getSiteMenuTitle(d[b],!0),icon:getBG().geticonurlfromrecord(d[b])}}else{m=c.length;e=[];
for(b=0;b<m;b++)h=c[b],f=h.lastIndexOf("\\"),k=-1==f||0==f?h:h.substring(f+1),k={title:k,children:{}},e[h]=k,-1==f||0==f?a[h]=k:e[h.substring(0,f)].children[h]=k;d.sort(function(a,b){return a.name.toLowerCase()<b.name.toLowerCase()?-1:1});for(b=0;b<d.length;b++){"1"==d[b].fav&&"undefined"!=typeof a[gs("favorites")]&&(a[gs("favorites")].children[get_record_id(d[b])]={title:getSiteMenuTitle(d[b],!0),icon:getBG().geticonurlfromrecord(d[b])});h=d[b].group;if(null==h||""==h)h=gs("(none)");k={title:getSiteMenuTitle(d[b],
!0),icon:getBG().geticonurlfromrecord(d[b])};"undefined"!=typeof e[h]&&(e[h].children[get_record_id(d[b])]=k)}}g_tree=a;g_treestack=[];g_focusstack=[];return showtree(a,!0)}
function showtree(a,c){var b="";c||(b+='<tr><td style="color:white; background:-webkit-gradient(linear, left top, left bottom, color-stop(0%,#158aff), color-stop(44%,#0b7ef1), color-stop(100%,#126eca));"   onclick="drawsites(\'__lp_back\')"><img src="images/left.png"/> '+gs("Back")+"</td></tr>");var d=[],e=[],f=0,g;for(g in a)if("undefined"==typeof a[g].icon)if(c&&g==gs("favorites"))f=!0;else{var j=g.lastIndexOf("\\");0<j&&(g=g.substr(j+1));d[d.length]=g}else j=get_record(g),e[e.length]=j;e.sort(getBG().lp_sort_case_insensitive_name);
d.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});f&&(b+=addfolder(gs("favorites")));for(g=0;g<d.length;g++)b+=addfolder(d[g]);for(g=0;g<e.length;g++)b+=addsiterow(e[g],!1,!1);return b}function getSiteMenuTitle(a,c){var b=c?getusernamefromacct(a):a.username;return trunc2(a.name,b,300)}
function addsiterow(a,c,b,d,e){"undefined"!=typeof a.fiid&&""!=a.fiid||get_record_id(a);var f=getBG().geticonurlfromrecord(a),g="";b&&(g=e?"recentshown":"recenthidden");d&&(g=e?"favsshown":"favshidden");c&&(g=e?"matchingshown":"matchinghidden");g_ids[g_ids.length]=get_record_id(a);b=getusernamefromacct(a);return'<tr class="'+g+'"><td aid="'+of(get_record_id(a))+'" onclick="mainaction(\''+of(get_record_id(a))+"', "+c+')" onContextMenu="return secondaryaction(\''+of(get_record_id(a))+"', "+c+')" id="site'+
of(get_record_id(a))+'"><img src="'+f+'" class="icon"/> '+trunc2(a.name,b,300)+"</td></tr>"}
function addfolder(a){var c=a.replace("\\","\\\\");return'<tr><td  onclick="'+("drawsites('"+ofa(c)+"')")+'"><b><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAj1JREFUOBF9wbtvzWEcx/H39/k951KNoxYawuaSLqZG4hqLicEikRjE5PJPMAiJHYtb4l/ohMQ9SCQsIg01UGk1iuP0nN/l+X0/FAmDer2iJP7lyoM5FSmRkrNocvpT31zWzdP7d+/yG+X8/Pn7l/YPIksoqopje9Yw13MMcI0uq2onZmy4/uTL6WdPp8d3nZg4FFlCXYvPffF6ToQgquR0B4ndG4fYsWmE4WbYN3GrdzayBAGZQTsCZpiMdjPw8cuATSsbbFm1gjv3Wicj/2EGjQwkUGa0Y2BqXvRmCsbXt2jEQJycGH/e7oyNmQX+EOIMhpGFwE8m3AWtDAtGlmUIiKawed2Oqw0zA/GDwAxufsBZZBhOZtCMAZNwN8wMCSJJOV62ipmL1GUGoYPZcu4+Xc+RnWuJAYIFXJAZBAeaMBRBEpHKgrykLpvIxcLUQ76+esG5EZi9DAYIMCADMqAN+NFH4EbE1PY0oDv1mmp+Gq9yVo4fJo4dpzOcIQV+ERKEAG8ubKVIPcyDRapAHFrF6J5zgIOEcPoz1yi/gTCkABjCiJ3tLGqGDq5URipJdU45ewUQvzgLg0CZoKigSjV5mRgUJSOrPxOBg6cez64YbgxFCiRPYIAEOHhFp1VBs0B1Dr6A112UvtJes5e3wM3z20b5IVJKRg0SqAaVyAvwHGmA6j6qeyh1Uf0NcP4WVXpM/U94aoACKENqgLeQD4MqpBKshJCo85y/ReXFy6lLBzYiwPg/AXYbXJP89h0EnjqSmhXUWAAAAABJRU5ErkJggg==" class="icon"/> '+of(a)+
"</b></td></tr>"}function addtitlerow(a,c,b,d){return'<tr class="titlerow" style="height:25px;"><td  id="'+b+'" onclick="'+c+'">'+(d?d+" ":"")+of(a)+"</td></tr>"}function togglefavs(){var a="favsshown",c=document.getElementsByClassName("favshidden");0==c.length?(a="favshidden",c=document.getElementsByClassName("favsshown"),get("favsid").innerHTML="\u25ba "+gs("Favoritesproper")):get("favsid").innerHTML="\u25bc  "+gs("Favoritesproper");for(;c.length;)c[0].className=a}
function isrecentshown(){return 0==document.getElementsByClassName("recenthidden").length}function togglerecent(){var a="recentshown",c=document.getElementsByClassName("recenthidden");isrecentshown()?(a="recenthidden",c=document.getElementsByClassName("recentshown"),get("recentusedid").innerHTML="<img src='images/right.png'/> "+gs("Recent Sites")):get("recentusedid").innerHTML="<img src='images/down.png'/> "+gs("Recent Sites");for(;c.length;)c[0].className=a}
function ismatchingshown(){return 0==document.getElementsByClassName("matchinghidden").length}function togglematching(){var a="matchingshown",c=document.getElementsByClassName("matchinghidden");ismatchingshown()?(a="matchinghidden",c=document.getElementsByClassName("matchingshown"),get("matchingsitesid").innerHTML="<img src='images/right.png'/> "+gs("Matching Sites")):get("matchingsitesid").innerHTML="<img src='images/down.png'/> "+gs("Matching Sites");for(;c.length;)c[0].className=a}
function mainaction(a,c){var b,d=0;b='<table class="submenustyle" id="tblsub">'+('<tr><td id="submenu'+d++ +'" style="color:white; background:-webkit-gradient(linear, left top, left bottom, color-stop(0%,#158aff), color-stop(44%,#0b7ef1), color-stop(100%,#126eca));"   onclick="back()"><img src="images/left.png"/> '+gs("Back")+"</td></tr>");if(1>=g_page)g_scrollPos=get("sites").scrollTop,get("sites").style.display="none",get("btnrow").style.display="none",get("search").style.display="none","undefined"!=
typeof getBG().g_sites[a]?(b=c?b+('<tr><td id="submenu'+d++ +'" onclick="getBG().fillaid(\''+of(a)+"'); getBG().closePop();\">"+gs("AutoFill")+"</td></tr>"):b+('<tr><td id="submenu'+d++ +'" onclick="getBG().launch(\''+of(a)+"'); getBG().closePop();\">"+gs("Launch")+"</td></tr>"),b+='<tr><td  id="submenu'+d++ +'" onclick="getBG().editAid(\''+of(a)+"'); getBG().closePop();\">"+gs("Edit")+"</td></tr>",getBG().can_copy_to_clipboard()&&(b+='<tr><td id="submenu'+d++ +'" onclick="getBG().copyusername(\''+
of(a)+"'); getBG().closePop();\">"+gs("Copy Username")+"</td></tr>",b+='<tr><td id="submenu'+d++ +'" onclick="getBG().copypassword(\''+of(a)+"'); getBG().closePop();\">"+gs("Copy Password")+"</td></tr>",b+='<tr><td id="submenu'+d++ +'" onclick="getBG().copyurl(\''+of(a)+"'); getBG().closePop();\">"+gs("Copy URL")+"</td></tr>"),b+='<tr><td  id="submenu'+d++ +'" onclick="getBG().gotourl(\''+of(a)+"'); getBG().closePop();\">"+gs("Go to URL")+"</td></tr>"):"undefined"!=typeof getBG().g_securenotes[a]?
(b+='<tr><td id="submenu'+d++ +'" onclick="getBG().editAid(\''+of(a)+"'); getBG().closePop();\">"+gs("Edit")+"</td></tr>",getBG().can_copy_to_clipboard()&&(b+='<tr><td id="submenu'+d++ +'" onclick="getBG().copynote(\''+of(a)+"'); getBG().closePop();\">"+gs("Copy Note")+"</td></tr>")):is_application(a)&&(!g_issafari&&getBG().have_binary()&&(b+='<tr><td id="submenu'+d++ +'" onclick="getBG().launch(\''+of(a)+"'); getBG().closePop();\">"+gs("Launch")+"</td></tr>"),getBG().can_copy_to_clipboard()&&(b+=
'<tr><td id="submenu'+d++ +'" onclick="getBG().copyusername(\''+of(a)+"'); getBG().closePop();\">"+gs("Copy Username")+"</td></tr>",b+='<tr><td id="submenu'+d++ +'" onclick="getBG().copypassword(\''+of(a)+"'); getBG().closePop();\">"+gs("Copy Password")+"</td></tr>",b+='<tr><td id="submenu'+d++ +'" onclick="getBG().copyurl(\''+of(a)+"'); getBG().closePop();\">"+gs("Copy URL")+"</td></tr>"),b+='<tr><td id="submenu'+d++ +'" onclick="getBG().editAid(\''+of(a)+"'); getBG().closePop();\">"+gs("Edit")+
"</td></tr>"),b+='<tr><td id="submenu'+d++ +'" onclick="setTimeout(function() { getBG().deleteAid(\''+of(a)+"'); }, 0); getBG().closePop();\">"+gs("Delete")+"</td></tr>";else if(2==g_page)g_scrollPos=get("formfill").scrollTop,get("formfill").style.display="none",get("btnrow").style.display="none",b+='<tr><td id="submenu'+d++ +'" onclick="getBG().editprofile(\''+of(a)+"'); getBG().closePop();\">"+gs("Edit")+"</td></tr>",b+='<tr><td  id="submenu'+d++ +'" onclick="getBG().fillform(\''+of(a)+"'); getBG().closePop();\">"+
gs("Fill")+"</td></tr>";else if(4==g_page){get("advancedpage").style.display="none";var e=getBG();b+="<tr><td"+(0==e.g_identity?'><img src="images/checkmark.gif">':" onclick=\"getBG().switch_identity('', false, false, false, true);changepage(0);\">")+gs("All")+"</td></tr>";for(var f in e.g_identities){var g=e.g_identities[f].deciname;b=e.g_identities[f].iid==e.g_identity?b+('<tr><td><img src="images/checkmark.gif"> '+of(g)+"</td></tr>"):b+('<tr><td id="submenu'+d++ +'" onclick="getBG().switch_identity(\''+
of(e.g_identities[f].iid)+"', false, false, false, true);changepage(0);\">"+of(g)+"</td></tr>")}}get("submenu").innerHTML=b+"</table>";get("submenu").style.display="block"}function secondaryaction(a,c){1>=g_page?(c?getBG().fillaid(a):getBG().launch(a),getBG().closePop()):2==g_page&&(getBG().fillform(a),getBG().closePop());return!1}
function back(){g_insubmenu=!1;get("submenu").style.display="none";0==g_page?(get("sites").style.display="block",get("btnrow").style.display="block",get("search").style.display="block",get("sites").scrollTop=g_scrollPos):1==g_page?(get("sites").style.display="block",get("btnrow").style.display="none",get("search").style.display="block",get("sites").scrollTop=g_scrollPos):2==g_page?(get("formfill").style.display="block",get("btnrow").style.display="block",get("formfill").scrollTop=g_scrollPos):4==
g_page&&(get("advancedpage").style.display="block")}
function trunc2(a,c,b){a||(a="");c||(c="");var d=get("gettextextent");d||(d=document.createElement("span"),d.id="gettextextent",d.style.cssText="display:none;position:absolute;top:-100px;left:1000px;",document.body&&document.body.appendChild(d));var e=" <b>"+of(a)+"</b>"+(c.length?" ("+of(c)+")":"");for(d.innerHTML=e;d.offsetWidth>b;)a=a.length?a.substr(0,a.length-1):"",c=3<c.length?c.substr(0,c.length-3):"",e=" <b>"+of(a)+"..</b>"+(c.length?" ("+of(c)+"..)":""),d.innerHTML=e;return e}
function get(a){return document.getElementById(a)}
function changepage(a,c){if(3==g_page&&3==a)return!1;for(var b="logoff search sites formfill btnrow generate advancedpage submenu".split(" "),d=[["logoff","search","sites","btnrow"],["logoff","search","sites"],["logoff","formfill","btnrow"],["logoff","generate"],["logoff","advancedpage"]],e=0;e<b.length;e++)get(b[e]).style.display="none";for(e=0;e<d[a].length;e++)get(d[a][e]).style.display="block";1>=a&&(get("sites").scrollTop=0);get("searchinput").value="";1==g_page&&(get("sites").style.height="313px");
1==a&&(get("sites").style.height="354px");g_page=a;g_selectedrowsubmenu=g_selectedrow=-1;setGlowImg();c||refreshPage();return!1}function setGlowImg(){for(var a=["vault","notes","formfill","generate","advanced"],c=0;c<a.length;c++)get("navimg"+c).src="images/menu_"+a[c]+".png";get("navimg"+g_page).src="images/menuglow_"+a[g_page]+".png"}
function refreshPage(a){if(1>=g_page)get("searchxlink").style.display=""==get("searchinput").value?"none":"inline",1==g_page&&(g_tree=null,g_treestack=[],g_focusstack=[]),menuload(),a||$("#searchinput").watermark({remove:!0}),0==g_page?(get("addbtn").innerHTML=gs("Save Site"),get("add2").style.display="",get("addbtn2").innerHTML=gs("Add Note"),get("addbtn2").style.display=getBG().g_hidenotes?"none":"",a||$("#searchinput").watermark({html:gs("Search All Data"),cls:"waterclass"})):1==g_page&&(get("searchxlink").style.display=
"none",a||$("#searchinput").watermark({html:gs("Search All Groups"),cls:"waterclass"})),get("searchinput").focus();else if(2==g_page)g_issafari&&(a=getBG().lpGetPref("language",""),""==a&&"undefined"!=typeof navigator.language&&(a=navigator.language.toLowerCase()),0==a.indexOf("pt")&&(get("addbtn2").style.fontSize="10px")),get("addbtn").innerHTML=gs("Add Profile"),get("add2").style.display="",get("addbtn2").innerHTML=gs("Add Credit Card"),get("addbtn2").style.display="",showformfills(),get("vaultbtn").focus();
else if(3==g_page){try{onshowgenerate()}catch(c){}get("searchinput").focus();get("searchinput").blur()}else 4==g_page&&(get("searchinput").focus(),get("searchinput").blur())}
function showformfills(){var a='<table class="stdrow" id="tblff">',c=getBG(),b=0,d;for(d in c.g_formfills){var e=c.g_formfills[d].ffid;c.check_ident_ffid(e)&&(a+='<tr><td id="formfill'+b++ +'" ffid="'+of(e)+'" onclick="mainaction(\''+of(e)+"')\" onContextMenu=\"return secondaryaction('"+of(e)+'\')" style="padding-left:10px;">'+trunc2(c.g_formfills[d].decprofilename,"",300))}get("formfillinner").innerHTML=a+"</table>"}function rollmain(a,c,b){g_page!=a&&roll(c,b)}
function roll(a,c){a.src="images/"+c}function add(){0==g_page?getBG().saveall():1==g_page?getBG().openaddsecurenote():2==g_page&&getBG().addprofile();getBG().closePop()}function add2(){0==g_page?getBG().openaddsecurenote():2==g_page&&getBG().addcreditcard();getBG().closePop()}function savegenprefs(){onhidegenerate()}window.addEventListener("keydown",function(a){handle_keydown(a)},!1);
function handle_keydown(a){if("none"==get("win").style.display){var c=0!=a.keyCode?a.keyCode:a.charCode;if(68==c&&a.ctrlKey)document.body.innerHTML="<pre>"+getBG().g_console_log+"</pre>",a.cancelBubble=!0,a.preventDefault(),a.stopPropagation();else{if(9==c)return a.cancelBubble=!0,a.preventDefault(),a.stopPropagation(),changepage((g_page+1)%5),!1;if(!(2<g_page)){var b="block"==get("submenu").style.display;a=b?"tblsub":2==g_page?"tblff":"tbldata";var d=get("searchinput").value.toLowerCase();if(40==
c||38==c){var d=g_selectedrow,e=get(a).children[0].children,b=e.length,f=40==c?d+1:-1==d?b:d-1;if(!(f+1>b||0>f)){if("matchingsitesid"==e[f].children[0].id||"recentusedid"==e[f].children[0].id)if(f=40==c?f+1:-1==d?b:f-1,f+1>b||0>f)return;0==g_page&&(f>d&&(f==g_nummatching&&!isrecentshown())&&togglerecent(),f<d&&(f==g_nummatching-1&&!ismatchingshown())&&togglematching());-1!=d&&(e[g_selectedrow].children[0].className=e[g_selectedrow].children[0].className.replace(/\bsitefocus\b/,""));g_selectedrow=
f;e[g_selectedrow].children[0].className+=" sitefocus";c=e[g_selectedrow].offsetTop;c<get(a).scrollTop&&(get(a).scrollTop-=45);280<c&&(get(a).scrollTop+=45)}}else if(39==c){if(-1!=g_selectedrow){g_focusstack.push(g_selectedrow);e=get(a).children[0].children;if(c=e[g_selectedrow].children[0])c.onclick();g_selectedrow=-1}}else if(37==c)-1!=g_selectedrow&&(g_selectedrow=g_focusstack.pop(),1==g_page&&!b?drawsites("__lp_back"):back());else if(13==c&&-1!=g_selectedrow&&(e=get(a).children[0].children,c=
e[g_selectedrow].children[0]))if(b)c.onclick();else c=2==g_page?c.getAttribute("ffid"):c.getAttribute("aid"),secondaryaction(c,0==g_page&&""==d&&g_selectedrow<g_nummatching)}}}}function clearkeyboardnav(){if("undefined"!=typeof g_selectedrow&&-1!=g_selectedrow){var a=get("tbldata").children[0].children;a&&(a.length>g_selectedrow&&a[g_selectedrow].children)&&(a[g_selectedrow].children[0].className=a[g_selectedrow].children[0].className.replace(/\bsitefocus\b/,""));g_selectedrow=-1}}
function refreshPageIfSearch(a){a=0!=a.keyCode?a.keyCode:a.charCode;37<=a&&40>=a||9==a||refreshPage(!0)};
