var last_logout_on_close=0,hide_binary_dl_links=!1,show_notifications_help_button=!0,show_hotkeys_help_button=!0,show_advanced_help_button=!0,show_general_help_button=!0,showNotification_is_superset=!1,gray_color="#cdcdcd",black_color="black",notification_checkbox_ids=[{boxid:"showGenerateNotifications",labelid:"_docwrite_prefs24"},{boxid:"showFormFillNotifications",labelid:"_docwrite_prefs25"},{boxid:"showSaveSiteNotifications",labelid:"_docwrite_prefs26"},{boxid:"showNotificationsAfterClick",labelid:"_docwrite_prefs27"},
{boxid:"showFillNotificationBar",labelid:"_docwrite_prefs28"},{boxid:"showSaveNotificationBar",labelid:"_docwrite_prefs29"},{boxid:"showChangeNotificationBar",labelid:"_docwrite_prefs30"}];
function onLoad(a){if(a){document.getElementById("save").innerHTML=gs("Save");sr(document,"cancel","value","Cancel");sr(document,"helptranslate","value","Help Translate");if(enable_native_idle&&"undefined"!=typeof chrome&&"undefined"!=typeof chrome.idle||(getBG().g_is_win||getBG().g_is_linux||getBG().g_is_mac)&&getBG().have_binary())document.getElementById("idlelogoffspan").style.display="block";else if(!g_issafari&&!g_isopera&&!g_ismaxthon&&(getBG().g_is_win||getBG().g_is_linux||getBG().g_is_mac))!1==
hide_binary_dl_links&&(document.getElementById("idlelogoffneedbinaryspan").style.display="block");else if((g_issafari||g_isopera||g_ismaxthon)&&(getBG().g_is_win||getBG().g_is_mac||getBG().g_is_linux)&&!1==hide_binary_dl_links)document.getElementById("idlelogoffneedbinaryspansafari").style.display="block";if(!getBG().lppassusernamehash&&(getBG().g_is_win||getBG().g_is_mac||getBG().g_is_linux)&&!getBG().LPISLOC&&!getBG().is_chrome_portable())if(!getBG().g_is_win||!g_issafari)if(getBG().have_binary())document.getElementById("enablenamedpipesspan").style.display=
"block";else if(!g_issafari&&!g_isopera&&!g_ismaxthon&&islastpass&&(getBG().g_is_win||getBG().g_is_linux||getBG().g_is_mac))document.getElementById("enablenamedpipesneedbinaryspan").style.display="block";g_ischrome&&getBG().g_shownewloginoption&&(document.getElementById("enablenewloginspan").style.display="block");"undefined"!=typeof chrome&&"undefined"!=typeof chrome.contextMenus&&(document.getElementById("hidecontextspan").style.display="block");g_isopera&&getBG().g_opera_context&&(document.getElementById("hidecontextspan").style.display=
"block");g_issafari&&(document.getElementById("hidecontextspan").style.display="block");islastpass||(document.getElementById("helptranslate").style.display="none");getBG().can_clear_clipboard()&&(document.getElementById("clearclipboardspan").style.display="block");g_issafari&&(document.getElementById("hideshowacctsingroupsspan").style.display="none");if(g_issafari||g_isopera||g_ismaxthon)document.getElementById("shownotificationsspan").style.display="none",document.getElementById("showsavesitenotificationsspan").style.display=
"none";getBG().LPISLOC&&(document.getElementById("launchaccountsettings").style.display="none",document.getElementById("security_prompts").style.display="block");getBG().g_can_open_popover||(document.getElementById("popover").style.display="none");getBG().g_nopoll&&(document.getElementById("pollcontainer").style.display="none");getBG().LPISLOC&&(document.getElementById("pollcontainer").style.display=document.getElementById("otpcontainer").style.display="none");getBG().g_norecovery&&(document.getElementById("otpcontainer").style.display=
"none");if(getBG().g_hidevault||getBG().g_hideshowvault)document.getElementById("showvaultcontainer").style.display="none";getBG().g_hidesaedhotkey&&(document.getElementById("saedhkrow").style.display="none");getBG().g_hidelogoffprefs&&(document.getElementById("logoffprefscontainer").style.display="none",document.getElementById("security").style.display="none");getBG().g_hideappearancebox&&(document.getElementById("appearancespan").style.display="none");getBG().g_hidesearch&&(document.getElementById("searchhkrow").style.display=
"none");getBG().g_offer_popupfill||(document.getElementById("usepopupfillrow").style.display="none");g_ischrome||(document.getElementById("showmatchingbadgerow").style.display="none");getBG().g_hidevault&&(document.getElementById("homehkrow").style.display="none");getBG().g_hiderecentlyusedlistsize&&(document.getElementById("recentlyusedlistsizespan").style.display="none");getBG().g_hidenotes&&(document.getElementById("searchnotesspan").style.display="none");show_hotkeys_help_button||(document.getElementById("hotkeys_help").style.display=
"none");populate();if(!0==showNotification_is_superset&&!g_issafari&&!g_isopera){document.getElementById("showNotifications").addEventListener("click",function(){supernotification_handler(event)});for(var b in notification_checkbox_ids)(g_issafari||g_isopera)&&"showSaveSiteNotifications"==notification_checkbox_ids[b].boxid||(document.getElementById(notification_checkbox_ids[b].boxid).addEventListener("click",function(){notification_checkbox_handler(event)}),!1==document.getElementById("showNotifications").checked?
(document.getElementById(notification_checkbox_ids[b].boxid).addEventListener("click",function(){notification_checkbox_handler(event)}),document.getElementById(notification_checkbox_ids[b].labelid).style.color=gray_color):document.getElementById(notification_checkbox_ids[b].labelid).style.color=black_color)}a=getBG().g_pref_tab;getBG().g_pref_tab=null;a||(a="general");menuaction(a)}else get_data("prefs",function(){onLoad(!0)})}
function check(a,b,d){document.getElementById(b).checked=1==a.lpGetPref(b,d)}function fillVal(a,b,d){a=a.lpGetPref(b,d);"recentUsedCount"==b&&(a=parseInt(a));document.getElementById(b).value=a}function setSelect(a,b,d){var e=document.getElementById(b);a=a.lpGetPref(b,d);for(b=0;b<e.options.length;b++)if(a==e.options[b].value){e.selectedIndex=b;break}}
function showChromeLanguageError(){alert(gs("Google Chrome requires that extensions use the same language as the browser, so in order to switch LastPass's language, please change the main browser language under Chrome's Options."));document.getElementById("save").focus()}
function populate(){createMenu();filldefaultffid();fillLanguage();var a=getBG();check(a,"disablecrpw",1);check(a,"logoffWhenCloseBrowser",0);check(a,"highlightFields",1);check(a,"automaticallyFill",1);check(a,"showvault",a.g_showvaultdefault);check(a,"showAcctsInGroups",1);check(a,"hideContextMenus",0);check(a,"donotoverwritefilledfields",0);check(a,"showNotifications",1);check(a,"showGenerateNotifications",1);check(a,"showFormFillNotifications",1);check(a,"showSaveSiteNotifications",0);check(a,"showNotificationsAfterClick",
1);check(a,"showFillNotificationBar",1);check(a,"showSaveNotificationBar",1);check(a,"showChangeNotificationBar",1);check(a,"usepopupfill",1);check(a,"showmatchingbadge",1);check(a,"warninsecureforms",0);check(a,"dontfillautocompleteoff",0);check(a,"openloginstart",a.LPISUPEK?1:0);check(a,"storeLostOTP",1);check(a,"enablenamedpipes",1);check(a,"enablenewlogin",1);check(a,"clearfilledfieldsonlogoff",0);check(a,"toplevelmatchingsites",0);fillVal(a,"logoffWhenCloseBrowserVal","0");fillVal(a,"idleLogoffVal",
"");document.getElementById("idleLogoffEnabled").checked=0<parseInt(document.getElementById("idleLogoffVal").value);fillVal(a,"autoautoVal","25");document.getElementById("autoautoEnabled").checked=0<parseInt(document.getElementById("autoautoVal").value);fillVal(a,"pollServerVal","15");document.getElementById("pollServerEnabled").checked=0<parseInt(document.getElementById("pollServerVal").value);fillVal(a,"clearClipboardSecsVal","30");document.getElementById("clearClipboardSecsEnabled").checked=0<
parseInt(document.getElementById("clearClipboardSecsVal").value);check(a,"searchNotes",1);check(a,"recentUsed",1);fillVal(a,"recentUsedCount","10");document.getElementById("recentUsed").checked=0<parseInt(document.getElementById("recentUsedCount").value);setSelect(a,"openpref","tabs");setSelect(a,"defaultffid","0");setSelect(a,"language","");last_logout_on_close=a.lpGetPref("logoffWhenCloseBrowser",0);last_logout_on_close_val=a.lpGetPref("logoffWhenCloseBrowserVal",0);for(var b="generateHk recheckHk searchHk nextHk prevHk homeHk submitHk saveallHk logoffHk defaultffidHk openpopoverHk".split(" "),
d=0;d<b.length;d++){var e=b[d],f=a.lpGetPref(e+"KeyCode"),c=a.lpGetPref(e+"Mods");"undefined"!=typeof f&&"undefined"==f&&(f=0);"undefined"!=typeof c&&"undefined"==c&&(c=0);optionsData.HotKeys[e+"KeyCode"]=f;optionsData.HotKeys[e+"Mods"]=c;writeHotKeyValue(e)}document.getElementById("login_site_prompt").checked=a.g_prompts.login_site_prompt;document.getElementById("edit_site_prompt").checked=a.g_prompts.edit_site_prompt;document.getElementById("edit_sn_prompt").checked=a.g_prompts.edit_sn_prompt;document.getElementById("view_pw_prompt").checked=
a.g_prompts.view_pw_prompt;document.getElementById("view_ff_prompt").checked=a.g_prompts.view_ff_prompt}function filldefaultffid(){var a=document.getElementById("defaultffid");a.options[0]=new Option("","0",!1,!1);for(var b in getBG().g_formfills)getBG().check_ident_ffid(getBG().g_formfills[b].ffid)&&(a.options[a.options.length]=new Option(getBG().g_formfills[b].decprofilename,getBG().g_formfills[b].ffid,!1,!1))}
function fillLanguage(){var a=document.getElementById("language"),b;for(b in g_langs)if(!g_ischrome||""==b)a.options[a.options.length]=new Option(gs(g_langs[b]),b,!1,!1)}
function createMenu(){var a={general:{icon:"images/icon_lock.png",title:gs("General"),cmd:"general"},notifications:{icon:"images/icon_bell.png",title:gs("Notifications"),cmd:"notifications"},hotkeys:{icon:"images/keyboard.png",title:gs("HotKeys"),cmd:"hotkeys"},accountsettings:{icon:"icon.gif",title:gs("Account Settings"),cmd:"accountsettings",hidden:getBG().g_hideacctsettings},advanced:{icon:"images/icon_preferences.png",title:gs("Advanced"),cmd:"advanced"}},b="",d,e,f={};for(d in a)if(null==a[d])b+=
'<div id="menu'+d+'" class="menuspacer"><div></div></div>';else{var c="undefined"!=typeof a[d].hidden&&a[d].hidden?' style="display:none;" ':"";e="undefined"==typeof a[d].cmd?"":' data-lpcmd="'+a[d].cmd+'" ';b+='<div id="menu'+d+'" class="menubutton"'+e+c+'><div class="menubuttontext" style="background:url('+a[d].icon+') no-repeat 3px 3px;">'+a[d].title+"</div></div>";"undefined"!=typeof a[d].cmd&&(f["menu"+d]=function(){menuaction(this.getAttribute("data-lpcmd"))})}document.getElementById("menu").innerHTML=
b;for(d in f)document.getElementById(d).addEventListener("click",f[d])}function ischecked(a){return document.getElementById(a).checked?1:0}function getVal(a){return document.getElementById(a).value}function selectedValue(a){a=document.getElementById(a);return a.options[a.selectedIndex].value}
function dosave(a){for(var b=getBG(),d=!1,e="generateHk recheckHk searchHk nextHk prevHk homeHk submitHk saveallHk logoffHk defaultffidHk openpopoverHk".split(" "),f=!1,c=0;c<e.length-1;c++){var g=optionsData.HotKeys[e[c]+"KeyCode"];if(!("undefined"==typeof g||!g||""==g||0==g||"0"==g)){var j=optionsData.HotKeys[e[c]+"Mods"];if(!("undefined"==typeof j||!j||""==j)){for(var k=c+1;k<e.length;k++){var h=optionsData.HotKeys[e[k]+"KeyCode"];if(!("undefined"==typeof h||!h||""==h||0==h||"0"==h)){var l=optionsData.HotKeys[e[k]+
"Mods"];if(!("undefined"==typeof l||!l||""==l)&&h==g&&l==j){f=!0;break}}}if(f)break}}}if(f)return alert(gs("You cannot assign more than one HotKey the same value.")),!1;f=!1;document.getElementById("login_site_prompt").checked!=b.g_prompts.login_site_prompt&&(f=!0);document.getElementById("edit_site_prompt").checked!=b.g_prompts.edit_site_prompt&&(f=!0);document.getElementById("edit_sn_prompt").checked!=b.g_prompts.edit_sn_prompt&&(f=!0);document.getElementById("view_pw_prompt").checked!=b.g_prompts.view_pw_prompt&&
(f=!0);document.getElementById("view_ff_prompt").checked!=b.g_prompts.view_ff_prompt&&(f=!0);if(f&&!a&&b.lploggedin)b.security_prompt(function(){dosave(!0)});else{b.lpPutGblPref("disablecrpw",ischecked("disablecrpw"));c=!1;a=b.g_prefoverrides;if("undefined"==typeof a.logoffclosebrowser||-1==a.logoffclosebrowser)b.lpPutGblPref("logoffWhenCloseBrowser",ischecked("logoffWhenCloseBrowser")),b.lpPutGblPref("logoffWhenCloseBrowserVal",getVal("logoffWhenCloseBrowserVal"));else if(ischecked("logoffWhenCloseBrowser")!=
last_logout_on_close||getVal("logoffWhenCloseBrowserVal")!=last_logout_on_close_val)c=!0;g=getVal("idleLogoffVal");document.getElementById("idleLogoffEnabled").checked?0>=parseInt(g)&&(g="15"):g="0";"undefined"==typeof a.logoffidle||-1==a.logoffidle?b.lpPutUserPref("idleLogoffVal",g):g!=a.logoffidle&&(c=!0);b.lpGetPref("pollServerVal","15")!=getVal("pollServerVal")&&("undefined"==typeof b.g_flags.pollIntervalSetByPolicy?(a=getVal("pollServerVal"),document.getElementById("pollServerEnabled").checked?
0>=parseInt(a)?a="15":5>parseInt(a)&&(a="5"):a="0",b.lpPutUserPref("pollServerVal",a)):c=!0);c&&alert(gs("Company policy prevents changing some settings, not all updates have been saved."));b.lpPutUserPref("highlightFields",ischecked("highlightFields"));b.lpPutUserPref("automaticallyFill",ischecked("automaticallyFill"));b.lpPutGblPref("showvault",ischecked("showvault"));b.lpPutUserPref("showAcctsInGroups",ischecked("showAcctsInGroups"));b.lpPutGblPref("hideContextMenus",ischecked("hideContextMenus"));
b.lpPutUserPref("donotoverwritefilledfields",ischecked("donotoverwritefilledfields"));b.lpPutUserPref("showNotifications",ischecked("showNotifications"));b.lpPutUserPref("showGenerateNotifications",ischecked("showGenerateNotifications"));b.lpPutUserPref("showFormFillNotifications",ischecked("showFormFillNotifications"));b.lpPutUserPref("showSaveSiteNotifications",ischecked("showSaveSiteNotifications"));b.lpPutUserPref("showNotificationsAfterClick",ischecked("showNotificationsAfterClick"));b.lpPutUserPref("showFillNotificationBar",
ischecked("showFillNotificationBar"));b.lpPutUserPref("showSaveNotificationBar",ischecked("showSaveNotificationBar"));b.lpPutUserPref("showChangeNotificationBar",ischecked("showChangeNotificationBar"));c=b.lpGetPref("usepopupfill",1);ischecked("usepopupfill")!=c&&(d=!0);b.lpPutUserPref("usepopupfill",ischecked("usepopupfill"));b.lpPutGblPref("usepopupfill",ischecked("usepopupfill"));b.lpPutUserPref("showmatchingbadge",ischecked("showmatchingbadge"));"undefined"!=typeof chrome&&!ischecked("showmatchingbadge")&&
b.clear_badge_text();c=getVal("autoautoVal");document.getElementById("autoautoEnabled").checked?0>=parseInt(c)?c="25":10>parseInt(c)&&(c="10"):c="0";b.lpPutUserPref("autoautoVal",c);b.lpPutUserPref("warninsecureforms",ischecked("warninsecureforms"));b.lpPutUserPref("dontfillautocompleteoff",ischecked("dontfillautocompleteoff"));c=getVal("clearClipboardSecsVal");document.getElementById("clearClipboardSecsEnabled").checked?0>=parseInt(c)&&(c="30"):c="0";b.lpPutUserPref("clearClipboardSecsVal",c);b.lpPutUserPref("searchNotes",
ischecked("searchNotes"));b.lpPutUserPref("recentUsed",ischecked("recentUsed"));ischecked("recentUsed")?b.lpPutUserPref("recentUsedCount",parseInt(getVal("recentUsedCount"))):b.lpPutUserPref("recentUsedCount","0");b.lpPutGblPref("openloginstart",ischecked("openloginstart"));b.lpPutGblPref("storeLostOTP",ischecked("storeLostOTP"));b.lpPutUserPref("storeLostOTP",ischecked("storeLostOTP"));c=b.lpGetPref("enablenamedpipes",1);a=ischecked("enablenamedpipes");a!=c&&(d=!0);b.lpPutGblPref("enablenamedpipes",
a);b.lpPutGblPref("enablenewlogin",ischecked("enablenewlogin"));b.lpPutUserPref("clearfilledfieldsonlogoff",ischecked("clearfilledfieldsonlogoff"));b.lpPutUserPref("toplevelmatchingsites",ischecked("toplevelmatchingsites"));b.lpPutUserPref("openpref",selectedValue("openpref"));b.lpPutUserPref("defaultffid",selectedValue("defaultffid"));c=b.lpGetPref("language","");a=selectedValue("language");c!=a&&(d=!0);b.lpPutGblPref("language",a);c=1==last_logout_on_close&&0==last_logout_on_close_val;(ischecked("logoffWhenCloseBrowser")&&
0==getVal("logoffWhenCloseBrowserVal"))!=c&&alert(gs("You must restart Chrome or logoff and back in to get logoff on browser close changes to be reflected"));ischecked("storeLostOTP")||b.DeleteOTP();for(c=0;c<e.length;c++)a=e[c],b.lpPutGblPref(a+"KeyCode",optionsData.HotKeys[a+"KeyCode"]),b.lpPutGblPref(a+"Mods",optionsData.HotKeys[a+"Mods"]);f&&(b.g_prompts.login_site_prompt=document.getElementById("login_site_prompt").checked,b.g_prompts.edit_site_prompt=document.getElementById("edit_site_prompt").checked,
b.g_prompts.edit_sn_prompt=document.getElementById("edit_sn_prompt").checked,b.g_prompts.view_pw_prompt=document.getElementById("view_pw_prompt").checked,b.g_prompts.view_ff_prompt=document.getElementById("view_ff_prompt").checked,(g_issafari||g_isopera||g_ismaxthon)&&b.update_prompts(),b.rewritelocalfile());if(ischecked("logoffWhenCloseBrowser")||ischecked("idleLogoffEnabled"))if((1==b.lpGetPref("rememberpassword",-1)||b.g_master_password_saved)&&confirm(gs("You currently have LastPass set to remember your password.  Doing so essentially makes the automatically logoff options you've chosen useless.  Would you like LastPass to stop remembering your password?")))b.lpPutGblPref("rememberpassword",
0),b.deletesavedpw(b.g_username);"undefined"!=typeof chrome&&b.createContextMenus();d&&alert(gs("You must restart your browser before all of the changes will take effect."));b.lpWriteAllPrefs();b.start_idle_checker();b.setprefs("all","all");(g_issafari||g_isopera||g_ismaxthon)&&b.update_prefs("prefs");setTimeout(function(){getBG().closecurrenttab("prefs.html")},0)}}function docancel(){setTimeout(function(){getBG().closecurrenttab("prefs.html")},0)}
function openaccountsettings(){var a=getBG();a&&(a.unlock_plug2web(),a.openURL(a.base_url+"?ac=1&opensettings=1"));setTimeout(function(){window_close("prefs.html")},0)}function openhelptranslate(){var a=getBG();a&&a.openURL(a.base_url+"translate.php");setTimeout(function(){window_close("prefs.html")},0)}function getbinary(){var a=getBG();a&&a.install_binary()}var tabs=["general","notifications","hotkeys","accountsettings","advanced"];
function menuaction(a){for(var b in tabs){var d=tabs[b];document.getElementById("menu"+d).className="menubutton";document.getElementById(d).style.display="none"}document.getElementById("menu"+a).className="menubutton2";document.getElementById(a).style.display="block"}
function supernotification_handler(a){if(!0==showNotification_is_superset){if(null==a)return!1;a=a.target;if(null==a)return!1;var b;if(null!=a&&"undefined"!=typeof a.checked){b=!0==a.checked?black_color:gray_color;for(var d in notification_checkbox_ids)(g_issafari||g_isopera)&&"showSaveSiteNotifications"==notification_checkbox_ids[d].boxid||(document.getElementById(notification_checkbox_ids[d].boxid).checked=a.checked,document.getElementById(notification_checkbox_ids[d].labelid).style.color=b)}}return!1}
function notification_checkbox_handler(a){if(!0==showNotification_is_superset){if(null==a)return!1;a=a.target;if(null==a)return!1;var b=document.getElementById("showNotifications");"undefined"!=typeof a.checked&&!1==b.checked&&(a.checked=!1)}return!1}
function openhelp(a){switch(a){case "general":a="gengeneralprefs";break;case "appearance":a="genappearanceprefs";break;case "formfill":a="genformfillprefs";break;case "security":a="gensecurityprefs";break;case "notifications":a="notificationprefs";break;case "hotkeys":a="hotkeysprefs";break;case "advanced":a="advancedprefs";break;default:a="generalprefs"}var b=getBG(),d;b&&(d="function"==typeof b.gethelpurl?b.gethelpurl():b.g_helpurl,b.openURL(d+"&topic="+a));return!1};
