function upload_rsa_keys(a,b,c){if(lploggedin){var e="",d="",d="";b||(e="undefined"!=typeof a.publickey?a.publickey:encode_public_key(a),d="LastPassPrivateKey<"+("undefined"!=typeof a.privatekey?a.privatekey:encode_private_key(a))+">LastPassPrivateKey",d=AES.bin2hex(atob(AES.Encrypt({pass:g_local_key+g_local_key.substring(0,16),data:d,b64:!0,bits:256,mode:"cbc"}))).toUpperCase());a=g_local_key;c="";null!=a&&""!=a&&(c=AES.bin2hex(a),c=c.toUpperCase());a=""==c?"":SHA256(c);b=""==c?"":SHA256(d);c="undefined"==
typeof forcewriteprivatearg||0==forcewriteprivatearg?0:forcewriteprivatearg;d="privatekeyenc="+LP.en(d);d+="&publickey="+LP.en(e);d+="&forcewriteprivate="+LP.en(c);d+="&userkeyhexhash="+LP.en(a);d+="&privatekeyenchexhash="+LP.en(b);d+="&from="+LP.en("crplugin");lpMakeRequest(base_url+"uploadrsakeys.php",d,upload_rsa_keys_response,null)}}
function upload_rsa_keys_response(a){if(4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement){a=a.responseXML.documentElement.getElementsByTagName("ok");var b="";0<a.length&&(b=a[0].getAttribute("privatekeyenchex"),null!=b&&""!=b&&(writersaprivatekeyenchextodb(b),readrsaprivatekeyhexfromdb(!0,null,null,function(){g_shares&&0<g_shares.length&&(console_log("upload_rsa_keys_response found shares: reparse!"),get_accts_local(!0,"refetchsharing"))})))}}
function writersaprivatekeyenchextodb(a){null==g_username||""==g_username||(console_log("writersaprivatekeyenchextodb"),lpSaveData(a,"rsakey"))}
function readrsaprivatekeyhexfromdb(a,b,c,e){if(!g_nosharingkeys&&!(null==g_username||""==g_username||null==g_local_key))("undefined"==typeof a||!a)&&""!=lp_rsaprivatekeyhex&&(!c||SHA256(lp_rsaprivatekeyenchex)==c)?e&&e(lp_rsaprivatekeyhex):(rsa_clearvars(),a=opendb(),createDataTable(a),a&&a.transaction(function(a){a.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"rsakey"],function(a,d){if(0<d.rows.length){var g=d.rows.item(0).data;if(""==g||
null==g)DeleteFromDB("rsakey");else if(c&&SHA256(g)!=c)console_warn("RSA Hashes didn't match. Deleting local!"),DeleteFromDB("rsakey"),0==g_privkeyattempts&&(g_privkeyattempts=1,setTimeout(function(){console.error("BAH!!!");upload_rsa_keys(null,!0)},500));else{var h=AES.Decrypt({pass:g_local_key+g_local_key.substring(0,16),data:btoa(AES.hex2bin(g)),b64:!0,bits:256,mode:"cbc"}),j=rsa_extractprivatekey(h);null==j?(console_warn("failed to extract rsa key from file "+j),lpReportError("readrsaprivatekeyhexfromfile : failed to extract rsa key from file - did we change our password on another PC? datahex.length="+
g.length+" decryptedbin.length="+h.length),DeleteFromDB("rsakey")):(console_log("readrsaprivatekeyhexfromfile : all is good!"),lp_rsaprivatekeyenchex=g,lp_rsaprivatekeyhex=j,lp_rsaprivatekeyenchexserverhash=SHA256(lp_rsaprivatekeyenchex),e&&e(lp_rsaprivatekeyhex),g_shares&&(1==g_shares.length&&0==g_shares[0].id)&&(console_log("Shared folder found, we just got the key, reparse!"),get_accts_local()))}}else b&&upload_rsa_keys(null,!0)},function(a,b){console_log(b)})}))}
function rsa_extractprivatekey(a){if(38>=a.length)return lpReportError("rsa_extractprivatekey : failed to extract rsaprivatekeyhex : length="+a.length+" is too short"),null;if(0!=a.indexOf("LastPassPrivateKey<"))return lpReportError("rsa_extractprivatekey : failed to extract rsaprivatekeyhex : expected_prefix='LastPassPrivateKey<'   actual_prefix='"+a.substring(0,19)+"'"),null;var b=a.indexOf(">LastPassPrivateKey");if(b!=a.length-19)return lpReportError("rsa_extractprivatekey : failed to extract rsaprivatekeyhex : expected_prefix='LastPassPrivateKey<'   actual_prefix='"+
a.substring(0,19)+"'"),null;a=a.substring(19,b);return 2E3>a.length?(lpReportError("rsa_extractprivatekey : failed to extract rsaprivatekeyhex : we expect a length of approx 2426    actual_length="+a.length),null):a}function rsa_userchangedpassword(){console_log("rsa_userchangedpassword : called");DeleteFromDB("rsakey");rsa_clearvars()}function rsa_clearvars(){lp_rsaprivatekeyenchexserverhash=lp_rsaprivatekeyenchex=lp_rsaprivatekeyhex=""}var lppendingsharests=0;
function rsa_setpendingsharests(a){lppendingsharests="undefined"!=typeof a&&a?0:(new Date).getTime()}
function rsa_acceptpendingshares(a){if(lploggedin&&!(lploggedinoffline||null==g_local_key))if(""!=lp_rsaprivatekeyhex){if(rsaprivatekeyhex=lp_rsaprivatekeyhex,0!=g_pendings.length)if(1E4>(new Date).getTime()-lppendingsharests)console_log("lprsa_acceptpendingshares : skipping because we were already called very recently");else{rsa_setpendingsharests();a=[];for(var b in g_pendings){var c=g_pendings[b];if(1==c.shareautoaccept){var e="",e="";if(have_nplastpass()&&"function"==typeof g_nplastpass.xCryptoRSADecrypt)e=
g_nplastpass.xCryptoRSADecrypt(rsaprivatekeyhex,c.sharekeyenchex),e=AES.hex2bin(e);else{e=new RSAKey;if(!parse_private_key(e,lp_rsaprivatekeyhex)){console_error("Private key could not be parsed while auto accepting shares");return}e=e.decrypt(c.sharekeyenchex);AES.bin2hex(e)}if(""==e){console_error("Share key bin empty while auto accepting shares");return}var d=dec(c.sharename,e),f=dec(c.sharegroup,e),k=dec(c.username,e),g=dec(c.password,e),h=dec(c.extra,e),j=!0,l={};for(b in c.shareafids)if(l[b]=
dec(c.shareafids[b],e),""!=c.shareafids[b]&&""==l[b]){j=!1;break}if(""!=c.sharename&&""==d||""!=c.sharegroup&&""==f||""!=c.username&&""==k||""!=c.password&&""==g||""!=c.extra&&""==h||!j)lpReportError("lprsa_acceptpendingshares : failing autoaccept of share because we failed to decrypt at least one value");else{var m=lpenc(d),n=lpenc(f),p=lpenc(k),q=lpenc(g),r=lpenc(h),j=!0,e={};for(b in l)if(e[b]=lpenc(l[b]),""!=l[b]&&""==e[b]){j=!1;break}if(""!=d&&""==m||""!=f&&""==n||""!=k&&""==p||""!=g&&""==q||
""!=h&&""==r||!j)lpReportError("lprsa_acceptpendingshares : failing autoaccept of share because we failed to reencrypt at least one value");else{c={aid:c.id,name:m,group:n,username:p,password:q,extra:r};d=0;for(b in e)c["afid"+d]=b,c["afidv"+d]=e[b],++d;c.numafids=d;a.push(c)}}}}if(0<a.length){c="cmd="+LP.en("autoacceptshares")+"&from="+LP.en("crplugin")+"&numshares="+LP.en(a.length);e=0;for(b in a){d="&share"+e;++e;for(var s in a[b])c+=d+s+"="+LP.en(a[b][s])}console_log("rsa_acceptpendingshares : issuing server request to autoaccept "+
a.length+" shares");lpMakeRequest(base_url+"showacceptshare.php",c,rsa_acceptpendingsharesresponse)}else console_log("rsa_acceptpendingshares : no shares to autoaccept so not issuing server request")}}else a||readrsaprivatekeyhexfromdb(!1,null,null,rsa_acceptpendingshares)}
function rsa_acceptpendingsharesresponse(a){if(4==a.readyState)if(console_log("rsa_acceptpendingsharesresponse : received response from server"),200!=a.status)lpReportError("lprsa_acceptpendingsharesresponse : request failed status="+a.status);else if(null==a.responseXML||null==a.responseXML.documentElement)lpReportError("lprsa_acceptpendingsharesresponse : request failed xml invalid A text="+a.responseText);else{var b=a.responseXML.documentElement.getElementsByTagName("ok");!b||0==b.length?lpReportError("lprsa_acceptpendingsharesresponse : request failed xml invalid B text="+
a.responseText):get_accts()}}function rsa_setshareeautopushests(a){g_shareeautopushests="undefined"!=typeof a&&a?0:(new Date).getTime()}function rsa_acceptshareeautopushes(){var a=!1,b;for(b in g_shareeautopushes){a=!0;break}if(a&&lploggedin&&!(lploggedinoffline||null==g_local_key)&&!(1E4>(new Date).getTime()-lpshareeautopushests))rsa_setshareeautopushests(),readrsaprivatekeyhexfromdb(!1,null,null,rsa_acceptshareeautopushes2)}
function rsa_acceptshareeautopushes2(a){var b=[],c;for(c in g_shareeautopushes)for(var e in g_shareeautopushes[c]){var d=g_shareeautopushes[c][e],f="";if(have_nplastpass()&&"function"==typeof g_nplastpass.xCryptoRSADecrypt)f=g_nplastpass.xCryptoRSADecrypt(a,d.sharekeyhexenc),f=AES.hex2bin(f);else{f=new RSAKey;if(!parse_private_key(f,a)){console_error("Private key could not be parsed while auto accepting shares");return}f=f.decrypt(d.sharekeyhexenc)}""==f||null==f||(d=reencryptShareeAutoPushes(f,d,
c),null!=d&&("undefined"==typeof b[c]&&(b[c]=[]),b[c].push(d)))}a="cmd="+LP.en("updateautoshareepushes")+"&from="+LP.en("ffplugin");f=e=0;for(c in b){++e;for(var k in b[c]){var g="&share"+f,d=b[c][k],h;for(h in d)a+=g+h+"="+LP.en(d[h]);++f}}a+="&numupdates="+LP.en(f);0<f?(lplastgetaccounts=0,lpMakeRequest(base_url+"showacceptshare.php",a,rsa_acceptshareeautopushesresponse)):lpdbg("sharing","lprsa_acceptshareeautopushes : no shareeautopushes so not issuing server request")}
function rsa_acceptshareeautopushesresponse(a){if(4==a.readyState)if(lpdbg("sharing","lprsa_acceptshareeautopushesresponse : received response from server"),200!=a.status)lpReportError("lprsa_acceptshareeautopushesresponse : request failed status="+a.status);else if(null==a.responseXML||null==a.responseXML.documentElement)lpReportError("lprsa_acceptshareeautopushesresponse : request failed xml invalid A text="+a.responseText);else{var b=a.responseXML.documentElement.getElementsByTagName("ok");!b||
0==b.length?lpReportError("lprsa_acceptshareeautopushesresponse : request failed xml invalid B text="+a.responseText):get_accts()}}
function rsa_shareeautopushesresponse(a,b){if(4!=a.readyState||200!=a.status||null==a.responseXML||null==a.responseXML.documentElement||"undefined"==typeof b||null==b)return!1;var c=(new Date).getTime(),e=b.url,d=b.aid,f=b.handler,k=b.param,g=b.postdata,d="undefined"!=typeof g_sites[d]?g_sites[d]:"undefined"!=typeof g_securenotes[d]?g_securenotes[d]:null;null==d&&(d={name:"",group:"",username:"",password:"",extra:""});g=createShareeAutoPushesResponse(a,b,d);if(!1==g)return!1;c=((new Date).getTime()-
c)/1E3;lpdbg("sharing","Finished RSA encryption. Total time taken = "+c+" seconds");lpdbg("sharing","Reissuing request to "+e+" with postdata="+g);lplastgetaccounts=0;lpMakeRequest(e,g,f,null,k);return!0}
function lprsa_encryptdata(a,b){var c=null;if(have_nplastpass()&&"function"==typeof g_nplastpass.xCryptoRSAEncrypt)c=g_nplastpass.xCryptoRSAEncrypt(a,b);else{c=new RSAKey;if(!parse_public_key(c,a))return console_error("Private key could not be parsed while auto accepting shares"),!1;c=c.encrypt(AES.hex2bin(b))}return""!=b&&(null==c||""==c)?(lpReportError("lprsa_encryptdata : Failed to rsaencrypt data using publickeyhex="+a),!1):c}
function lprsa_rsadecrypt(a){if(""==lp_rsaprivatekeyhex)return null;if(have_nplastpass()&&"function"==typeof g_nplastpass.xCryptoRSADecrypt)a=g_nplastpass.xCryptoRSADecrypt(lp_rsaprivatekeyhex,a);else{var b=new RSAKey;if(!parse_private_key(b,lp_rsaprivatekeyhex))return null;a=b.decrypt(a);a=AES.bin2hex(a).toUpperCase()}return a}
function lprsa_encryptmultiple(a){a=JSON.parse(a);for(var b=0;b<a.length;++b){if("undefined"==typeof a[b].valuehex||"undefined"==typeof a[b].publickeyhex||""==a[b].publickeyhex)return null;if(have_nplastpass()&&"function"==typeof g_nplastpass.xCryptoRSAEncrypt)a[b].valuehexenc=g_nplastpass.xCryptoRSAEncrypt(a[b].publickeyhex,a[b].valuehex);else{var c=new RSAKey;if(!parse_public_key(c,a[b].publickeyhex))return null;a[b].valuehexenc=c.encrypt(AES.hex2bin(a[b].valuehex)).toUpperCase()}if(""==a[b].valuehexenc||
null==a[b].valuehexenc)return null}return JSON.stringify(a)};
