document.getElementById("_docwrite_site2")&&(document.getElementById("_docwrite_site2").innerHTML=gs("Add New Site"));document.getElementById("_docwrite_site3")&&(document.getElementById("_docwrite_site3").innerHTML=gs("URL:"));document.getElementById("_docwrite_site4")&&(document.getElementById("_docwrite_site4").innerHTML=gs("Name:"));document.getElementById("_docwrite_site5")&&(document.getElementById("_docwrite_site5").innerHTML=gs("Group:"));
document.getElementById("_docwrite_site6")&&(document.getElementById("_docwrite_site6").innerHTML=gs("Username:"));document.getElementById("_docwrite_site7")&&(document.getElementById("_docwrite_site7").innerHTML=gs("History"));document.getElementById("_docwrite_site8")&&(document.getElementById("_docwrite_site8").innerHTML=gs("Password:"));
if(g_eye_show&&document.getElementById("passwordtoggle")){var img=getBG().g_ischrome?"images/svg/eye-shown.svg":"images/vault/eye-shown.png";document.getElementById("passwordtoggle").innerHTML='<a href="#" class="tooltip eye'+(g_isopera?"":" eye2")+'"> <img src="'+img+'" id="passwordtoggleimg" alt="'+gs("[Show]")+'"/><span tabindex="-1" id="passwordtoggle_tooltip">'+gs("Show Password")+"</span></a>"}
document.getElementById("_docwrite_site10")&&(document.getElementById("_docwrite_site10").innerHTML=gs("History"));document.getElementById("_docwrite_site12")&&(document.getElementById("_docwrite_site12").innerHTML=gs("Fields:"));document.getElementById("_docwrite_site13")&&(document.getElementById("_docwrite_site13").innerHTML=gs("Note Type")+":");document.getElementById("_docwrite_site14")&&(document.getElementById("_docwrite_site14").innerHTML=gs("Notes:"));
document.getElementById("_docwrite_site15")&&(document.getElementById("_docwrite_site15").innerHTML=gs("Favorite"));document.getElementById("_docwrite_site16")&&(document.getElementById("_docwrite_site16").innerHTML=gs("Never AutoFill"));document.getElementById("_docwrite_site17")&&(document.getElementById("_docwrite_site17").innerHTML=gs("Edit Form Fields"));document.getElementById("_docwrite_site18")&&(document.getElementById("_docwrite_site18").innerHTML=gs("Require Password Reprompt"));
document.getElementById("_docwrite_site19")&&(document.getElementById("_docwrite_site19").innerHTML=gs("AutoLogin"));document.getElementById("_docwrite_site20")&&(document.getElementById("_docwrite_site20").innerHTML=gs("Replace Existing Site"));
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){onLoad()});window.addEventListener("resize",function(){onResize()});document.getElementById("lpform").submit=function(){};document.getElementById("addnewsite").addEventListener("click",function(){fix_addreplace()});document.getElementById("showusernamehistory").onclick=function(){show_history(!0);return!1};document.getElementById("passwordtoggle").onclick=function(){toggle_password(document.getElementById("password"),
document.getElementById("passwordtoggle"));return!1};document.getElementById("showpasswordhistory").onclick=function(){show_history(!1);return!1};document.getElementById("password").addEventListener("keyup",function(){update_password_meter("",this.value)});document.getElementById("notestype").onchange=function(){buildSecureNotes()};document.getElementById("notestype").addEventListener("focus",function(){this.blur()});document.getElementById("editfields").onclick=function(){doeditfields();return!1};
document.getElementById("replaceexistingsite").addEventListener("click",function(){fix_addreplace()});document.getElementById("del").addEventListener("click",function(){dodel();return!1});document.getElementById("share").addEventListener("click",function(){doshare();return!1});document.getElementById("save").addEventListener("click",function(){dosave();return!1});document.getElementById("cancel").addEventListener("click",function(){docancel();return!1});document.getElementById("lpaddattach").addEventListener("click",
function(){addattach();return!1})});
